fix(frontend): typo in filename
SocialGouv/code-du-travail-numerique pull request #1000
Opened 2019-07-03 15:11 UTC by UnbearableBear

It's all in the title !

2019-07-03 15:27 UTC, UnbearableBear commented on packages/code-du-travail-frontend/pages/outils.js
> -import { CalculateurIndemnite } from "../src/outils/indemniteLicenciement";
Je comprends pas pourquoi il n'affiche pas que j'ai renommé le dossier aussi ??

2019-07-03 15:28 UTC, UnbearableBear commented on packages/code-du-travail-frontend/pages/outils.js
> -import { CalculateurIndemnite } from "../src/outils/indemniteLicenciement";
ça m'angoisse

2019-07-04 06:27 UTC, lionelB requested changes
Ok pour le simulateur d'embauche mais il me semble que la conventions c'est de gardait les Majuscule pour des composants et mettre les dossiers en minuscules.

2019-07-04 08:45 UTC, UnbearableBear commented
Ah il me semblait que la convention c'était de garder le nom d'un dossier en majuscule si il contient un component récupérable via un index ?

2019-07-04 09:06 UTC, lionelB commented
@UnbearableBear ah, oui au temps pour moi,  :/

2019-07-04 11:10 UTC, lionelB approved these changes

2019-07-05 11:48 UTC, merged