refactor(frontend): normalize margins
SocialGouv/code-du-travail-numerique pull request #1005
Opened 2019-07-04 17:04 UTC by UnbearableBear

Approved by aurélie and virginie already

before:
<img width="1190" alt="Screenshot 2019-07-04 at 18 59 25" src="https://user-images.githubusercontent.com/705453/60681166-8676fb80-9e8e-11e9-95df-a1138e74dd56.png">
<img width="351" alt="Screenshot 2019-07-04 at 18 59 39" src="https://user-images.githubusercontent.com/705453/60681167-870f9200-9e8e-11e9-892b-f420507981b6.png">

after: 
<img width="1154" alt="Screenshot 2019-07-04 at 18 58 54" src="https://user-images.githubusercontent.com/705453/60681178-8f67cd00-9e8e-11e9-8568-1bc4d0f35ec6.png">
<img width="367" alt="Screenshot 2019-07-04 at 18 59 10" src="https://user-images.githubusercontent.com/705453/60681179-90006380-9e8e-11e9-99e3-3d4d08db35bb.png">

2019-07-05 07:26 UTC, lionelB requested changes
Nice !  Can you document a little bit about wrapper large usage and perhaps general rules used for spacing ?

2019-07-05 07:26 UTC, lionelB commented on packages/code-du-travail-frontend/src/outils/indemniteLicenciement/StepItems.js
> +  width: 135px;
in `em` / `rem` please :)

2019-07-05 08:51 UTC, UnbearableBear commented on packages/code-du-travail-frontend/src/outils/indemniteLicenciement/StepItems.js
> +  width: 135px;
👌

2019-07-05 09:02 UTC, UnbearableBear commented
Yes let me add the explenations in the ui

2019-07-08 15:29 UTC, lionelB approved these changes
👍

2019-07-08 15:38 UTC, merged