Refactor kthxbye python code
SocialGouv/code-du-travail-numerique pull request #1105
Opened 2019-08-21 14:48 UTC by lionelB

- replace python code by js
- update Dockerfile and ci

2019-08-21 15:03 UTC, lionelB commented
don't worry, I forgot to update the readme

2019-08-21 16:52 UTC, douglasduteil requested changes

2019-08-21 16:52 UTC, douglasduteil commented on .gitlab-ci/variables.yml
> +  PYTHON_VERSION: 3.7.2-alpine
Not on alphabetical order :(

2019-08-21 16:52 UTC, douglasduteil commented on packages/code-du-travail-data/package.json
> +    "esm": "^3.2.25",
Esm is a devdep no ?

2019-08-22 07:08 UTC, lionelB commented on packages/code-du-travail-data/package.json
> +    "esm": "^3.2.25",
it is used by check-slug script too

2019-08-22 07:11 UTC, lionelB commented
@douglasduteil updated !

2019-08-22 07:41 UTC, revolunet approved these changes
🎉

2019-08-22 09:05 UTC, lionelB commented on .gitlab-ci/variables.yml
> +  PYTHON_VERSION: 3.7.2-alpine
done !

2019-08-22 09:05 UTC, lionelB commented on packages/code-du-travail-data/package.json
> +    "esm": "^3.2.25",
and in dump script too

2019-08-22 09:32 UTC, douglasduteil approved these changes

2019-08-23 13:51 UTC, merged