Update datafiller data
SocialGouv/code-du-travail-numerique pull request #1504
Opened 2019-10-18 10:36 UTC by revolunet

2019-10-18 15:35 UTC, lionelB reviewed
sounds good to me, je fais la modif ?

2019-10-18 15:35 UTC, lionelB commented on packages/code-du-travail-data/dataset/datafiller/fetch-requetes.js
> +    //console.log(e);
console.error() will not pollute output thus, allow to know wich url fails
```suggestion
    console.error(`fail to retrieve tittle on ${url}`);
    console.error(e);
```

2019-10-24 09:35 UTC, lionelB requested changes
the last item is empty but link to a page 
http://0fec4cb.code-du-travail-numerique.dev.factory.social.gouv.fr/themes/112-formalites-dembauche

2019-11-06 22:20 UTC, revolunet commented
closed in favor of #1654

2019-11-06 22:20 UTC, closed without merging