Feat/elastic klout
SocialGouv/code-du-travail-numerique pull request #1753
Opened 2019-11-19 17:41 UTC by lionelB

use external elasticsearch

2019-12-09 11:33 UTC, douglasduteil approved these changes

2019-12-11 11:49 UTC, douglasduteil requested changes

2019-12-11 11:49 UTC, douglasduteil commented on .gitlab-ci/stages/deploy.yml
> +.resolve_helm_render_args: &resolve_helm_render_args |
to remove in v3 gitlab-ci-yaml
`PRODUCTION` var must be defined

2019-12-11 11:49 UTC, douglasduteil commented on .gitlab-ci/stages/deploy.yml
> +  - "https://raw.githubusercontent.com/SocialGouv/gitlab-ci-yml/feat/hpa/base_deploy_hpa_chart_stage.yml"
Use merged version

2019-12-11 11:49 UTC, douglasduteil commented on .gitlab-ci/stages/deploy.yml
> +  - "https://raw.githubusercontent.com/SocialGouv/gitlab-ci-yml/v2.2.1/register-stage.yml"
Update to v3

2019-12-11 11:49 UTC, douglasduteil commented on .gitlab-ci/stages/deploy.yml
> +    # IMAGE_TAG: ${CI_COMMIT_SHA}
Duplicate ?

2019-12-11 11:49 UTC, douglasduteil commented on .gitlab-ci/stages/deploy.yml
> +    - *resolve_helm_render_args
to remove in v3 gitlab-ci-yaml

2019-12-11 11:49 UTC, douglasduteil commented on .gitlab-ci/stages/deploy.yml
> +    - *resolve_helm_render_args
to remove in v3 gitlab-ci-yaml

2019-12-11 11:49 UTC, douglasduteil commented on .gitlab-ci/stages/deploy.yml
> +    - kubectl apply -f ./job.yml || true
Merge both lines `envsubst < ./.k8s/data.job.yml | kubectl apply -` (je crois...)

2019-12-11 11:49 UTC, douglasduteil commented on .gitlab-ci/stages/deploy.yml
> +    - *resolve_helm_render_args
to remove in v3 gitlab-ci-yaml

2019-12-11 11:49 UTC, douglasduteil commented on .gitlab-ci/stages/notify.yml
> +#    - GH_TOKEN=${GITHUB_TOKEN} yarn lerna version ${LERNA_ARGS:="--force-publish --yes"}
Remove comments we have the git history ;)

2019-12-11 11:49 UTC, douglasduteil commented on .gitlab-ci/stages/notify.yml
> +#      https://gitlab.factory.social.gouv.fr/api/v4/projects/51/trigger/pipeline
Remove comments we have the git history ;)

2019-12-11 11:49 UTC, douglasduteil commented on .gitlab-ci/stages/notify.yml
> -Production:
We need this

2019-12-11 11:49 UTC, douglasduteil commented on .gitlab-ci/stages/notify.yml
> -Release:
We need this

2019-12-11 11:49 UTC, douglasduteil commented on docker/elasticsearch/Dockerfile
> +COPY ./elasticsearch.yml  config/elasticsearch.yml
```suggestion
COPY ./elasticsearch.yml config/elasticsearch.yml
```

2019-12-11 11:49 UTC, douglasduteil commented on packages/code-du-travail-api/Dockerfile
> +RUN yarn add elastic-apm-node --production
Why not a __real__ api dependency ?

2019-12-11 11:49 UTC, douglasduteil commented on packages/code-du-travail-api/package.json
>      "jest": "^24.9.0",
Jest as dependencies ??

2019-12-11 11:49 UTC, douglasduteil commented on packages/code-du-travail-api/package.json
>      "abort-controller": "3.0.0",
```suggestion
```

2019-12-11 11:49 UTC, douglasduteil commented on packages/code-du-travail-api/package.json
>      "abort-controller": "3.0.0",
Require yarn.lock update

2019-12-11 11:49 UTC, douglasduteil commented on packages/code-du-travail-api/src/server/routes/search/index.js
> +    // const query_vector = await fetch(
We need this

2019-12-11 18:04 UTC, douglasduteil requested changes

2019-12-11 18:04 UTC, douglasduteil commented on .gitlab-ci/stages/06-deploy.yml
> +  - "https://raw.githubusercontent.com/SocialGouv/gitlab-ci-yml/v3.0.7/base_register_stage.yml"
use 

```
- project
  file
  ref
```

2019-12-11 18:04 UTC, douglasduteil commented on .gitlab-ci/stages/06-deploy.yml
> +    # IMAGE_TAG: ${CI_COMMIT_SHA}
to remove

2019-12-11 18:04 UTC, douglasduteil commented on .gitlab-ci/stages/07-notify.yml
> +#.notify_stage: &notify_stage
comments to remove

2019-12-11 18:05 UTC, douglasduteil commented
**TODO** 

- [ ] should test fast release (skip ci) on commit release
- [ ] should test production more on prod cluster

2019-12-16 22:13 UTC, lionelB commented
@ylascombe je pense qu'il manque les secrets k8s. est ce qu'on peut se faire un point demain à ce sujet ?

2019-12-19 22:39 UTC, lionelB commented
@douglasduteil I've updated the pipelines to take advantages of external_pull_request
- use manual deployement for feature branch (external_pull_request)
- use automatique deployement for prod
- release job only register images
- avoid running job for  release commit

2019-12-23 17:56 UTC, douglasduteil requested changes

2019-12-23 17:56 UTC, douglasduteil commented on .gitlab-ci/stages/deploy.yml
> +    entrypoint: [""]
can be replaced by 

```
image: registry.gitlab.factory.social.gouv.fr/socialgouv/docker/kubectl:0.20.0
```

?

2019-12-23 17:56 UTC, douglasduteil commented on .k8s/api/deployment.yml
> +<<<<<<< HEAD
Ouch !

2019-12-23 17:56 UTC, douglasduteil commented on .k8s/api/deployment.yml
> +||||||| merged common ancestors
Ouch !

2019-12-23 17:56 UTC, douglasduteil commented on .k8s/api/deployment.yml
> +=======
Ouch !

2019-12-23 17:56 UTC, douglasduteil commented on .k8s/api/deployment.yml
> +>>>>>>> fix initcontainer credentials
Ouch !

2019-12-23 18:01 UTC, lionelB commented on packages/code-du-travail-api/Dockerfile
> +RUN yarn add elastic-apm-node --production
because it's not working with ncc

2019-12-24 10:23 UTC, douglasduteil approved these changes

2019-12-24 11:06 UTC, merged