build(docker): explicite the node image tag version
SocialGouv/code-du-travail-numerique pull request #1768
Opened 2019-11-20 17:29 UTC by douglasduteil

<img src=https://media.giphy.com/media/kBSOfIERSIljUUNk5v/giphy.gif width=693>

\from #1767

2019-11-20 17:35 UTC, lionelB requested changes
there is a lot more alipine image to explicit... 
thanks :)

2019-11-20 17:37 UTC, douglasduteil commented
Whet ?

2019-11-20 17:40 UTC, lionelB commented
- code-du-travail-numerique/packages/code-du-travail-api/Dockerfile
 - code-du-travail-numerique/packages/code-du-travail-data/Dockerfile
- code-du-travail-numerique/.gitlab-ci/stages/notify.yml
- code-du-travail-numerique/.k8s/api/deployment.yml
- code-du-travail-numerique/.k8s/data/deployment.yml 
- code-du-travail-numerique/.k8s/frontend/deployment.dev.yml (x2)
- code-du-travail-numerique/.k8s/frontend/deployment.prod.yml (x2)

2019-11-25 15:44 UTC, lionelB approved these changes

2019-11-25 15:54 UTC, merged