fix(wording): fix IndemnitePrecarite for #1834
SocialGouv/code-du-travail-numerique pull request #1863
Opened 2019-12-02 18:03 UTC by revolunet

2019-12-03 09:15 UTC, virginielastisneres requested changes
Parfait sur tout :) 
J'ai juste oublié de modifier une expression... le titre de l'outil...
"Simulation de la prime de précarité" devient "Simulation de l'indemnité de précarité"
et "Simuler la prime de précarité" devient "Simulation de l'indemnité de précarité"

2019-12-03 15:51 UTC, revolunet commented
updated

2019-12-05 20:04 UTC, lionelB commented
rebased :)

2019-12-05 20:06 UTC, lionelB approved these changes

2019-12-06 09:26 UTC, revolunet commented
much much better :)

2019-12-06 10:00 UTC, lionelB commented
prochaine étape on merge avec @cdt/data...outils :)

2019-12-06 10:24 UTC, virginielastisneres commented
oh :O je suis désolée j'ai fait une erreur dans le titre de l'outil je vous ai mis "simulation de l'indemnité de précarité" alors que c'est "simulateur de l'indemnité de précarité".... 
C'est entièrement ma faute je suis vraiment désolée de vous faire perdre du temps...

2019-12-06 15:10 UTC, virginielastisneres approved these changes

2019-12-06 16:45 UTC, merged