ci(k8s): override k8s nlp name
SocialGouv/code-du-travail-numerique pull request #2112
Opened 2019-12-30 23:22 UTC by lionelB

2019-12-30 23:57 UTC, revolunet approved these changes

2019-12-30 23:59 UTC, douglasduteil requested changes

2019-12-30 23:59 UTC, douglasduteil commented on .k8s/nlp.values.yml
> +  fullnameOverride: ${NLP_HOST}
no indentation

2019-12-31 00:15 UTC, douglasduteil approved these changes

2019-12-31 00:15 UTC, merged