Add files via upload
SocialGouv/code-du-travail-numerique pull request #2132
Opened 2019-12-31 14:28 UTC by jrduscher

2019-12-31 14:30 UTC, ClementChapalain approved these changes

2019-12-31 16:53 UTC, ClementChapalain requested changes
besoin de faire le point avec laura d'ici la fin de semaine, on merge pas pour l'instant

2020-01-06 15:22 UTC, jrduscher commented
@ClementChapalain . Modèles revus par l'équipe de validation.

2020-01-06 16:56 UTC, ClementChapalain approved these changes

2020-01-08 22:27 UTC, lionelB commented
superseded by #2204

2020-01-08 22:27 UTC, closed without merging