Fixed print date
SocialGouv/code-du-travail-numerique pull request #2217
Opened 2020-01-10 15:52 UTC by nkrmr

- Display date and hour into the header
- Remove URL's links
- Remove Toaster on print

2020-01-10 16:49 UTC, lionelB requested changes

2020-01-10 16:49 UTC, lionelB commented on packages/code-du-travail-frontend/src/outils/common/printResult.js
> +  const printDate = document.getElementById("printDate");
pourquoi tu fais pas ca directement dans un composant <DateHeader/> et gere que l'impression dans ce handler ?

2020-01-10 16:52 UTC, nkrmr commented on packages/code-du-travail-frontend/src/outils/common/printResult.js
> +  const printDate = document.getElementById("printDate");
Pour avoir la date et l'heure exacte du moment de l'impression

2020-01-10 17:33 UTC, lionelB commented on packages/code-du-travail-frontend/src/outils/common/printResult.js
> +  const printDate = document.getElementById("printDate");
Disons que ca complexifie pas mal en plus d'avoir une certaine adéherence avec l'id entre les fichiers pour 5min de difference (le moment on la page est affichée)

2020-01-10 17:53 UTC, nkrmr commented on packages/code-du-travail-frontend/src/outils/common/printResult.js
> +  const printDate = document.getElementById("printDate");
Ça peut être plus de 5mn, mais ok je vais changer

2020-01-10 18:27 UTC, lionelB commented on packages/code-du-travail-frontend/src/outils/common/printResult.js
> +  const printDate = document.getElementById("printDate");
pas pour rien car des qu'on fera imprimer n'importe quelle on aura l'info de quand l'impression date 
et ce qui est important c'est quand la date de quand la page a été généré et pas imprimer
car potentiellement on peut etre sur une page, faire une release qui met à jour les données. Dans ce cas, la date ne correspondra pas aux données

2020-01-13 09:48 UTC, UnbearableBear commented on packages/code-du-travail-frontend/src/outils/common/printResult.js
> +  const printDate = document.getElementById("printDate");
A voir si on préfère que l'utilisateur
- voie une date qui ne colle pas avec le moment de l'impression (potentiellement antérieure de plusieurs minutes voir demi-heure en fonction de l'endroit ou on place ce componsant, probablement dans _app), et à quel moment on décide de mettre à jour la date. Est-ce qu'on la met à jour à chaque fetch de data ? A chaque changement de page ou au rechargement complet du site ?)
- juste le faire au print et potentiellement avoir le problème que tu remontes.
A mon avis ça vaut le coup de demander à @ClementChapalain !

2020-01-13 19:54 UTC, lionelB commented
nickel pour la date, est ce qu'on peut supprimer le 
![image](https://user-images.githubusercontent.com/160320/72287145-d3f6d100-3646-11ea-97c1-328eededa020.png) a coté du lien du header ?

2020-01-13 19:59 UTC, nkrmr commented
Normalement il a été viré avec l'override du content en CSS

2020-01-13 20:24 UTC, lionelB commented
ben je viens de tester ta branche justement :)

2020-01-13 21:08 UTC, nkrmr commented
Ah yes je viens de voir c'est fou en local je ne l'ai pas. Je check ce que cela peut être

2020-01-14 10:19 UTC, nkrmr commented
Finalement vu avec Virginie on va garder le détail des URLs dans la page de résultat des outils.
<img width="490" alt="Screenshot 2020-01-14 at 11 19 03" src="https://user-images.githubusercontent.com/686395/72335705-b9147300-36bf-11ea-8cc8-e6eee56a1cfc.png">

2020-01-14 13:10 UTC, lionelB approved these changes

2020-01-14 13:39 UTC, merged

2020-01-14 13:39 UTC, nkrmr commented
Fix #2084