Manu/accordion fix
SocialGouv/code-du-travail-numerique pull request #2242
Opened 2020-01-14 11:20 UTC by UnbearableBear

Fix navigation issue with accordion and page target were title and top content was hidden behind header.
Fix id nit macthing when coming from search into fiche MT

closes #2226
closes #2231

2020-01-14 11:32 UTC, lionelB commented
il faudrait voir aussi ce que ca donne dans la page contribution qui integre des fiche SP / MT avec des accordion aussi

2020-01-21 16:11 UTC, UnbearableBear commented
Pfiouuu elle m'a fatigué cette PR !

2020-01-21 17:14 UTC, lionelB commented on packages/code-du-travail-frontend/src/layout/Header/index.js
> -    flex: 0 0 calc(50% + 4.635rem);
mitigated about the loosing author reference, ti sometimes eaisier to ask when we forgot why we do some stuff

2020-01-21 17:15 UTC, lionelB commented on packages/code-du-travail-frontend/src/layout/Header/index.js
> -    flex: 0 0 calc(50% + 4.635rem);
though it only work because of space-between :)

2020-01-21 17:17 UTC, lionelB submitted a review, later dismissed
Ok for me but before merge it would be nice to test it with IE11 / Edge from @virginielastisneres @jrduscher

2020-01-21 17:31 UTC, lionelB commented
from @virginielastisneres 
> https://15336d4-code-travail.dev.fabrique.social.gouv.fr/fiche-service-public/contribution-patronale-au-dialogue-social?q=Représentation
> PB d'ouverture des accordeons

et 
> https://15336d4-code-travail.dev.fabrique.social.gouv.fr/outils/preavis-demission
> le bouton suivant ne fonctionne pas

2020-01-22 10:31 UTC, nkrmr commented on packages/code-du-travail-frontend/pages/modeles-de-courriers/[slug].js
> -          <Alert varaint="primary">
Variant à la place de varaint ;)

2020-01-22 10:41 UTC, nkrmr approved these changes

2020-01-22 11:11 UTC, lionelB commented
from @jrduscher 
- [ ] affichage de la ligne LRAR/ remise en main propre : dépasse du cadre d'aperçu (https://15336d4-code-travail.dev.fabrique.social.gouv.fr/modeles-de-courriers/convocation-a-un-entretien-prealable-au-licenciement-economique-de-moins-de-10-salaries-pendant-30-jours)
- [ ] pas de possiblité choisir une CCN ( suggester down)
- [ ] titres du menu du header, qui partent du centre pour arriver à droite (animation)
pas de possibilité de lancer des outils pour tester ( arrêt en page d'introduction de l'outil)
- [ ] accessibilité: pas lançable

2020-01-22 11:12 UTC, lionelB requested changes
I propose to fix the changes first before and retest before merging

2020-01-22 11:23 UTC, UnbearableBear commented
@lionelB l'ensemble de bug remontés sont liée à l'erreur js sur IE11, qui devrait etre fixée désormais
Je fais retester à @virginielastisneres et @jrduscher pour en etre bien certain mais RAS de mon côté sous ie11 à présent.
Pour ce qui est de l'animation sur le header sous ie, ce n'est pas lié à cette PR

2020-01-23 10:05 UTC, lionelB approved these changes

2020-01-23 10:05 UTC, lionelB commented
GO GO GO !

2020-01-23 10:10 UTC, merged