Search results ui
SocialGouv/code-du-travail-numerique pull request #2312
Opened 2020-01-30 11:25 UTC by nkrmr

- Added Tag component
- Updated result page with Tag component

Fixed UI : 
- [ ] nouveau design actions secondaires (chercher convention, consulter thèmes)

2020-01-30 11:31 UTC, lionelB requested changes

2020-01-30 11:31 UTC, lionelB commented on packages/code-du-travail-frontend/pages/recherche.js
> +                      <Tag>Consulter les themes</Tag>
il faut rajouter un passHref et un as="a" sinon le markup ne sera pas bon

2020-01-30 11:37 UTC, nkrmr commented on packages/code-du-travail-frontend/pages/recherche.js
> +                      <Tag>Consulter les themes</Tag>
Oups!

2020-01-30 12:02 UTC, UnbearableBear commented on packages/code-du-travail-frontend/pages/themes/[slug].js
> +                    <Tag shadow>{title}</Tag>
Même remarque que Lionel ici pour le tag / link

2020-01-30 12:05 UTC, UnbearableBear commented on packages/code-du-travail-frontend/pages/recherche.js
> +                  <Heading shift="2.4rem" variant="primary" stripped>
Est-ce que tu peux utiliser la variable ici (xmedium) plutôt que de la mettre en dur ?

2020-01-30 12:07 UTC, UnbearableBear commented on packages/code-du-travail-frontend/pages/recherche.js
> +                    ...
le "Essayez ..." je le virerais mais si jamais on le garde (à voir avec Virginie) il faudrait mettre les … encodés pas une succession de trois points.

2020-01-30 12:11 UTC, UnbearableBear commented on packages/react-ui/src/Tag/index.js
> +  margin-bottom: ${spacings.base};
le margin bottom par défaut pourquoi pas mais le problème c'est que dans la page de recherche du coup ça rajoute des marges en trop en desktop (en mobile ça va)

2020-01-30 12:12 UTC, UnbearableBear approved these changes
Attention à quelques petits détails mais sinon nice !
Je sais pas pour toi mais je rajouterais bien un petit effet au hover, t'en penses quoi ?

2020-01-30 12:34 UTC, nkrmr commented on packages/code-du-travail-frontend/pages/themes/[slug].js
> +                    <Tag shadow>{title}</Tag>
Ok je m en occupe

2020-01-30 12:35 UTC, nkrmr commented on packages/code-du-travail-frontend/pages/recherche.js
> +                  <Heading shift="2.4rem" variant="primary" stripped>
Yes ok je m’ étais inspiré dès test dans reach-ui je vais changer.

2020-01-30 12:35 UTC, nkrmr commented on packages/code-du-travail-frontend/pages/recherche.js
> +                    ...
Ok je vais Check avec virginie voir ce qu’elle en pense.

2020-01-30 12:36 UTC, nkrmr commented on packages/react-ui/src/Tag/index.js
> +  margin-bottom: ${spacings.base};
Ok

2020-01-30 12:37 UTC, nkrmr commented
C est une bonne idée j ai conservé le fonctionnement de l ancien système mais effectivement ce serait mieux

2020-01-31 12:25 UTC, lionelB approved these changes

2020-01-31 12:32 UTC, merged