add test for common
SocialGouv/code-du-travail-numerique pull request #302
Opened 2018-11-21 15:35 UTC by lionelB

add test for commons

2018-11-21 16:56 UTC, douglasduteil requested changes

2018-11-21 16:56 UTC, douglasduteil commented on packages/code-du-travail-frontend/src/common/Disclaimer.js
>      Important ! Ce site est en cours de construction : les données qui s'y
can you use `&apos;` here ?

2018-11-22 08:09 UTC, lionelB commented
poke @douglasduteil

2018-11-22 11:10 UTC, revolunet commented
![](https://media.giphy.com/media/l0HlKDJgw54pm4hgY/giphy.gif)

2018-11-22 11:28 UTC, douglasduteil requested changes
- Why using "react-testing-library" other "react-test-renderer"
  \cc @revolunet 
- Some "request changes" might be better done in another PR

2018-11-22 11:28 UTC, douglasduteil commented on packages/code-du-travail-frontend/src/common/FeedbackForm.js
> +        fetch(formspreeUrl, {
We shouldn't make HTTP calls inside a component.
You might want to separate this logic from the component rendering.

2018-11-22 11:28 UTC, douglasduteil commented on packages/code-du-travail-frontend/src/common/FeedbackForm.js
> +            ) : null}
It looks like a "switch/case" to me no ?

2018-11-22 11:28 UTC, douglasduteil commented on packages/code-du-travail-frontend/src/common/FeedbackForm.js
> +        className="Feedback__form"
Why "uppercases" in css class names ?

2018-11-22 11:28 UTC, douglasduteil commented on packages/code-du-travail-frontend/src/common/ServiceRenseignement.js
> +    }
Might want to take a functional approach

```jsx
const department = this.state.departmentData ? DepartmentComponent(this.state.departmentData) : null

[...]

const DepartmentComponent = data => (
  <p>
    <a
      target="_blank"
      rel="noopener noreferrer"
      href={data.url}
      className="external-link__after"
    >
      <mark>{data.url}</mark>
    </a>
  </p>
);
```

Here the `DepartmentComponent` is a standalone component

2018-11-22 11:28 UTC, douglasduteil commented on packages/code-du-travail-frontend/src/common/__tests__/Html.test.js
> +    expect(container.firstChild.innerHTML).toBe("<b>Hello</b> World");
This is already tested by the snapshot above

2018-11-22 11:28 UTC, douglasduteil commented on packages/code-du-travail-frontend/src/common/__tests__/Html.test.js
> +    expect(container.firstChild.getAttribute("class")).toMatch(/toto/i);
This is testing all the above assertion if you snapshot the container

2018-11-22 11:28 UTC, douglasduteil commented on packages/code-du-travail-frontend/src/search/Answer.js
> -              {date && <DateContenu value={date} />}
Seems like removing the `DateContenu` is not related to the test branch

2018-11-22 12:27 UTC, lionelB commented on packages/code-du-travail-frontend/src/search/Answer.js
> -              {date && <DateContenu value={date} />}
It is. The goal was to have `/commons` tested. DateContenu is not usefull anymore since date was available in header, that's I remove it

2018-11-22 12:43 UTC, douglasduteil commented on packages/code-du-travail-frontend/src/search/Answer.js
> -              {date && <DateContenu value={date} />}
Alright

2018-11-22 16:07 UTC, douglasduteil requested changes

2018-11-22 16:07 UTC, douglasduteil commented on packages/code-du-travail-frontend/src/common/FeedbackForm.js
> +        if (data.success) {
Isn't it redundant ?
`then` callbacks should always be successful no ?

2018-11-22 16:07 UTC, douglasduteil commented on packages/code-du-travail-frontend/src/common/FeedbackForm.js
> +        } else if (data.error) {
should ne the content of the `catch(e => ...)`

2018-11-23 12:18 UTC, lionelB commented
@douglasduteil I wrap the inner API stuff (success / error) into feedback service, I can't find detailed ressource about formspree api response. I believe @revolunet do it like that on purpose.

what do you think ?

2018-11-23 13:07 UTC, douglasduteil approved these changes

2018-11-23 13:08 UTC, douglasduteil commented
That's way better no ?

2018-11-23 15:51 UTC, lionelB commented
yes !

2018-11-23 15:52 UTC, merged