feat(data): remove outdated link
SocialGouv/code-du-travail-numerique pull request #3052
Opened 2020-10-15 14:59 UTC by UnbearableBear

closes https://github.com/SocialGouv/code-du-travail-numerique/issues/3051

2020-10-15 15:00 UTC, virginielastisneres approved these changes

2020-10-15 16:42 UTC, virginielastisneres approved these changes

2020-10-16 08:58 UTC, lionelB requested changes

2020-10-16 08:58 UTC, lionelB commented on packages/code-du-travail-data/dataset/dossiers/index.js
> +              "https://www.economie.gouv.fr/plan-de-relance/profils/entreprises/fne-formationn",
```suggestion
              "https://www.economie.gouv.fr/plan-de-relance/profils/entreprises/fne-formation",
```

2020-10-16 09:03 UTC, lionelB approved these changes

2020-10-16 09:59 UTC, merged