Lionelb/fix modal ccn
SocialGouv/code-du-travail-numerique pull request #319
Opened 2018-11-26 16:40 UTC by lionelB

fix #208

2018-11-27 11:05 UTC, douglasduteil requested changes
What a Pyramid of DOOM BTW

- We shouldn't mix data layer and front request in the same files...
- We shouldn't try catch the whole functions... as Express, [Koa has an global error handler](https://github.com/koajs/koa/wiki/Error-Handling)
- `packages/code-du-travail-frontend/src/common/ConventionForm.js` looks like a good example of a Smart component in need of using lower abstractions

2018-11-27 11:05 UTC, douglasduteil commented on packages/code-du-travail-data/dataset/kali/utils.js
> +    results = results.concat(...values);
same as `results = [...results, ...values]`

2018-11-27 11:05 UTC, douglasduteil commented on packages/code-du-travail-data/dataset/kali/utils.js
> +    let values = await Promise.all(items.map(callback));
here `values` is a const right ?

2018-11-27 11:05 UTC, douglasduteil commented on packages/code-du-travail-data/dataset/kali/yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
this packages is not part of the monorepo ??

2018-11-27 11:05 UTC, douglasduteil commented on packages/code-du-travail-frontend/src/common/ConventionForm.js
> +          <div style={{ marginTop: 10 }}>
prefer use of styled-components or atomic classes

2018-11-27 11:05 UTC, douglasduteil commented on packages/code-du-travail-frontend/src/common/ConventionForm.js
> +              <div>
why you need a div here ?

2018-11-27 11:05 UTC, douglasduteil commented on packages/code-du-travail-frontend/src/common/ConventionForm.js
> +            <div style={{ marginTop: 20, fontWeight: "bold" }}>
prefer use of styled-components or atomic classes

2018-11-27 11:05 UTC, douglasduteil commented on packages/code-du-travail-frontend/src/common/ConventionForm.js
> +                  style={{ marginLeft: 5, cursor: "pointer" }}
prefer use of styled-components or atomic classes

2018-11-27 11:05 UTC, douglasduteil commented on packages/code-du-travail-frontend/src/common/ConventionForm.js
> +            <div style={{ marginTop: 20, fontWeight: "bold" }}>
prefer use of styled-components or atomic classes

2018-11-27 11:05 UTC, douglasduteil commented on packages/code-du-travail-frontend/src/common/ConventionForm.js
> +export { ConventionForm };
Might want to put this line 8 as :

```diff
-class ConventionForm extends React.Component {
+export class ConventionForm extends React.Component {
````

2018-11-27 11:05 UTC, douglasduteil commented on packages/code-du-travail-frontend/src/common/ConventionForm.js
> +      style={{ marginRight: 5 }}
prefer use of styled-components or atomic classes

2018-11-27 11:05 UTC, douglasduteil commented on packages/code-du-travail-frontend/src/common/ConventionForm.js
> +      <Button link style={{ whiteSpace: "normal", fontSize: ".9rem" }}>
prefer use of styled-components or atomic classes

2018-11-27 13:31 UTC, lionelB commented on packages/code-du-travail-frontend/src/common/ConventionForm.js
> +              <div>
because there is 2 child so i need a wrapper ? what do you suggest ?

2018-11-27 13:32 UTC, lionelB commented on packages/code-du-travail-frontend/src/common/ConventionForm.js
> +export { ConventionForm };
Is there a difference ?

2018-11-27 14:00 UTC, douglasduteil commented on packages/code-du-travail-frontend/src/common/ConventionForm.js
> +              <div>
Does a React fragment works in that case ?

2018-11-27 14:04 UTC, douglasduteil commented on packages/code-du-travail-frontend/src/common/ConventionForm.js
> +export { ConventionForm };
The end result is the same.
IMO the code is more expectable as you can read what is exported next to the export statement but it's a taste.

2018-11-27 15:59 UTC, lionelB commented on packages/code-du-travail-frontend/src/common/ConventionForm.js
> +              <div>
yep

2018-11-27 17:10 UTC, lionelB commented
![chad-dance](https://user-images.githubusercontent.com/160320/49098643-a8146280-f26f-11e8-80c2-c05ea04158df.gif)

2018-11-27 17:21 UTC, douglasduteil requested changes

2018-11-27 17:21 UTC, douglasduteil commented on packages/code-du-travail-api/src/server/routes/api.js
> +    ctx.throw(error);
Do we still need to "try catch" ?
a "natural" throw would work right ?

2018-11-27 17:28 UTC, lionelB commented on packages/code-du-travail-api/src/server/routes/api.js
> +    ctx.throw(error);
you mean because `codeDuTravailNumerique.search()` already throw ans error ?

2018-11-28 10:00 UTC, douglasduteil approved these changes

2018-11-28 10:01 UTC, merged

2018-11-28 11:05 UTC, revolunet commented on packages/code-du-travail-api/src/server/data_sources/code_du_travail_numerique.js
> +          ...fieldHightlight
typo

2018-11-28 11:05 UTC, revolunet commented on packages/code-du-travail-api/src/server/data_sources/code_du_travail_numerique.js
> +  fieldHightlight = [],
typo

2018-11-28 11:05 UTC, revolunet commented on packages/code-du-travail-data/dataset/kali/utils.js
> +};
C'est mignon et mérite quelques TU :)

2018-11-28 11:38 UTC, lionelB commented on packages/code-du-travail-data/dataset/kali/utils.js
> +};
mignon !??!!?  mais oui on pourrait ajouter quelques tests sur ces fonctions