feat(frontend): add a11y navigation skip link
SocialGouv/code-du-travail-numerique pull request #3426
Opened 2021-04-08 12:56 UTC by lionelB

2021-04-09 09:01 UTC, m-maillot requested changes
The navigation skip link doesn't work on the whole site.
For instance, if I open this page: https://9805866-code-travail.dev2.fabrique.social.gouv.fr/outils/preavis-demission
I don't have access to the navigation skip.

It's the same if I navigate in the site. But I don't know if it's required in the case 🤷

2021-04-09 09:01 UTC, m-maillot commented on packages/code-du-travail-frontend/pages/index.js
> +    <div id="content">
From the rule 12.6:

> La zone possède un rôle WAI-ARIA de type landmark correspondant à sa nature ;

From the landmark page:

> La zone de contenu principal doit avoir un attribut WAI-ARIA role="main" ;

I think we should set `main` in place of `content` here.

2021-04-09 09:01 UTC, m-maillot commented on packages/code-du-travail-frontend/pages/index.js
> +    </div>
Why the tools are not in the section?

2021-04-09 09:01 UTC, m-maillot commented on packages/code-du-travail-frontend/src/layout/Header/SkipNavLink.js
> +  background-color: ${({ theme }) => theme.paragraph};
I think we should use another color :/

<img width="612" alt="CleanShot 2021-04-09 at 10 38 53@2x" src="https://user-images.githubusercontent.com/992514/114154934-39587100-9921-11eb-90aa-62a116f9a081.png">

The contrast is poor with this link color.

2021-04-09 09:01 UTC, m-maillot commented on packages/code-du-travail-frontend/src/layout/Layout.js
> +          <StyledMain id="content">{children}</StyledMain>
Same here, it should be `main` in place of `content`.

2021-04-09 15:07 UTC, lionelB commented on packages/code-du-travail-frontend/src/layout/Header/SkipNavLink.js
> +  background-color: ${({ theme }) => theme.paragraph};
replace with white

2021-04-13 15:26 UTC, m-maillot approved these changes

2021-04-13 16:24 UTC, merged