feat(frontend): rgaa 9.2
SocialGouv/code-du-travail-numerique pull request #3722
Opened 2021-09-01 14:18 UTC by maxgfr

J'ai corrigé l'issue #3720

Concernant le dernier point sur l'accessibilité, j'ai modifié la nav en div. ça répond à la problèmatique, mais je ne suis pas sûr si cela était attendu. L'autre possibilité est de refaire le design afin d'enlever l'accessibilité de la navigation et de la popup

2021-09-06 08:19 UTC, m-maillot reviewed
Aucune remarque sur le correctif, juste sur le script et le fichier de log ajouté :)

2021-09-06 08:19 UTC, m-maillot commented on lerna-debug.log
> +0 silly argv {
Ce fichier ne devrait pas être commité. Peut être l'ajouter dans le `.gitignore` ?

2021-09-06 08:19 UTC, m-maillot commented on package.json
> +    "dev:frontend": "API_URL=https://api-master-dev-code-du-travail-numerique.dev.fabrique.social.gouv.fr/api/v1 yarn workspace @cdt/frontend dev",
Je propose de garder `dev:frontend` comme il existe (en mode dev) et de créer un `dev:frontend:preprod-api` pour indiquer que l'on s'appuie sur la preprod.

Changer l'url par : https://api-preprod-code-du-travail-numerique.dev.fabrique.social.gouv.fr/api/v1

2021-09-08 15:47 UTC, lionelB commented on package.json
> +    "dev:frontend:preprod-api": "API_URL=https://api-master-dev-code-du-travail-numerique.dev.fabrique.social.gouv.fr/api/v1 yarn workspace @cdt/frontend dev",
```suggestion
    "dev:frontend:preprod-api": "API_URL=https://api-preprod-code-du-travail-numerique.dev.fabrique.social.gouv.fr/api/v1 yarn workspace @cdt/frontend dev",
```

2021-09-08 15:50 UTC, lionelB commented on packages/code-du-travail-frontend/src/layout/Header/SkipNavLink.js
>      <SkipNav>
Skipnav est une balise ul il faudrait remonter la balise nav au dessus pour que le li soit dans le ul

2021-09-08 15:52 UTC, lionelB commented on packages/react-ui/src/BurgerNav/index.js
> +const Div = styled.div`
Etant donnée que les liens sont de la navigation, je pense qu'il faut laisser la balise nav

2021-09-08 15:52 UTC, lionelB requested changes
cool :) juste 2-3 modif

2021-09-08 15:53 UTC, lionelB commented on packages/code-du-travail-frontend/src/layout/Header/SkipNavLink.js
>      <SkipNav>
on peut aussi rajouter un aria-label="liens d'évitements" / role=nav comme sur service public

2021-09-10 12:57 UTC, lionelB approved these changes

2021-09-10 13:17 UTC, lionelB commented on packages/code-du-travail-frontend/src/layout/Header/SkipNavLink.js
> +            <SkipLink type="inline" as="a" href="#navigation">
on peut virer le type="inline" d'apres le validateur w3c

2021-09-10 15:12 UTC, merged