feat(frontend): add rgaa 9.3
SocialGouv/code-du-travail-numerique pull request #3725
Opened 2021-09-02 08:24 UTC by maxgfr

Le critère 9.3 a été corrigé 

fix #3723

2021-09-06 09:30 UTC, m-maillot commented on package.json
> +    "test:codecept": "cd optional/e2e/runners/puppeteer && yarn test",
Cette commande est disruptive, ça nous fait changer de dossier. Du coup on a plus accès aux anciennes commandes. Peut être faire un cd ../../../.. à la fin ? Ou voir si on peut lancer une commande yarn dans un sous dossier ?

2021-09-06 09:30 UTC, m-maillot commented on package.json
> +    "test:frontend": "yarn build:ui && yarn workspace @cdt/frontend test --watch",
Top ! :+1:

2021-09-08 15:56 UTC, lionelB commented on packages/code-du-travail-frontend/src/common/Breadcrumbs.js
> +    <Nav aria-label="Breadcrumb">
aria-labe
```suggestion
    <Nav aria-label="Fil d'ariane">
```

2021-09-08 15:58 UTC, lionelB commented on packages/code-du-travail-frontend/src/outils/common/StepList.js
> +      <FlatList as="ol">
je pense qu'il vaut mieux conserver le comportement actuel avec un li qui est plus fréquent

2021-09-08 15:59 UTC, lionelB commented on packages/react-ui/src/BurgerNav/index.js
> +            title="fermer la modal"
```suggestion
            title="fermer la fenêtre modale"
```

2021-09-08 15:59 UTC, lionelB commented on packages/react-ui/src/BurgerNav/index.js
> +            <ScreenReaderOnly>fermer la modal</ScreenReaderOnly>
```suggestion
            <ScreenReaderOnly>fermer la fenêtre modale</ScreenReaderOnly>
```

2021-09-08 16:00 UTC, lionelB commented on packages/react-ui/src/Grid/GridCell.js
> +export const ListItem = styled.div`
on peut conserver le comportement par default, une liste ca devrait etre  un `li`

2021-09-08 16:01 UTC, lionelB commented on packages/react-ui/src/Grid/Grid.js
> +export const List = styled.div`
on peut conserver le comportement par default, une liste ca devrait etre un ul

2021-09-08 16:13 UTC, lionelB requested changes
quelques modif mais sinon c'est cool
Par contre je suis pas sur des changement des balises par defaut pour les list / listitem

2021-09-09 08:57 UTC, maxgfr commented on packages/react-ui/src/Grid/Grid.js
> +export const List = styled.div`
Je sais bien, j'ai fait ça dans le but de coller au mieux au critère RGAA. En soit, cette List s'applique notamment aux blocks qu'on a sur la home page. Il est recommandé selon l'audit d'utiliser des divs. Je suis d'accord avec toi que leur retour se discute

2021-09-09 08:58 UTC, maxgfr commented on packages/react-ui/src/Grid/Grid.js
> +export const List = styled.div`
Il y'a d'ailleurs d'autres éléments de type Block qui sont sous forme de list. J'ai pas bien compris la subtilité au niveau de l'audit aussi

2021-09-09 09:00 UTC, lionelB commented on packages/react-ui/src/Grid/Grid.js
> +export const List = styled.div`
oui j'ai envoyé un mail en ce sens, je pense que le comportement par defaut attendu d'un compo list doit se baser sur un li. si jamais on doit le changer alors on utilise le `as="div"` ou `as="ol"` selon les cas

2021-09-09 13:02 UTC, lionelB approved these changes

2021-09-10 12:47 UTC, m-maillot approved these changes

2021-09-10 14:06 UTC, merged