feat(frontend): add canonical link to contributions
SocialGouv/code-du-travail-numerique pull request #3735
Opened 2021-09-08 16:59 UTC by maxgfr

J'ai suivi les indications de l'issue pour ajouter les canonicals sur contributions

fix #3487

2021-09-09 08:11 UTC, lionelB requested changes
on a plusieurs pages contributions pour un meme contenu
- 1 générique avec une url type https://preprod-code-du-travail-numerique.dev.fabrique.social.gouv.fr/contribution/les-conges-pour-evenements-familiaux
-  X déclinaisons par Convention collective) https://preprod-code-du-travail-numerique.dev.fabrique.social.gouv.fr/contribution/44-les-conges-pour-evenements-familiaux

je pense qu'il faudrait faire pointer la canonical des déclinaison vers la page générique 
\cc @Jonathan2051

2021-09-09 08:11 UTC, lionelB commented on packages/code-du-travail-frontend/pages/contribution/[slug].js
> +  componentDidMount() {
componentDidMount implique que la balise canonical sera fausse en SSR, pour cela il vaut mieux utiliser la variable d'env `FRONTEND_URL`

2021-09-09 08:38 UTC, maxgfr commented on packages/code-du-travail-frontend/pages/contribution/[slug].js
> +  componentDidMount() {
D'accord, effectivement !

2021-09-09 08:52 UTC, maxgfr commented on packages/code-du-travail-frontend/pages/contribution/[slug].js
> +  componentDidMount() {
FRONTEND_URL, n'est accessible que côté SSR, il faudrait rajouter le prefix `NEXT_PUBLIC_` pour pouvoir l'utiliser front. L'autre possibilité serait de la passer via les server side props. Qu'en penses-tu ?

2021-09-09 08:57 UTC, lionelB commented on packages/code-du-travail-frontend/pages/contribution/[slug].js
> +  componentDidMount() {
```
const {
  publicRuntimeConfig: { FRONTEND_HOST },
} = getConfig();
```

2021-09-09 09:15 UTC, maxgfr commented on packages/code-du-travail-frontend/pages/contribution/[slug].js
> +  componentDidMount() {
Merci 🔥

2021-09-10 16:10 UTC, lionelB commented
pour tester view-source:https://maxgfr-canonical-ep5mu7-code-du-travail-numerique.dev.fabrique.social.gouv.fr/contribution/44-les-conges-pour-evenements-familiaux

2021-09-13 09:56 UTC, m-maillot requested changes
Je ne suis pas fan de l'utilisation de regex à ce niveau. 
J'ai trouvé dans les props de la page les informations requises pour obtenir le lien canonique.

Désolé pour les tests mais c'était une très bonne initiative ! :) Tu peux en mettre pour la logique de récupération du lien canonique :)

2021-09-13 09:56 UTC, m-maillot commented on packages/code-du-travail-frontend/pages/contribution/[slug].js
> +            href={getCanonicalUrl(
Je propsoe que l'on s'appuie sur les données fournies par le serveur pour récupérer l'information. Ces informations sont disponibles dans le `props` de la page.

<img width="1530" alt="image" src="https://user-images.githubusercontent.com/992514/133063609-dc6da2d8-4e56-4d79-9c74-7cfa1d52957d.png">

2021-09-13 10:06 UTC, maxgfr commented on packages/code-du-travail-frontend/pages/contribution/[slug].js
> +            href={getCanonicalUrl(
Bien vu ! 🔥

2021-09-13 11:15 UTC, maxgfr commented on packages/code-du-travail-frontend/pages/contribution/[slug].js
> +            href={getCanonicalUrl(
Avec du recul, les deux questions que je me pose :
- Est-ce que dans le related item, nous aurons toujours le slug ?
- Est-ce que le slug reflète toujours l'url canonique ?

2021-09-13 11:26 UTC, m-maillot commented on packages/code-du-travail-frontend/pages/contribution/[slug].js
> +            href={getCanonicalUrl(
En fait j'ai dit n'importe quoi. Les `relatedItems` sont générés par un algo qui détecte les pages en relations avec le contenu. Du coup, si l'algo change, on peut perdre la page d'origine. 
Par contre, je pense que l'on doit savoir si la page est personnalisée ou non et obtenir la page source. En tout cas, on l'a dans la base elastic. Je vais essayer de voir où ça peut être sinon voir avec @lionelB.

2021-09-17 07:17 UTC, lionelB commented on packages/code-du-travail-frontend/pages/contribution/[slug].js
> +            href={getCanonicalUrl(
si on veut rajouter l'url d'origine, il faut faire ca coté ingester dans cdtn-admin https://github.com/SocialGouv/cdtn-admin/blob/master/targets/ingester/src/transform/contributions.ts#L35-L52

2021-09-17 09:05 UTC, m-maillot requested changes

2021-09-17 09:05 UTC, m-maillot commented on packages/code-du-travail-frontend/src/utils/url.ts
> +  return url.replace(/\d+-/g, "");
Dans le cas où l'on a un chiffre dans le titre de la contribution, ça va la modifier à tort, exemple : 
https://code.travail.gouv.fr/contribution/les-conges-10-pour-evenements-familiaux -> https://code.travail.gouv.fr/contribution/les-conges-pour-evenements-familiaux

Je propose de modifier le regex pour le prendre en compte qu'au début : `/\/\d+-/g`

2021-09-17 09:05 UTC, m-maillot commented on packages/code-du-travail-frontend/pages/contribution/[slug].js
> +            href={getCanonicalUrl(
J'ai crée l'issue sur l'admin pour le mettre en place plus tard. https://github.com/SocialGouv/cdtn-admin/issues/613

2021-09-17 09:08 UTC, maxgfr commented on packages/code-du-travail-frontend/src/utils/url.ts
> +  return url.replace(/\d+-/g, "");
Et oui, j'aurai dû y penser dans mes tests 😅

2021-09-17 10:14 UTC, maxgfr commented on packages/code-du-travail-frontend/src/utils/url.ts
> +  return url.replace(/\d+-/g, "");
Test rajouté, au final pas besoin d'update la regex

2021-09-17 10:19 UTC, m-maillot commented on packages/code-du-travail-frontend/src/utils/url.ts
> +  return url.replace(/\d+-/g, "");
Je me suis mal exprimé 😄 

Le test est faux ici : 
```js
const parsedUrlWithOriginNumber = getCanonicalUrl(
    "https://code.travail.gouv.fr/contribution/les-conges-10-pour-evenements-familiaux"
  );
  expect(parsedUrlWithOriginNumber).toBe(
    "https://code.travail.gouv.fr/contribution/les-conges-pour-evenements-familiaux"
  );
```
Car quand on a l'url https://code.travail.gouv.fr/contribution/les-conges-10-pour-evenements-familiaux, on ne devrait rien changer. Il n'y a que les URLs où le slug commence par un chiffre de CC comme https://code.travail.gouv.fr/contribution/1093-les-conges-10-pour-evenements-familiaux qui doit devenir : https://code.travail.gouv.fr/contribution/les-conges-10-pour-evenements-familiaux

:)

2021-09-17 11:31 UTC, maxgfr commented on packages/code-du-travail-frontend/src/utils/url.ts
> +  return url.replace(/\d+-/g, "");
Oh je vois ! 

Got it ;)

2021-09-17 12:26 UTC, m-maillot approved these changes
Nickel :+1:

2021-09-17 12:36 UTC, lionelB commented
https://github.com/SocialGouv/cdtn-admin/pull/614

2021-09-17 12:39 UTC, lionelB approved these changes

2021-09-17 12:59 UTC, merged