feat(modeles): add 3043
SocialGouv/code-du-travail-numerique pull request #3748
Opened 2021-09-15 13:04 UTC by maxgfr

La PR est en draft, je dois corriger mon TODO avant de la passer en Review.

J'ai noté un problème de conversion sur publicode, avec la correspondance, mois semaine

2021-09-16 13:34 UTC, maxgfr commented
La problématique que je rencontre est lié à cette [issue](https://github.com/betagouv/publicodes/issues/80) de la lib publicodes

2021-09-17 09:46 UTC, maxgfr commented
Le [bug](https://github.com/betagouv/publicodes/issues/80#issuecomment-921660968) a été corrigé !

2021-09-17 11:54 UTC, m-maillot requested changes
Top :+1: 
J'ai trouvé quelques cas de tests manquant pour couvrir toute la CC.
Il y a un nommage dans les catégorie qui est à changer, il faut rester au plus près du Excel pour bien avoir le terme juridique. L'astuce également est de regarder comment c'est géré sur le simulateur de préavis de licenciement, on pourra en parler lundi en review de l'autre PR.

Pour les références, je vois ce que tu veux dire. Il faut garder en tête que c'est du code qui va très peu changer mais on pourrait en effet le simplifier facilement en ayant des variables dans le cas présent où l'on indique que le nom de l'article et le mapping article <-> lien est réalisé ailleurs mais comme ils ont souvent le même nom, c'est pas aussi simple. Je n'ai pas de solution miracle actuellement mais je reste dispo pour des propositions 👍 :)

2021-09-17 11:54 UTC, m-maillot commented on packages/code-du-travail-modeles/src/__test__/depart.mise.retraite.proprete.spec.ts
> +  ${1}      | ${"Techniciens & Agents de maîtrise"} | ${0}           | ${"mois"}
pourquoi utiliser le `&` à la place du `et` ici ? Par défaut les caractères spéciaux on préfère les éviter dans le dev :D

2021-09-17 11:54 UTC, m-maillot commented on packages/code-du-travail-modeles/src/__test__/depart.mise.retraite.proprete.spec.ts
> +  ${24}     | ${"Agents de propreté"}               | ${7}           | ${"jour"}
Si on utilise 1 semaine au lieu de 7 jours, ça plante encore ? Sinon on pourrait mettre 1 semaine ici.

2021-09-17 11:54 UTC, m-maillot commented on packages/code-du-travail-modeles/src/__test__/depart.mise.retraite.proprete.spec.ts
> +  ${6}      | ${"Employés"}                         | ${1}           | ${"mois"}
Il manque le usecase pour plus de 2 ans pour valider que l'on ne prend pas les 2 mois du CDT
```
${24} | ${"Employés"} | ${1} | ${"mois"}
```

2021-09-17 11:54 UTC, m-maillot commented on packages/code-du-travail-modeles/src/__test__/depart.mise.retraite.proprete.spec.ts
> +  ${12}     | ${"Techniciens & Agents de maîtrise"} | ${1}           | ${"mois"}
Il manque le cas spécifique quand il a plus de 2 mois et moins de 6 mois, dans la CC on a 1 mois et le CDT pas de préavis. Après quand on a plus de 6 mois, le cas est bien testé.
```
  ${2}      | ${"Techniciens & Agents de maîtrise"} | ${1}           | ${"mois"}
```

2021-09-17 11:54 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/contrat-salarie.yaml
> +        variations:
Top :+1: On a aussi le cas ligne 39 où l'on prend le maximum. On peut également le changer pour éviter le bug pour de futurs devs.

2021-09-17 11:54 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/proprete_entreprises.yaml
> +contrat salarié . convention collective . propreté entreprise:
Au vu du nom de la CC, le nom `entreprises de propreté` ne semble-t-il pas plus juste ?

2021-09-17 11:54 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/proprete_entreprises.yaml
> +      Techniciens & Agents de maîtrise: "'Techniciens & Agents de maîtrise'"
Ici on a une perte d'information et l'utilisation du & qui n'est pas utilisé sur le site. Il faudrait le renommer `Techniciens et Agents de maîtrise (TAM)` comme dans le Excel et dans le simu préavis de licenciement.

2021-09-22 11:34 UTC, maxgfr commented on packages/code-du-travail-modeles/src/modeles/contrat-salarie.yaml
> +        variations:
En modifiant, les tests n'ont pas passé sur d'autres conventions collectives... A creuser

2021-09-22 11:35 UTC, maxgfr commented on packages/code-du-travail-modeles/src/__test__/depart.mise.retraite.proprete.spec.ts
> +  ${24}     | ${"Agents de propreté"}               | ${7}           | ${"jour"}
Oui, j'ai testé les deux, et ça plante...
Il n'y a que jour sans s qui semble fonctionner

2021-09-22 11:38 UTC, maxgfr commented on packages/code-du-travail-modeles/src/modeles/contrat-salarie.yaml
> +        variations:
J'ai fait ça :

```yml
        variations:
          - si: contrat salarié . préavis de retraite légale > contrat salarié . préavis de retraite collective
            alors: contrat salarié . préavis de retraite légale
          - sinon: contrat salarié . préavis de retraite collective
```
au lieu de 
```yml
sinon:
        le maximum de:
          - contrat salarié . préavis de retraite légale
          - contrat salarié . préavis de retraite collective
```

2021-09-22 13:30 UTC, carolineBda commented on packages/code-du-travail-modeles/src/__test__/depart.mise.retraite.proprete.spec.ts
> +  ${6}      | ${"Agents de propreté"}                      | ${7}           | ${"jour"}
on met pas de "s" à jour ?

2021-09-22 13:37 UTC, maxgfr commented on packages/code-du-travail-modeles/src/__test__/depart.mise.retraite.proprete.spec.ts
> +  ${6}      | ${"Agents de propreté"}                      | ${7}           | ${"jour"}
J'ai essayé de mettre un s à `jour`, mais les tests ne passaient plus 🤔

2021-09-24 06:43 UTC, m-maillot commented on packages/code-du-travail-modeles/src/__test__/depart.mise.retraite.proprete.spec.ts
> +  ${24}     | ${"Agents de propreté"}               | ${7}           | ${"jour"}
En fait publicode ne connais pas l'unité semaine. Il connait jour et mois seulement donc c'est normal :)

2021-09-24 06:44 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/proprete_entreprises.yaml
> +contrat salarié . convention collective . propreté entreprise:
On pourrait en profiter pour renommer les fichiers aussi ? 😇

2021-09-24 06:52 UTC, m-maillot reviewed
Il faut qu'on voit pour prendre en compte les retours de Noémie avant de rebase:

```
Propreté (IDCC 3043): 

Quand la durée est affichée en jours, il manque un S à “jour” (2 jours, 7 jours, ...). De plus, par souci de cohérence avec les autres CC, pour le départ à la retraite, je pense qu’il faut indiquer 1 semaine quand l’ancienneté est de 7 jours (Pour la mise en retraite, c’est déjà le cas)
Quand le salarié est reconnu en qualité de travailleur handicapé et est cadre, il n’y a pas de phrase affichée dans le résultat décrypté. Il faudrait afficher la phrase suivante : “Le résultat correspond à la fois à la durée prévue par le code du travail et à la fois à la durée prévue par la convention collective, celles-ci étant identiques dans cette situation.” (-> Erreur affichée puis disparue en essayant de nouveau mais je le signale quand même)
```
https://mattermost.fabrique.social.gouv.fr/default/pl/xg6otjyky7d98daky15tnnz9ow

2021-09-27 14:29 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/publicodes/__tests__/convertDaysIntoBetterUnit.test.ts
> +    ${182.5}   | ${PublicodesUnit.MONTH} | ${6}
ça fait quoi si on passe un chiffre pas du tout divible par 30, genre 45 ?

2021-09-27 14:29 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/publicodes/Utils.ts
> +    (Number(parsedDay) === parsedDay && parsedDay % 1 !== 0) ||
c'est un peu dur à lire cette méthode 😅

2021-09-28 10:34 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/publicodes/__tests__/convertDaysIntoBetterUnit.test.ts
> +    ${182.5}   | ${PublicodesUnit.MONTH} | ${6}
Très bonne question, en soit ça donnerait 30 jours, 45 jours. Le but c'est de se dire que la conversion s'appliquant au mois sera toujours flottant. Et que pour les semaines, toujours au modulo 7. 35 jours donnerait donc 5 semaines

2021-09-28 10:34 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/publicodes/Utils.ts
> +    (Number(parsedDay) === parsedDay && parsedDay % 1 !== 0) ||
Ouaip, peut-être wrappé la formule dans une fonction à part entière. Tu en penses quoi @m-maillot ?

2021-09-29 11:52 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/publicodes/__tests__/convertDaysIntoBetterUnit.test.ts
> +    ${182.5}   | ${PublicodesUnit.MONTH} | ${6}
du coup il faudrait rajouter ces cas de tests pour être sur

2021-09-30 08:05 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/common/YesNoQuestion.tsx
> +        {({ input }) => <InputRadio id={`${name}-no`} label="Non" {...input} />}
du coup ça fixe le pb ?

2021-09-30 10:21 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/common/YesNoQuestion.tsx
> +        {({ input }) => <InputRadio id={`${name}-no`} label="Non" {...input} />}
Je ne crois pas car ça ne fonctionnait pas durant la session de pair programming

2021-09-30 14:04 UTC, carolineBda approved these changes

2021-09-30 14:04 UTC, m-maillot approved these changes

2021-09-30 14:04 UTC, merged