feat(simulators): implement the agreement boulangerie patisserie
SocialGouv/code-du-travail-numerique pull request #3751
Opened 2021-09-17 09:47 UTC by m-maillot

linked to #3531

2021-09-22 09:23 UTC, carolineBda commented on packages/code-du-travail-modeles/src/modeles/conventions/automobiles.yaml
> +      Ouvriers, Employés: Ouvriers
format "'Ouvriers'"

2021-09-22 09:23 UTC, carolineBda commented on packages/code-du-travail-modeles/src/modeles/conventions/automobiles.yaml
> +contrat salarié . convention collective . automobiles . échelon ouvrier:
sous namespace "ouvrier"

2021-09-29 10:48 UTC, maxgfr requested changes
Quelques changements, et c'est parfait ;)

2021-09-29 10:48 UTC, maxgfr commented on packages/code-du-travail-modeles/src/__test__/depart.retraite.automobile.spec.ts
> +  ${24}     | ${3}  | ${1}           | ${"mois"}
Il faudrait tester 12 mois en plus

2021-09-29 10:48 UTC, maxgfr commented on packages/code-du-travail-modeles/src/__test__/depart.retraite.automobile.spec.ts
> +  ${5}      | ${1}  | ${2}           | ${"semaines"}
De plus, le terme semaines, ne marche pas avec publicodes, il faut utiliser `jour`

2021-09-29 10:48 UTC, maxgfr commented on packages/code-du-travail-modeles/src/__test__/depart.mise.retraite.boulangerie.patisserie.entreprise.artisanales.spec.ts
> +  ${3}      | ${1}           | ${"semaine"}
Utiliser le terme `jour`

2021-09-29 10:48 UTC, maxgfr commented on packages/code-du-travail-modeles/src/__test__/depart.mise.retraite.boulangerie.patisserie.entreprise.artisanales.spec.ts
> +  ${2}      | ${1}           | ${"semaine"}
Same ici `jour`

2021-09-29 10:48 UTC, maxgfr commented on packages/code-du-travail-modeles/src/__test__/mise.retraite.automobile.spec.ts
> +  ${5}      | ${1}  | ${2}           | ${"semaines"}
`jour`

2021-09-29 10:48 UTC, maxgfr commented on packages/code-du-travail-modeles/src/__test__/mise.retraite.automobile.spec.ts
> +  ${24}     | ${20} | ${3}
Il faudrait mieux faire une matrice, en prenant compte des 3 anciennetés possible

2021-09-29 10:48 UTC, maxgfr commented on packages/code-du-travail-modeles/src/modeles/conventions/automobiles.yaml
> +contrat salarié . convention collective . automobiles . préavis de mise à la retraite . ouvriers échelon 3 à 12:
j'aime bien les namespace comme ça perso 😁

2021-09-29 10:48 UTC, maxgfr commented on packages/code-du-travail-modeles/src/modeles/conventions/automobiles.yaml
> +        plafond: 20
Mettre une unité ici

2021-09-29 10:48 UTC, maxgfr commented on packages/code-du-travail-modeles/src/modeles/conventions/automobiles.yaml
> +        plafond: 3
Il faudrait aussi mettre une unité là 🤓

2021-09-29 10:48 UTC, maxgfr commented on packages/code-du-travail-modeles/src/modeles/conventions/automobiles.yaml
> +        plafond: 20
et là 😁

2021-09-29 10:48 UTC, maxgfr commented on packages/code-du-travail-modeles/src/__test__/mise.retraite.automobile.spec.ts
> +});
Moi j'aurai fait quand même un each ancienneté pour être sûr, après ça se discute

2021-09-29 11:23 UTC, maxgfr requested changes
👀

2021-09-29 11:50 UTC, carolineBda commented on packages/code-du-travail-modeles/src/modeles/conventions/automobiles.yaml
> +        plafond: 20
sur le plafond ?

2021-09-29 12:10 UTC, maxgfr commented on packages/code-du-travail-modeles/src/modeles/conventions/automobiles.yaml
> +        plafond: 20
Ah oui, bien vu

2021-09-29 12:50 UTC, maxgfr approved these changes
C'est niquel pour moi

2021-09-29 12:50 UTC, maxgfr commented on packages/code-du-travail-modeles/src/modeles/conventions/boulangerie_patisserie.yaml
> +      - montant: départ à la retraite . une semaine
C'est vrai que comme ça, on optimise bien

2021-10-04 15:06 UTC, carolineBda commented
Noemie a validé les 2 CC 1090 & 843. Je merge

2021-10-04 19:35 UTC, merged