feat(simulator): add CC 2609
SocialGouv/code-du-travail-numerique pull request #3763
Opened 2021-09-21 15:30 UTC by carolineBda

2021-09-22 08:33 UTC, maxgfr approved these changes
🔥

2021-09-28 08:36 UTC, m-maillot requested changes
Il y a un point à discuter ensemble dans le lot :)

2021-09-28 08:36 UTC, m-maillot commented on packages/code-du-travail-modeles/src/__test__/depart.mise.retraite.batiment.etam.spec.ts
> +  "Pour une mise à la retraite avec un contrat conclu après le 1er juillet 2019 et un group $group, on attend une notification",
Le titre du test me laisse perplexe quand à ce qui est testé. Après vérification dans le fichier Excel, le titre du test me semble faux :)

2021-09-28 08:36 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/batiment.yaml
> +contrat salarié . convention collective . batiment:
On a beaucoup de CC avec le terme bâtiment à l'intérieur:
<img width="282" alt="image" src="https://user-images.githubusercontent.com/992514/135052096-bec97cfe-e5b7-4af7-97ef-35ae9a15b0e7.png">

Je pense qu'il est judicieux d'ajouter le terme ETAM dans le namespace ici.

2021-09-28 08:36 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/batiment.yaml
> +  applicable si: départ à la retraite
On a deux choix ici, soit on place les notifications dans leur namespace et du coup pas besoin du `applicable si` dans le cas présent. Soit on place les notifications à la racine du namespace et on utilise les `applicable si` pour limiter leur périmètre.
J'avais choisi la seconde car je trouvais la gestion via namespace trop lourde pour des notifications, l'applicable si est plus simple à mettre en place. 
Je pense qu'il peut être bien d'en discuter rapidement @carolineBda @maxgfr

2021-09-29 10:38 UTC, maxgfr approved these changes

2021-09-30 16:06 UTC, maxgfr requested changes
Attends, y'a pas un problème avec PR ?  Je vois pleins de fichiers modifiés 😨

2021-10-01 11:36 UTC, carolineBda commented
t'as raison je sais pas ce que j'avais fait. Je viens de re merge master. merci !

2021-10-01 12:13 UTC, maxgfr approved these changes

2021-10-04 15:10 UTC, m-maillot approved these changes

2021-10-04 15:26 UTC, carolineBda commented
Approuvé par Noémie. Je merge

2021-10-04 15:26 UTC, merged