fix(frontend): add cannonical tag to all pages
SocialGouv/code-du-travail-numerique pull request #3764
Opened 2021-09-21 17:16 UTC by lionelB

un fix pour appliquer les canonical sur toutes les pages (vu que j'avais tout compris de travers) 
Comme les moteurs indexent des url, renseigner la balise `canoncial` permet d'éviter les doublons entre `cdtn.url?id` et `cdtn.url` 

J'en ai profité pour cleaner les meta / link / script du `<head>` car on avait des doublons liés à l'utilisation de la balise `Head` de `next/document`

2021-09-22 08:30 UTC, maxgfr requested changes
C'est génial, mais oui j'aurai sûrement segmenter en deux les metas. Un pour les contributions, et l'autre pour le global de l'application

2021-09-22 08:30 UTC, maxgfr commented on packages/code-du-travail-frontend/next.config.js
> +      : `http://localhost:${process.env.FRONTEND_PORT || 3000}`,
Ahah, bien vu, pour la string qui sera jamais null !

2021-09-22 08:30 UTC, maxgfr commented on packages/code-du-travail-frontend/pages/contribution/[slug].js
> +          <Metas title={metas.title} description={metas.description} />
Bonne idée d'avoir wrappé ça dans un component pour ce use case. En revanche, je pense que ça serait mieux d'avoir une balise Metas Global au site qui sera utilisé dans `_document.jsx`
Et une autre qui va override celle-ci pour contribution. 
J'ai aussi peur qu'avec les AT internet, et autres ça risque de poser soucis

2021-09-22 08:30 UTC, maxgfr commented on packages/code-du-travail-frontend/src/common/Metas.js
> +      <script key="smarttag" src="/static/smarttag.js" />
Du coup, ça je l'aurai laissé dans le `_document.jsx`

2021-09-22 08:30 UTC, maxgfr commented on packages/code-du-travail-frontend/src/common/Metas.js
> +      <script key="smarttag" src="/static/smarttag.js" />
Et donc utiliser `<Metas ... />` juste pour l'override

2021-09-22 08:43 UTC, maxgfr commented
fix #3487

2021-09-23 07:41 UTC, lionelB commented
> J'en ai profité pour cleaner les meta / link / script du `<head>` car on avait des doublons liés à l'utilisation de la balise `Head` de `next/document`

@maxgfr si tu regardes le source sur la preprod, on a un doublon dans la balise `<meta charset="utf-8"/>`  d'ou le deplacement des meta dans la balise meta plutot que dans le  `_document`

2021-09-23 08:07 UTC, maxgfr commented
@lionelB Oui je vois, il faudrait mettre la balise `<Meta ...` dans `_app.js`(ou alors à la mano dans toutes les pages) car là elle est effective que dans `[slug].jsx`

2021-09-23 08:48 UTC, lionelB commented
la balise `<Meta>` est deja presente dans les pages

2021-09-23 08:56 UTC, maxgfr approved these changes
👍

2021-09-23 09:07 UTC, maxgfr approved these changes
🔥

2021-09-23 13:27 UTC, maxgfr reviewed
Validé ;)

2021-09-23 13:28 UTC, carolineBda approved these changes

2021-09-23 14:42 UTC, lionelB commented
Hello, pour le cas des fiches SP / MT il faut setter le canonical sur l'url de la fiches sur le site d'origine (et pas mettre notre url)

2021-09-23 14:54 UTC, carolineBda commented
@lionelB non je ne penses pas. SI l'on fait ça on demande à google de ne pas indexer notre page mais plutot d'indexer la fiches sur le site d'origine.

2021-09-23 15:46 UTC, maxgfr commented
@lionelB @carolineBda Normalement c'est bon ;)

Il faudrait penser à mettre en e2e, des tests pour voir qu'on pète pas la balise dans une prochaine PR

2021-09-23 16:17 UTC, carolineBda approved these changes

2021-09-24 07:47 UTC, merged