feat(simulator): Add CC 0787
SocialGouv/code-du-travail-numerique pull request #3773
Opened 2021-09-22 11:55 UTC by carolineBda

2021-09-23 09:22 UTC, maxgfr requested changes
C'est bien, mais il me semble pour les départs ou mises à la retraite, lorsque c'est écrit Pas de préavis de départ. Il faut prendre celui de la CC

2021-09-23 09:22 UTC, maxgfr commented on packages/code-du-travail-modeles/src/__test__/depart.retraite.comptables.spec.ts
> +  ${4}      | ${"Assistants"} | ${0}
Concernant les départs, il me semble lorsqu'il n'y a pas de préavis de départ, il faut prendre celui de la CC donc ici 1 mois

2021-09-23 09:22 UTC, maxgfr commented on packages/code-du-travail-modeles/src/__test__/depart.retraite.comptables.spec.ts
> +  ${5}      | ${"Autres"}     | ${0}
Pareil pour là

2021-09-23 09:30 UTC, maxgfr requested changes
C'est bien, mais il me semble pour les départs ou mises à la retraite, lorsque c'est écrit Pas de préavis de départ. Il faut prendre celui de la CC

2021-09-27 08:19 UTC, maxgfr approved these changes
ça m'a l'air bon sur le code. la question que je me pose niveau UI, est-ce que c'est worth de poser deux rôles différents sur le départ et la mise à la retraite ?
L'utilisateur final sera peut-être perdu. Faudrait voir avec les juristes

2021-09-27 14:50 UTC, carolineBda commented
@m-maillot et @romain-b13 on peut en parler en stand-up demain ?

2021-09-28 08:45 UTC, m-maillot approved these changes
Je pense que l'on peut élargir un peu les tests mais sinon c'est tout bon pour moi :)

2021-09-28 08:45 UTC, m-maillot commented on packages/code-du-travail-modeles/src/__test__/depart.retraite.comptables.spec.ts
> +  ${24}     | ${"Employés"} | ${2}
Je pense que cela peut être bien de tester les 3 tranches par défaut du code du travail (0-6, 6-24, 24+)
Ici on peut ajouter un cas 25.

2021-09-28 08:45 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/comptables.yaml
> +contrat salarié . convention collective . comptables . mise à la retraite . catégorie professionnelle . cadres:
J'aime bien ce découpage en namespace ici, c'est parlant sans superflu :+1:

2021-09-29 10:37 UTC, maxgfr approved these changes

2021-09-30 15:03 UTC, merged