feat(simulator): add idcc1266
SocialGouv/code-du-travail-numerique pull request #3775
Opened 2021-09-22 14:53 UTC by carolineBda

2021-09-23 09:44 UTC, maxgfr approved these changes
ça m'a l'air niquel aussi !

2021-09-28 11:18 UTC, m-maillot requested changes
Les unités sont à mettre au singulier. 
Les références me semblent mal positionnées. Dispo pour en discuter :)

2021-09-28 11:18 UTC, m-maillot commented on packages/code-du-travail-modeles/src/__test__/depart.retraite.restauration.collectivités.spec.ts
> +    ${4}      | ${"Employés"}  | ${8}           | ${"jours"}
Suite au nouveau formatage du résultat, il faut utiliser jour au singulier dans publicode. Seulement `jour` et `mois` sont valides.

2021-09-28 11:18 UTC, m-maillot commented on packages/code-du-travail-modeles/src/__test__/depart.retraite.restauration.collectivités.spec.ts
> +    ${4}      | ${"Employés"}  | ${8}           | ${"jours"}
Utiliser l'unité `jour` sans le s

2021-09-28 11:18 UTC, m-maillot commented on packages/code-du-travail-modeles/src/__test__/depart.retraite.restauration.collectivités.spec.ts
> +        `Cette durée s’applique sauf s’il existe dans le contrat de travail des stipulations particulières.`
@noemiechassard je pense que ça fait doublon avec la note déjà en place sur le sujet, qu'en penses tu ?

2021-09-28 11:18 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/restauration_collectivités.yaml
> +  références:
Je pense qu'il faut mieux mettre les références sur les résultats. Ici la règle n'indique pas que c'est du préavis de retraite. On peut la réutiliser pour de l'indeminité de licenciement par exemple.
Je placerai les références sur les règles `contrat salarié . convention collective . restauration collectivités . catégorie professionnelle . mise à la retraite` et `contrat salarié . convention collective . restauration collectivités . catégorie professionnelle . départ à la retraite`. 
Logiquement, l'article 35 concerne le départ en lui même donc peut être sur les règles au dessus. Pour l'article 13, cela concerne la grille et devrait donc être sur les règles concernant les grilles.

2021-09-28 11:18 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/restauration_collectivités.yaml
> +      - montant: 8 jours
Pas de `s`à jour

2021-09-28 11:18 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/restauration_collectivités.yaml
> +      - montant: 8 jours
Pas de `s`à jour

2021-09-29 08:11 UTC, carolineBda commented on packages/code-du-travail-modeles/src/modeles/conventions/restauration_collectivités.yaml
> +  références:
@m-maillot je les ai mises comme ça pour pas créer une regle juste pour ça mais tu me dira ce que t'en penses

2021-09-29 08:12 UTC, carolineBda commented on packages/code-du-travail-modeles/src/__test__/depart.retraite.restauration.collectivités.spec.ts
> +        `Cette durée s’applique sauf s’il existe dans le contrat de travail des stipulations particulières.`
oui finalement on enleve

2021-09-29 10:09 UTC, maxgfr approved these changes

2021-09-30 16:04 UTC, maxgfr approved these changes

2021-10-05 07:20 UTC, m-maillot requested changes
J'aime bien l'idée d'englober dans un describe les tests :)

On pourrait le faire aussi pour les références ?

2021-10-05 07:20 UTC, m-maillot commented on packages/code-du-travail-modeles/src/__test__/depart.retraite.restauration.collectivités.spec.ts
> +describe("Mise à la retraite", () => {
Le fichier s'appelle `depart.retraite.restauration.collectivités.spec.ts` et on commence par un test `Mise à la retraite` ? 🤔 
Je pense qu'il manque `mise` dans le nom du fichier :)

2021-10-05 07:20 UTC, m-maillot commented on packages/code-du-travail-modeles/src/__test__/depart.retraite.restauration.collectivités.spec.ts
> +    ${24}     | ${"Employés"}  | ${2}           | ${"mois"}
Dans le fichier Excel, il est indiqué `Plus de 2 ans` et pas `2 ans ou plus`. 
24 mois d'ancienneté devrait renvoyé 1 mois.

2021-10-05 07:20 UTC, m-maillot commented on packages/code-du-travail-modeles/src/__test__/depart.retraite.restauration.collectivités.spec.ts
> +    ${24}     | ${"Maîtrises"} | ${2}           | ${"mois"}
Idem ici, 24 mois retourne 1 mois normalement car il est indiqué `Plus de 2 ans`.

2021-10-05 07:20 UTC, m-maillot commented on packages/code-du-travail-modeles/src/__test__/depart.retraite.restauration.collectivités.spec.ts
> +    ${24}     | ${"Maîtrises"} | ${2}           | ${"mois"}
Idem ici, il est indiqué `Plus de 2 ans` dans le fichier Excel, on doit donc retourner 1 mois.

2021-10-05 07:20 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/restauration_collectivités.yaml
> +#Convention collective nationale du personnel des entreprises de restauration de collectivités du 20 juin 1983. Etendue par arrêté du 2 février 1984 JONC 17 février 1984
Il manque un espace après le #

```suggestion
# Convention collective nationale du personnel des entreprises de restauration de collectivités du 20 juin 1983. Etendue par arrêté du 2 février 1984 JONC 17 février 1984
```

2021-10-05 07:20 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/restauration_collectivités.yaml
> +        plafond: 24 mois
Le plafond doit être 25 mois ici.

2021-10-05 07:20 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/restauration_collectivités.yaml
> +        plafond: 24 mois
Le plafond doit être 25 mois ici.

2021-10-05 07:20 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/restauration_collectivités.yaml
> +contrat salarié . convention collective . restauration collectivités . catégorie professionnelle . employés . mise à la retraite:
Je me demande si l’omission du terme préavis dans la règle ne peut pas nous jouer un tour plus tard. Car on peut avoir aussi l'indémnité de mise à la retraite. 

Je pense qu'il serait préférable de nommer la règle avec le mot clé préavis : `préavis de mise à la retraite`

2021-10-05 08:18 UTC, carolineBda commented on packages/code-du-travail-modeles/src/__test__/depart.retraite.restauration.collectivités.spec.ts
> +describe("Mise à la retraite", () => {
tout à fait !

2021-10-05 08:18 UTC, carolineBda commented on packages/code-du-travail-modeles/src/modeles/conventions/restauration_collectivités.yaml
> +contrat salarié . convention collective . restauration collectivités . catégorie professionnelle . employés . mise à la retraite:
Tout à fait

2021-10-07 08:19 UTC, m-maillot approved these changes
Nickel :+1:

2021-10-07 08:19 UTC, m-maillot commented on packages/code-du-travail-modeles/src/__test__/depart.mise.retraite.restauration.collectivités.references.spec.ts
> +describe("Références", () => {
Là le describe fait doublon :D

2021-10-07 08:34 UTC, carolineBda commented on packages/code-du-travail-modeles/src/__test__/depart.mise.retraite.restauration.collectivités.references.spec.ts
> +describe("Références", () => {
ouai c'est vrai que celui la il est un peu inutile 😬

2021-10-07 08:37 UTC, carolineBda commented on packages/code-du-travail-modeles/src/__test__/depart.mise.retraite.restauration.collectivités.references.spec.ts
> +describe("Références", () => {
ok j'ai changé, ça donne ça (et @maxgfr j'ai mis un spread auss
![Screenshot 2021-10-07 at 10 36 26](https://user-images.githubusercontent.com/4971715/136349702-e5264815-aa33-4958-a3ff-1e2f5f12a1eb.png)
i)

2021-10-07 13:21 UTC, merged

2021-10-27 11:54 UTC, romain-b13 commented
La CC apparaît comme non traitée en preprod