feat(simulator): Standardize simulator results ui
SocialGouv/code-du-travail-numerique pull request #3785
Opened 2021-09-27 09:15 UTC by carolineBda

2021-09-27 12:54 UTC, maxgfr reviewed
👍

2021-09-27 12:54 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/IndemnitePrecarite/steps/Indemnite.js
> -`;
J'aurai peut-être diviser ce component en plusieurs parties pour plus de visibilités à la lecture

2021-09-27 12:55 UTC, maxgfr commented
D'ailleurs, je vois tu fix, plusieurs points, ça aurait peut-être mieux de diviser en plusieurs PRs, afin de simplifier la visibilité

2021-09-27 13:00 UTC, maxgfr reviewed
👍

2021-09-27 14:07 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/IndemnitePrecarite/steps/Indemnite.js
> -`;
tu as raison, j'ai extrait le component Disclaimer

2021-09-27 14:29 UTC, maxgfr approved these changes
🔥

2021-09-27 14:29 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/IndemnitePrecarite/components/Disclaimer.js
> +export { Disclaimer };
J'aurai fait un export default vu qu'il y a qu'un composant

2021-09-27 14:36 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/IndemnitePrecarite/components/Disclaimer.js
> +export { Disclaimer };
👍

2021-09-28 11:51 UTC, m-maillot approved these changes
Quelques suggestions d'améliorations (notamment pour créer des composants communs à l'ensemble des simulateurs). 
Dispo pour le faire ensemble si tu veux :)

PS: on peut aussi en profiter pour basculer en TS certains fichiers :)

2021-09-28 11:51 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/DureePreavisDemission/steps/Result.js
> +        <Disclaimer ccn={ccn} />
Il n'y a pas d'argument ccn sur le Disclaimer. Ce doit être un reliquat. On aurait pu en profiter pour passer en typescript 😉

2021-09-28 11:51 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/DureePreavisDemission/steps/Result.js
> +                {recapSituation({
J'aurais bien profité de l'occasion pour transformer ces fonctions en composants react. 
On peut même rendre l'accodéon générique et avoir un composant qui prend en entrée un contenu éléments saisis (`situation`), un autre qui pend les références et un dernier qui détail le calcul. Chaque simu l'utilise ensuite dans sa page de résultat avec les éléments dont il dispose.

2021-09-28 11:51 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/DureePreavisLicenciement/steps/Result.js
> +          Attention il peut exister une durée plus favorable
Je pense que l'on peut aussi le rendre générique car c'est un encadré que l'on retrouve sur l'ensemble des simulateurs.

2021-09-28 11:51 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/DureePreavisLicenciement/steps/Result.js
> +            body: (
Je pense que l'on peut exploser le body pour plus de lisibilité.

2021-09-28 11:51 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/HeuresRechercheEmploi/steps/Result.js
> +      {idcc > 0 && (
On pourrait faire un composant que l'on inclut dans les différents simulateurs aussi.

2021-09-28 11:51 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/IndemniteLicenciement/components/FormulaDetails.js
> +                    <PubliReferences
Cool :) On peut le réutiliser sur les autres simu peut être ?

2021-09-30 16:39 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/common/math.js
> +export const isNotNearZero = (toTest) => parseInt(toTest, 10) > 0;
Il faudrait créer un `common` folder commun à toute l'appli. Car on peut s'en re-servir de cette fonction

2021-09-30 16:39 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/DureePreavisLicenciement/steps/Result.js
> +            contrat de travail ou les usages.
Quid d'avoir des constantes pour les messages afin de les éditer plus facilement et de lire plus facilement le code ?

2021-09-30 16:39 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/DureePreavisLicenciement/steps/Result.js
> +        ]}
Lisibilité pas au top, c'est vrai que de wrapper ça dans un component aurait été mieux

2021-09-30 16:39 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/IndemnitePrecarite/components/Disclaimer.js
> +function Disclaimer({ situation, idcc }) {
Vu que c'est un nouveau composant, ça aurait été mieux en typescript

2021-10-06 09:09 UTC, maxgfr requested changes
Quelques petits changements et c'est parfait

2021-10-06 09:09 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/DureePreavisLicenciement/steps/Result.js
> +    if (isNotNearZero(durationCDT)) {
avec un `switch`, je pense ça aurait été mieux

2021-10-06 09:09 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/DureePreavisLicenciement/steps/Result.js
> +    </p>
D'ailleurs le problème pourrait venir de cette function, car s'il y a deux return d'activé, je pense que `React` n'aime pas

2021-10-06 09:09 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/DureePreavisLicenciement/steps/Result.js
> +    </p>
Pour le coup, je pense qu'il vaut mieux couper ce fichier en deux

2021-10-06 09:09 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/DureePreavisRetraite/steps/component/WarningResult.tsx
> +const title = "Attention il peut exister une durée plus favorable";
Ah quoi sert cette `const` ?

2021-10-06 09:09 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/HeuresRechercheEmploi/steps/Result.js
> +        !duration ? (
J'aurai fait l'inverse `duration ? (..) : (...)`

2021-10-06 09:09 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/common/Disclaimer.tsx
> +const Disclaimer = ({ title, children }: Props): JSX.Element => (
C'est super ça 🔥

2021-10-06 09:09 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/IndemnitePrecarite/steps/Indemnite.js
>          : "La convention collective n'a pas été traitée par nos services."
C'est un peu bizarre la manière dont c'est écrit ^^

2021-10-06 09:15 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/HeuresRechercheEmploi/steps/Result.js
> +        !duration ? (
Oui !

2021-10-06 09:16 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/DureePreavisRetraite/steps/component/WarningResult.tsx
> +const title = "Attention il peut exister une durée plus favorable";
elle est utilisé plus bas. Je la descend dans le code 👍

2021-10-06 09:22 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/DureePreavisLicenciement/steps/Result.js
> +    if (isNotNearZero(durationCDT)) {
UPDATE : 
Pour le `switch`, effectivement il y a plusieurs variables, c'est pas top. Peut-être essayer de wrapper dans `<>..</>`puis de faire des `maVariable && (...)`. Ca serait plus lisible peut etre

2021-10-06 14:39 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/DureePreavisLicenciement/steps/Result.js
> +            contrat de travail ou les usages.
pas fan du tout 😬

2021-10-07 08:28 UTC, carolineBda commented
> D'ailleurs, je vois tu fix, plusieurs points, ça aurait peut-être mieux de diviser en plusieurs PRs, afin de simplifier la visibilité

Ouai c'est vrai en fait. C'est devenu gros la

2021-10-07 08:30 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/IndemnitePrecarite/steps/Indemnite.js
>          : "La convention collective n'a pas été traitée par nos services."
Je suis d'accord ! T'aurais mis comment ? Avec un vrai if ?

2021-10-07 08:43 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/IndemnitePrecarite/steps/Indemnite.js
>          : "La convention collective n'a pas été traitée par nos services."
`ccn && situations.length > 0 ? ccn.title : "La convention..."`

C'est un peu plus clair, et j'ai l'impression que ça revient au même

2021-10-07 12:27 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/HeuresRechercheEmploi/steps/Result.js
> +      {idcc > 0 && (
Bonne idée. C'est fait

2021-10-07 12:28 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/IndemnitePrecarite/components/Disclaimer.js
> +function Disclaimer({ situation, idcc }) {
Done 👍

2021-10-07 13:06 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/IndemniteLicenciement/components/FormulaDetails.js
> +                    <PubliReferences
C'est ici que je disais que je  penses qu'on ne peut pas ré-utiliser facilement ce composant

2021-10-07 13:07 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/DureePreavisLicenciement/steps/Result.js
> +    if (isNotNearZero(durationCDT)) {
mais du coup pour les else je fais des !maVariable && (...) ?

2021-10-07 13:09 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/IndemnitePrecarite/steps/Indemnite.js
>          : "La convention collective n'a pas été traitée par nos services."
et apres on met `!ccn && "La convention collective n'a pas été renseignée."` ?

2021-10-07 13:15 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/DureePreavisLicenciement/steps/Result.js
> +            body: (
j'en ai extrait des partis mais ça reste très dur à lire :(

2021-10-07 13:21 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/IndemnitePrecarite/steps/Indemnite.js
>          : "La convention collective n'a pas été traitée par nos services."
`(!cnn && stiuations.length < 0) && "La ......"` peut être

2021-10-07 13:22 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/IndemnitePrecarite/steps/Indemnite.js
>          : "La convention collective n'a pas été traitée par nos services."
Je pense qu'il faut prendre en compte la `length` de `situations`

2021-10-07 13:23 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/DureePreavisLicenciement/steps/Result.js
> +    if (isNotNearZero(durationCDT)) {
ah ou alors `maVariable ? (...) : (...)`

2021-10-07 13:29 UTC, maxgfr approved these changes
Niquel, juste une problématique de `render`

2021-10-07 13:29 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/DureePreavisRetraite/steps/component/WarningResult.tsx
> +  const title = "Attention il peut exister une durée plus favorable";
Je suis pas fan de mettre les const ici dans le composant. Car à chaque `render` ça va les ré-excuter. C'est vraiment une question de performances

2021-10-07 13:29 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/DureePreavisRetraite/steps/component/WarningResult.tsx
> +  const title = "Attention il peut exister une durée plus favorable";
Après pour le type, ça sous-entend de faire un `useEffect` pour optimiser cela

2021-10-07 14:11 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/DureePreavisRetraite/steps/component/WarningResult.tsx
> +  const title = "Attention il peut exister une durée plus favorable";
j'ai bougé le title

2021-10-07 14:12 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/IndemnitePrecarite/steps/Indemnite.js
>          : "La convention collective n'a pas été traitée par nos services."
en fait je vois pas en quoi ça rend le code plus lisible. Tu veux essayer de le checkout et de le faire chez toi ?

2021-10-12 19:48 UTC, m-maillot approved these changes
Comme tu l'as dit, on a peut être été trop loin dans cette PR :) Il faudrait qu'on se limite au passage en typescript dans un premier temps puis refacto dans un second temps. Mais bien joué 👍

2021-10-12 19:48 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/DureePreavisLicenciement/steps/Result.js
> +            body: (
C'est mieux déjà :)

2021-10-12 19:48 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/IndemniteLicenciement/components/FormulaDetails.js
> +                    <PubliReferences
Ok, tant pis, c'est déjà top de l'avoir réutiliser ici 👍

2021-10-13 07:47 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/DureePreavisRetraite/steps/component/WarningResult.tsx
> +  const title = "Attention il peut exister une durée plus favorable";
Il faudrait le mettre en haut de la function component

2021-10-14 08:21 UTC, m-maillot approved these changes
:+1:

2021-10-14 12:08 UTC, m-maillot approved these changes

2021-10-14 12:12 UTC, merged