feat(widget): Add backlink to widget code snippet (SEO purpose)
SocialGouv/code-du-travail-numerique pull request #3791
Opened 2021-09-29 13:52 UTC by carolineBda

Fix https://github.com/SocialGouv/code-du-travail-numerique/issues/3786

2021-09-29 14:45 UTC, maxgfr reviewed
Reviewed

2021-09-30 16:04 UTC, maxgfr approved these changes
Pour moi, ça m'a l'air bon, que des retours mineurs qui portent à la discussion. Bien joué 😁

2021-09-30 16:04 UTC, maxgfr commented on packages/code-du-travail-frontend/public/widget.html
> +      alt="le Code du travail numérique"
`Le` en majuscule😁

2021-09-30 16:04 UTC, maxgfr commented on packages/code-du-travail-frontend/public/widget.html
> +        src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAG0AAAAoCAMAAADDs4S7AAAAw1BMVEX///////9wcMFAQKxgYLrv7/j0oKXpQEvwgIcAAJFAQK373+HlIC3hAA/sYGkQEJivr9z2sLS/v+P0n6X4wMPjEB4gIJ/f3/LucHifn9blHy3y
très bonne idée la base64 ;)

2021-09-30 16:04 UTC, maxgfr commented on packages/code-du-travail-frontend/public/widget.js
> +        box-shadow: rgba(121, 148, 212, 0.4) 0 0.8rem 1.4rem;
`0px`, c'est mieux nop ?

2021-09-30 16:04 UTC, maxgfr commented on packages/code-du-travail-frontend/public/widget.html
> +     title="le Code du travail numérique - Obtenez les réponses à vos questions sur le droit du travail.">
`Le`

2021-09-30 16:04 UTC, maxgfr commented on packages/code-du-travail-frontend/public/widget.html
> +        content="default-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' 'unsafe-inline' data:; font-src 'self' data:;">
Est-ce que ça vaudrait le coup de rajouter une canonical ici ?

2021-10-01 14:51 UTC, lionelB commented on packages/code-du-travail-frontend/pages/integration.js
> +  pre {
il vaut mieux créer un objet dédié que faire du nesting depuis l'élément code pour éviter d'introduire un poids supplémentaire dans le selecteur

2021-10-01 14:52 UTC, lionelB commented on packages/code-du-travail-frontend/public/widget.js
> +        box-shadow: rgba(121, 148, 212, 0.4) 0 0.8rem 1.4rem;
nope quand c'est 0 pas besoin de mettre d'unité

2021-10-01 15:01 UTC, lionelB commented
je viens de tester l'intégration depuis un code sandbox, j'ai l'impression que le async fonctionne a partir du moment ou on reload la page...  (https://xo0p7.csb.app/)
edition : https://codesandbox.io/s/zealous-williamson-xo0p7?file=/index.html

Du coup je pense que le soucis viens peut-être de l'initialisation du code addWidget qui se lance pas ou pas au bon moment

2021-10-04 08:09 UTC, carolineBda commented on packages/code-du-travail-frontend/public/widget.html
> +        content="default-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' 'unsafe-inline' data:; font-src 'self' data:;">
Normalement elle est pas indexé par google. T'aurais mis une canonical vers elle même c'est ça ?

2021-10-04 08:11 UTC, carolineBda commented on packages/code-du-travail-frontend/public/widget.html
> +        src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAG0AAAAoCAMAAADDs4S7AAAAw1BMVEX///////9wcMFAQKxgYLrv7/j0oKXpQEvwgIcAAJFAQK373+HlIC3hAA/sYGkQEJivr9z2sLS/v+P0n6X4wMPjEB4gIJ/f3/LucHifn9blHy3y
C'est Lionel :)

2021-10-04 08:15 UTC, carolineBda commented on packages/code-du-travail-frontend/public/widget.html
> +      alt="le Code du travail numérique"
T'as raison

2021-10-04 08:17 UTC, carolineBda commented on packages/code-du-travail-frontend/pages/integration.js
> +  pre {
ok reverted 👍

2021-10-04 08:21 UTC, carolineBda commented
@lionelB pour l'instant je laisse sans le async pour que ça fonctionne. On va créer 2 nouveaux widgets on regardera en même temps.

2021-10-04 08:45 UTC, maxgfr approved these changes

2021-10-04 08:47 UTC, maxgfr commented
J'ai approuvé car niveau code, c'est niquel pour moi. 

En revanche, concernant le commentaire de Lionel, et le lien qui a mis. Cela ne semble pas fonctionner au first reload, du coup ça a été corrigé ?

2021-10-04 08:51 UTC, m-maillot approved these changes
Ok pour moi. Il faudra en effet voir pourquoi le async ne fonctionne pas mais je ne pense pas que ce soit critique dans un premier temps.

2021-10-04 08:53 UTC, maxgfr commented
> J'ai approuvé car niveau code, c'est niquel pour moi.
> 
> En revanche, concernant le commentaire de Lionel, et le lien qui a mis. Cela ne semble pas fonctionner au first reload, du coup ça a été corrigé ?

J'ai retesté sans le async : https://codesandbox.io/s/vigorous-hellman-9wh52?file=/index.html

Ca ne semble pas fonctionné à chaque fois 🤔

2021-10-04 09:01 UTC, maxgfr commented on packages/code-du-travail-frontend/public/widget.html
> +        content="default-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' 'unsafe-inline' data:; font-src 'self' data:;">
Bah en soit je me disais vu que ça pouvait être intéressant de référencer cette iframe là. Dans tous les cas, cette page sera crowler par google, avec ou sans canonical

2021-10-04 09:09 UTC, maxgfr requested changes
Niveau code niquel, en revanche lorsque je test le widget, en first load, ça ne fonctionne pas 🧐

2021-10-04 11:38 UTC, carolineBda commented
@maxgfr sur le lien que tu as partagé il y a une typo sur l'inclusion sur script (//) :
    <script src="https://feat-backlink-on-9e0m60-code-du-travail-numerique.dev.fabrique.social.gouv.fr//widget.js"></script>

Pour moi ça fonctionne sans le async

2021-10-04 15:05 UTC, maxgfr commented
J'ai fait un GIF qui montre le problème que j'ai, même en mettant à jour le lien : https://gfycat.com/meanmessylangur

2021-10-04 15:46 UTC, maxgfr commented
@carolineBda Après j'ai testé avec l'iframe et le problème ne se pose pas. Mais après peut-être que ça vient du site de testing aussi. 🤔

Y'a-t-il des alternatives pour tester ce genre de feature ?

Après je pense que nous sommes pas passer par du React, dans le but d'optimiser le widget en évitant de loader du code inutile, c'est ça ?
 
<img width="1335" alt="Screenshot 2021-10-04 at 17 43 29" src="https://user-images.githubusercontent.com/25312957/135881932-148abdb2-b1c6-4d1c-9662-a5ce738b1174.png">

2021-10-05 10:01 UTC, carolineBda commented on packages/code-du-travail-frontend/public/widget.html
> +        content="default-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' 'unsafe-inline' data:; font-src 'self' data:;">
normalement cette page ne sera jamais crawlé (pas dans le site map)

2021-10-05 10:10 UTC, maxgfr approved these changes
Bien joué 🚀

2021-10-06 07:44 UTC, merged