feat(simulator): Add CC 1501
SocialGouv/code-du-travail-numerique pull request #3817
Opened 2021-10-06 13:18 UTC by carolineBda

2021-10-06 14:10 UTC, maxgfr requested changes
Deux trois petites modifs et c'est parfait 🔥

2021-10-06 14:10 UTC, maxgfr commented on packages/code-du-travail-modeles/src/__test__/depart.mise.restauration.rapide.spec.ts
> +    test.each`
Je pense pas que ça soit utile de wraper dans un describe un seul test, pour moi c'est plus intéressant d'en mettre deux. J'ai fait ça sur ma derniere cc : https://github.com/SocialGouv/code-du-travail-numerique/pull/3818/files

2021-10-06 14:10 UTC, maxgfr commented on packages/code-du-travail-modeles/src/__test__/depart.mise.restauration.rapide.spec.ts
> +  let CCReferences = [
je suis plus fan des `const`

2021-10-06 14:10 UTC, maxgfr commented on packages/code-du-travail-modeles/src/__test__/depart.mise.restauration.rapide.spec.ts
> +      ${25}     | ${"Cadres"}             | ${2}           | ${"mois"}    | ${DepartRetraiteRefs}
Il faudrait aussi tester `24` mois d'ancienneté pour être sûr de l'inclusion

2021-10-06 14:56 UTC, carolineBda commented on packages/code-du-travail-modeles/src/__test__/depart.mise.restauration.rapide.spec.ts
> +    test.each`
en fait si je trouve ça utile c'est pour l'affichage des résultat quand on unroll sur plein de valeurs :
![Screenshot 2021-10-06 at 16 55 02](https://user-images.githubusercontent.com/4971715/136229008-9a795cfd-1606-4af9-a16e-b82fe69b4b1f.png)

2021-10-06 14:57 UTC, carolineBda commented on packages/code-du-travail-modeles/src/__test__/depart.mise.restauration.rapide.spec.ts
> +  let CCReferences = [
Mais tout à fait !

2021-10-06 15:01 UTC, carolineBda commented on packages/code-du-travail-modeles/src/__test__/depart.mise.restauration.rapide.spec.ts
> +      ${25}     | ${"Cadres"}             | ${2}           | ${"mois"}    | ${DepartRetraiteRefs}
true. C'est fait

2021-10-06 15:26 UTC, maxgfr commented on packages/code-du-travail-modeles/src/__test__/depart.mise.restauration.rapide.spec.ts
> +    test.each`
Ah je vois, oui, pour le coup avec le `test.each` ça permet d'avoir un truc pas mal bien architecturé

2021-10-06 15:27 UTC, maxgfr commented on packages/code-du-travail-modeles/src/__test__/depart.mise.restauration.rapide.spec.ts
> +    test.each`
C'est vrai que moi sur le `describe` j'ai merge deux `test.each`, départ et mise à la retraite

Là aussi ça se discute

2021-10-06 15:28 UTC, maxgfr approved these changes
😉

2021-10-07 10:27 UTC, maxgfr commented on packages/code-du-travail-modeles/src/__test__/depart.mise.restauration.rapide.spec.ts
> +    test.each`
Pour le coup, l'arborescence est niquel comme ça. J'ai testé ça sur la 1505, https://github.com/SocialGouv/code-du-travail-numerique/pull/3822
Beaucoup plus de lisibilité, en effet.

2021-10-12 13:34 UTC, m-maillot approved these changes
:+1:

2021-10-12 14:55 UTC, merged