feat(simulator): Add CC 1979
SocialGouv/code-du-travail-numerique pull request #3825
Opened 2021-10-07 14:06 UTC by carolineBda

Fix https://github.com/SocialGouv/code-du-travail-numerique/issues/3535

2021-10-12 14:13 UTC, m-maillot requested changes
Il y a une erreur sur le Cadres de plus de 6 mois qui devrait être à 3 mois.

2021-10-12 14:13 UTC, m-maillot commented on packages/code-du-travail-modeles/src/__test__/depart.mise.retraite.hotels.cafes.restaurants.spec.ts
> +describe("CC 1979", () => {
On peut ajouter le nom de la régle pour savoir ce que l'on test sur la CC 1979
```suggestion
describe("Prévis de retraite pour la CC 1979", () => {
```

2021-10-12 14:13 UTC, m-maillot commented on packages/code-du-travail-modeles/src/__test__/depart.mise.retraite.hotels.cafes.restaurants.spec.ts
> +      ${24}     | ${"Cadres"}             | ${2}           | ${"mois"}    | ${MiseRetraiteRefs}
Ce n'est pas 3 mois ? Un cadres en mise à la retraite avec plus de 6 mois dispose d'un préavis de 3 mois. Les deux derniers tests devrait être à 3 mois d'après ce que le document Excel.

2021-10-12 14:13 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/hotels_cafes_restaurants.yaml
> +  applicable si:
`applicable si` est inutile ici. Dès que c'est un employés, on veut appliquer cette règle.

2021-10-12 14:13 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/hotels_cafes_restaurants.yaml
> +  applicable si:
Idem ici, `applicable si` inutile.

2021-10-12 14:13 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/hotels_cafes_restaurants.yaml
> +  applicable si:
Idem ici, `applicable si` est inutile ici.

2021-10-12 14:13 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/hotels_cafes_restaurants.yaml
> +      - montant: 2 mois
3 mois d'après le document Excel.

2021-10-12 16:15 UTC, carolineBda commented on packages/code-du-travail-modeles/src/modeles/conventions/hotels_cafes_restaurants.yaml
> +  applicable si:
bin je pensais que non justement pour  pas clash avec les futurs simulateurs ?

2021-10-12 16:46 UTC, carolineBda commented on packages/code-du-travail-modeles/src/__test__/depart.mise.retraite.hotels.cafes.restaurants.spec.ts
> +      ${24}     | ${"Cadres"}             | ${2}           | ${"mois"}    | ${MiseRetraiteRefs}
Oui !!

2021-10-18 11:57 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/hotels_cafes_restaurants.yaml
> +  applicable si:
On ne l'a pas fait sur l'ensemble des autres questions actuellement. Je ne sais pas comment on va traiter ces points dans les futurs simulateurs, du coup, je n'aurais rien mis pour le moment et le fait d'avoir des TU nous permettra de les mettre à jour au fur et à mesure si besoin.

2021-10-18 14:21 UTC, m-maillot approved these changes

2021-10-18 14:52 UTC, merged