feat(modeles): add cc 2264 retirement
SocialGouv/code-du-travail-numerique pull request #3826
Opened 2021-10-07 14:42 UTC by maxgfr

#3535

2021-10-07 15:23 UTC, carolineBda approved these changes

2021-10-07 15:23 UTC, carolineBda commented on packages/code-du-travail-modeles/src/modeles/conventions/hospitalisation_privees.yaml
> +  applicable si: mise à la retraite
👍 👍

2021-10-12 14:05 UTC, maxgfr commented
Cette CC, ne doit pas être mergé tant que ce problème n'est pas validé : 

> Mise en retraite des cadres: le critère + de 5 ans d'ancienneté n'est pas demandé à l'usager.  Il est tenu compte de ce crtère dans le calcul: c'est à dire quand on remplit le champ prévu pour les mois de 2 ans avec 156 mois, le critère + de 5 ans d'ancienneté est testé et renvoie au bon résultat, mais une question en plus est nécessaire pour l'usager qui va cocher normalement dans ce cas + de 2 ans d'ancienneté (Ajouter :Le salarié a-t-il plus de 5 ans d'ancienneté dans l'entreprise)

2021-10-12 14:20 UTC, m-maillot requested changes
Il faut également implémenter dans l'ancienneté les 5 ans.
Le détail est dans cette issue : 
https://github.com/SocialGouv/code-du-travail-numerique/issues/3528

2021-10-12 14:20 UTC, m-maillot commented on packages/code-du-travail-modeles/src/__test__/depart.mise.retraite.hospitalisation.privees.spec.ts
> +describe("Convention collective 2264", () => {
Du coup, on écris CC ou Convention collective 🤪

2021-10-12 14:20 UTC, m-maillot commented on packages/code-du-travail-modeles/src/__test__/depart.mise.retraite.hospitalisation.privees.spec.ts
> +      "Pour un employé de tel catégories : $category possédant $seniority mois d'ancienneté, son préavis devrait être $expectedResult mois",
```suggestion
      "Pour un $category possédant $seniority mois d'ancienneté, son préavis devrait être $expectedResult mois",
```

2021-10-12 14:20 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/hospitalisation_privees.yaml
> +        plafond: 120 mois
120 mois = 10 ans je crois 🤔 Ici on veut 5 ans soit = 60 mois.

2021-10-12 14:20 UTC, m-maillot commented on yarn.lock
> +  integrity sha512-V50KMwwzqJV0NpZIZFwfOD5/lyny3WlSzRiXgA0G7VUnRlqttta1L6UQIHzd6EuBY/cHGfwTIck7w1yH6Q5zUw==
kezako 🤔 ?

2021-10-12 15:07 UTC, maxgfr commented on packages/code-du-travail-modeles/src/modeles/conventions/hospitalisation_privees.yaml
> +        plafond: 120 mois
😨

2021-10-13 10:02 UTC, maxgfr commented
Merci @m-maillot pour les review, oui effectivement il faudra rajouter la question.

Doit-on l'effectuer dans cette PR, ou alors valider cette PR et en faire une spécial pour ce feature ?

2021-10-13 13:42 UTC, carolineBda approved these changes

2021-10-13 13:42 UTC, carolineBda commented on packages/code-du-travail-modeles/src/modeles/conventions/hospitalisation_privees.yaml
> +        plafond: 120 mois
OMG j'avais pas vu.

2021-10-18 11:59 UTC, m-maillot commented
@maxgfr je pense qu'il faut faire la question dans la même PR, elle ne passera jamais les tests de @jrduscher sinon :)

2021-10-19 20:40 UTC, m-maillot requested changes
La question sur + de 2 ans doit toujours être demandée (raison du request changes).
L'implémentation me semble très bien sinon mais j'ai l'impression que l'on complexifie inutilement notre code ici. Je pense qu'on peut y arriver de façon soit plus `publicode` soit `ui`. J'ai un commentaire qui expose mon point de vue :)

2021-10-19 20:40 UTC, m-maillot commented on packages/code-du-travail-modeles/src/internal/ExtractSupportedCc.ts
> +  cdtn: AgreementCdtnInfo;
Attention, dans le cas de la rule, le champs cdtn peut être absent ainsi que l'`idcc` et le `préavis-retraitre`.

2021-10-19 20:40 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/batiment_etam.yaml
> +    preavisRetraite: true
Je ne pense pas que le camel case soit à utiliser dans le yaml. j'avais mis le kebab case pour les définition typescript mais je vois que ce n'est pas nécessaire en fait.

2021-10-19 20:40 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/hospitalisation_privees.yaml
> +    type: "overrideSeniority"
Après lecture, je pense que l'ajout de la complexité dans le YAML n'est peut être pas la solution.

On a une implémentation UI spécifique. Soit on décide qu'elle doit se refléter dans publicodes, soit on en fait abstraction.

Aujourd'hui, pour l'ancienneté, on en a fait abstraction. A savoir que l'on a une règle ancienneté dans le code qui attend une ancienneté en mois et une UI qui abstrait la notion de plus de 24 mois ou moins.

Là, on inclus une règle très technique dans publicode pour gérer le cas où le salarié à plus de 5 ans. Pourquoi dans le cas présent, publicode porte l'information ? 

Pour moi, il faut rester sur la même logique dans les 2 cas pour éviter de l'incompréhension futur. Dans le cas présent, je vois 2 solutions.

### C'est de l'UI

Dans ce cas, publicode ne le gère pas. On va ajouter la règle dans le code react qui va intégrer cette question si on est sur la CC 2264. 

Avantages:
 * La règle publicode reste simple
 * La règle est en clair dans react et on peut y apposer des TU facilement
Inconvénients:
 * On ne gère que ce cas, si demain une autre condition sur l'ancienneté arrive, il n'y a pas de mécanisme spécifique.

### Publicode to rule them all

Dans ce cas, actuellement, la gestion de l'ancienneté n'est pas seine. Il faudrait avoir une règle publicode qui demande si le salarié à plus de 2 ans puis si il a moins de 2 ans, un règle qui demande combien il a exactement.
Dans ce cas là, on peut facilement ajouter une règle pour cette CC qui va demander si + ou - de 5 ans en plus.

Exemple:

```yaml
contrat salarié . ancienneté plus de 2 ans:
  titre: Ancienneté du salarié plus de 2 ans
  question: Le salarié a-t-il plus de 2 ans d'ancienneté dans l'entreprise (2 ans + 1 jour) ?
  cdtn:
    type: oui-non

contrat salarié . ancienneté moins de 2 ans:
  applicable si: ancienneté plus de 2 ans = non
  titre: Ancienneté du salarié en mois
  question: Quelle est l'ancienneté du salarié dans l’entreprise en mois ?
  unité: mois
  cdtn:
    type: entier

contrat salarié . ancienneté:
  titre: Ancienneté du salarié
  unité: mois
  variations:
     - si: ancienneté plus de 2 ans
        alors: 25 mois
     - sinon: ancienneté moins de 2 ans
```

Et pour cette CC, on va poser la question supplémentaire:
```
contrat salarié . convention collective . hospitalisation privées . ancienneté plus de 5 ans:
  applicable si: ancienneté plus de 2 ans
  titre: Ancienneté du salarié plus de 5 ans
  question: Le salarié a-t-il plus de 5 ans d'ancienneté dans l'entreprise (5 ans + 1 jour) ?
  cdtn:
    type: oui-non

contrat salarié . convention collective . hospitalisation privées . ancienneté :
   applicable si: ancienneté plus de 5 ans
  remplace: ancienneté
  par: 60 mois
```

Ici, publicode dirige l'ensemble des questions liées à l'ancienneté et on peut gérer les cas particulier sans devoir passer par du code propre à CDTN.

Je n'ai pas d'avis tranché sur la question sur le choix à faire. La solution 1 me semble logique car publicode devrait s'abstraire un maximum du comportement de l'UI et être au plus simple mais en même temps ça évite d'en avoir partout. La solution 2 me plait car on retrouve ce que l'on fait dans l'UI dans notre publicode.
Par contre, un mélange des 2 sur le même sujet, je trouve cela déroutant.

2021-10-19 20:40 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/DureePreavisRetraite/steps/Anciennete.tsx
> +      {overrideQuestion ? (
En fait on ne doit pas override la question. Si l'utilisateur répond `+ de 2 ans`, on lui pose ensuite la question `+ de 5 ans`.

2021-10-20 08:23 UTC, maxgfr commented on packages/code-du-travail-modeles/src/modeles/conventions/batiment_etam.yaml
> +    preavisRetraite: true
Pour le coup, je ne pense pas que ça soit une bonne idée de laisser cette variable en kebab case et avec des accents, du fait qu'elle soit déjà utilisée côté code, au niveau du typescript. D'autant plus que celle-ci fait partie intégrante d'un objet :

```ts
export function extractImplementedCc(engine: Engine): AgreementInfo[] {
  return Object.values(engine.getParsedRules())
    .flatMap((rule) => {
      const rawNode = rule.rawNode as RuleNodeIdcc;
      const cdtnNode = rawNode.cdtn;
      if (cdtnNode) {
        const idcc = cdtnNode.idcc;
        if (idcc) {
          return {
            idcc: idcc,
            preavisRetraite: cdtnNode["préavis-retraite"] ?? false,
          };
        }
      }
      return null;
    })
    .flatMap((item) => (item !== null ? [item] : []));
}
```

2021-10-20 08:24 UTC, maxgfr commented on packages/code-du-travail-modeles/src/internal/ExtractSupportedCc.ts
> +  cdtn: AgreementCdtnInfo;
Oui, je suis d'accord. Dans la définition de type, je ne suis pas fan de mettre les propriétés du type en optionnal d'entrée de jeu. Je suis plus dans l'optique de le définir au niveau de la function via un utility type :

```
export function extractImplementedCc(engine: Engine): Partial<AgreementInfo>[] {
```

2021-10-20 08:28 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/DureePreavisRetraite/steps/Anciennete.tsx
> +      {overrideQuestion ? (
Pour moi, d'un point de vue expérience utilisateur, c'est mieux de poser qu'une seule fois la question : Avez-vous plus de 5 ans d'ancienneté.

Imaginons que le salarié à 3 ans d'ancienneté, cela risque de rajouter plusieurs étapes, pas forcément si utile que ça dans le processus de choix de son ancienneté. 

Il est pour ma part plus pertinent d'override la question initiale, uniquement dans ce use-case bien précis. Par ailleurs, j'ai passé des paramètres issues de `publicode` dans cet override dans le but où si un jour nous avons une question : Avez-vous plus de 3 ans d'ancienneté dans l'entreprise ? Celle-ci soit plus facilement implémentée

2021-10-20 09:44 UTC, maxgfr commented on packages/code-du-travail-modeles/src/modeles/conventions/hospitalisation_privees.yaml
> +    type: "overrideSeniority"
Concernant la première approche, je ne trouve pas cela pratique dans la relecture du code, d'avoir à la fois une logique métier côté publicode et une autre côté typescript pour définir ou non les questions posées. La magie opérée par publicode ne trouve plus sa place dans cette approche, car cela rend le code de manière plus spaghetti en ayant d'un côté des questions liées métiers et de l'autres de la logique métier.

La seconde approche me semble pertinente mais assez overkill. En effet, pour moi, il est certes nécessaire de définir la manière dont on override les questions côtés `publicode`. Par définition, c'est l'approche qu'on a prise dès le début, et qu'il faut suivre pour la cohérence des données. En revanche, je ne pense pas que ça soit nécessaire, sur du court terme, et au vu des prochaines CC à établir de rajouter la partie concernant l'ancienneté de 2 ans ou moins. Celle-ci est partagée à toutes les CC. La problématique, selon moi, réside sur l'override de cette méthode, en l'applicant à la bonne CC.

Le choix effectué en partant sur la balise CDTN, et non sur une règle publicode concerne la manière de récupérer l'information. En effet, nous avons déjà une fonction qui permet de récupérer la surcharge de `cdtn` mise en place pour savoir si une CC est traitée ou non. Par conséquent, il m'est paru naturelle, de surcharger cette méthode en spécifiant les données et questions à override.

La problématique d'utiliser une règle publicode pour l'ancienneté réside sur la longueur du namespace. En effet, si nous souhaitant pouvoir la récupérer via les missing variables, il faudra la définir comme règle mère, ce qui pose des soucis dans la longueur de notre namespace.

Pour conclure, c'est vrai, comme toi, la seconde proposition que tu fais, me semble la plus élégante. En revanche, pour ce use case particulier, je ne pense pas que ça soit nécessaire de mettre en place une nouvelle règle spécialement pour cette question là.

2021-10-21 13:30 UTC, carolineBda commented
Je viens de lire tous vos commentaires. Je crois qu'il me manque du contexte.

Certains doivent être tranché par le business c'est ça (override ou non) ? 
Et sait-on si dans les CC qui restent il y a beaucoup de cas particuliers comme ça ?

2021-10-21 13:32 UTC, carolineBda commented on packages/code-du-travail-modeles/src/modeles/conventions/batiment_etam.yaml
> +    preavisRetraite: true
je comprends ce que tu dis @maxgfr mais j'ai l'impression qu'on le fait déjà partout comme ça :
```
engine.setSituation({
      "contrat salarié . ancienneté": 6,
```
Donc pour garder la consistence je garderai :
```
préavis retraite : ...
```

2021-10-21 14:48 UTC, m-maillot commented on packages/code-du-travail-modeles/src/internal/ExtractSupportedCc.ts
> +  cdtn: AgreementCdtnInfo;
export type RuleNodeIdcc = Rule & {
  cdtn?: Partial<AgreementInfo>;
};

2021-10-21 15:17 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/hospitalisation_privees.yaml
> +    type: "overrideSeniority"
Mettre la question en statique dans le code frontend.
Trigger avec le numéro de la CC.

2021-10-21 15:17 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/batiment_etam.yaml
> +    preavisRetraite: true
renomme en `préavis de retraite: `

2021-10-21 15:17 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/DureePreavisRetraite/steps/Anciennete.tsx
> +      {overrideQuestion ? (
Je l'avais expliqué à l'envers: 
 * D'abord 5 ans et plus
 * Ensuite 2 ans et plus
 * Enfin le nombre de mois

2021-10-27 09:06 UTC, maxgfr commented
J'ai modifié le fichier `package.json` car la build ne fonctionnait pas bien avec le modeles, dès que je faisais des changements, ça ne l'appliquait pas de manière automatique sur le frontend. Le problème est corrigé.

Concernant le `.gitignore`, j'ai add le `.DS_Store` qui ne fait que se glisser sur mes PR

2021-10-27 13:03 UTC, carolineBda commented on packages/code-du-travail-modeles/src/modeles/conventions/hospitalisation_privees.yaml
> +    special: mise à la retraite 5 ans
"ancienneté spécifique"

2021-10-27 13:03 UTC, carolineBda approved these changes
👍

2021-10-28 08:01 UTC, maxgfr commented
Validé par JR

2021-11-03 17:18 UTC, m-maillot approved these changes

2021-11-03 17:18 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/DureePreavisRetraite/steps/Anciennete.tsx
> +          }}
Il manque le tooltip ici.

2021-11-04 10:33 UTC, merged