fix(data): linter and reference about Code du travail
SocialGouv/code-du-travail-numerique pull request #3831
Opened 2021-10-08 09:30 UTC by maxgfr

2021-10-10 15:32 UTC, carolineBda approved these changes
👍 👍

2021-10-11 07:02 UTC, m-maillot requested changes
Y a t'il une issue associée ? Les liens n'arrivent plus au même endroit, normal ?

2021-10-12 14:06 UTC, maxgfr commented
@m-maillot Bien vu ;)

2021-10-12 14:23 UTC, m-maillot approved these changes
All good 😎

2021-10-12 14:30 UTC, merged