tfeat(modeles): add cc 1518
SocialGouv/code-du-travail-numerique pull request #3833
Opened 2021-10-08 15:43 UTC by maxgfr

#3536

2021-10-12 09:56 UTC, carolineBda commented on packages/code-du-travail-modeles/src/modeles/conventions/education_loisirs.yaml
> +    Article 4.4.1, Article 4.4.3 et Article 4.4.4: https://www.legifrance.gouv.fr/conv_coll/article/KALIARTI000038525633?idConteneur=KALICONT000005635177
du coup on les descends

2021-10-12 09:56 UTC, carolineBda requested changes
juste les ref à descendre

2021-10-12 14:23 UTC, maxgfr commented on packages/code-du-travail-modeles/src/modeles/conventions/education_loisirs.yaml
> +    Article 4.4.1, Article 4.4.3 et Article 4.4.4: https://www.legifrance.gouv.fr/conv_coll/article/KALIARTI000038525633?idConteneur=KALICONT000005635177
Oui :)

2021-10-12 15:17 UTC, m-maillot requested changes

2021-10-12 15:17 UTC, m-maillot commented on packages/code-du-travail-modeles/src/__test__/depart.mise.retraite.education.loisirs.spec.ts
> +  CommonReference,
Je ne vois pas ces références sur le Excel pour le départ à la retraite. La colonne référence est vide.

2021-10-12 15:17 UTC, m-maillot commented on packages/code-du-travail-modeles/src/__test__/depart.mise.retraite.education.loisirs.spec.ts
> +          expect.arrayContaining(DepartRetraiteCcReferences)
Ici, on ne devrait avoir que les références du code du travail.

2021-10-12 15:17 UTC, m-maillot commented on packages/code-du-travail-modeles/src/__test__/depart.mise.retraite.education.loisirs.spec.ts
> +      ${"Ouvriers et employés (groupes 2 et 3)"}                  | ${24}     | ${2}
Dans le Excel, on parle de 2 ans ou moins. Du coup 24 mois devrait retourner 1 mois.

2021-10-12 15:23 UTC, carolineBda commented on packages/code-du-travail-modeles/src/__test__/depart.mise.retraite.education.loisirs.spec.ts
> +      ${"Ouvriers et employés (groupes 2 et 3)"}                  | ${24}     | ${2}
Non parce que dans ce que le code du travail est + avantageux non ?

2021-10-12 16:37 UTC, m-maillot commented on packages/code-du-travail-modeles/src/__test__/depart.mise.retraite.education.loisirs.spec.ts
> +      ${"Ouvriers et employés (groupes 2 et 3)"}                  | ${24}     | ${2}
En effet :)

2021-10-13 13:40 UTC, carolineBda approved these changes

2021-10-19 15:43 UTC, m-maillot approved these changes

2021-10-19 16:13 UTC, merged

2021-10-27 11:56 UTC, romain-b13 commented
la CC est reconnue comme convention prochainement traitée en preprod