feat(modeles): add cc 2120 retirement
SocialGouv/code-du-travail-numerique pull request #3838
Opened 2021-10-11 09:45 UTC by maxgfr

#3536

2021-10-12 08:03 UTC, carolineBda commented on packages/code-du-travail-modeles/src/modeles/conventions/banque.yaml
> +    Article 32: https://www.legifrance.gouv.fr/conv_coll/id/KALIARTI000005787790/?idConteneur=KALICONT000005635780
Dans le excel la ref n'est que pour la mise à la retraite

2021-10-12 15:26 UTC, carolineBda requested changes

2021-10-12 15:26 UTC, carolineBda commented on packages/code-du-travail-modeles/src/modeles/conventions/banque.yaml
> +contrat salarié . convention collective . banque . départ à la retraite:
il n'y a pas de ref pour le depart à la retraite

2021-10-12 15:26 UTC, carolineBda commented on packages/code-du-travail-modeles/src/__test__/depart.mise.retraite.banque.spec.ts
> +          expect.arrayContaining(DepartRetraiteCcReferences)
Ici c'est que les ref Code du travail

2021-10-12 15:46 UTC, m-maillot reviewed
Idem que @carolineBda :)

2021-10-12 15:55 UTC, maxgfr commented on packages/code-du-travail-modeles/src/modeles/conventions/banque.yaml
> +contrat salarié . convention collective . banque . départ à la retraite:
Bien vu, merci 😅

2021-10-13 12:08 UTC, carolineBda approved these changes

2021-10-13 13:24 UTC, merged