feat(tracking): cc treated or untreated are tracked
SocialGouv/code-du-travail-numerique pull request #3872
Opened 2021-10-14 16:13 UTC by maxgfr

fix #3733

2021-10-15 09:26 UTC, maxgfr commented
Il faudrait déjà merger #3872 et #3839 , car je me base dessus.

2021-10-19 08:31 UTC, maxgfr commented
TODO : mettre le nom de la CC au lieu de son number

2021-10-20 07:48 UTC, maxgfr commented
https://github.com/SocialGouv/code-du-travail-numerique/issues/3733#issuecomment-946817280

2021-10-21 14:07 UTC, maxgfr commented
> TODO : mettre le nom de la CC au lieu de son number

Done

2021-10-21 14:08 UTC, carolineBda commented on packages/code-du-travail-frontend/src/conventions/Search/index.tsx
> +import { AgreementStatus } from "../../outils/DureePreavisRetraite/steps/component/DecryptedResult";
Il faudrait pas extraire l'AgreementStatus dans un autre fichier ?

2021-10-21 14:09 UTC, maxgfr commented on packages/code-du-travail-frontend/src/conventions/Search/index.tsx
> +import { AgreementStatus } from "../../outils/DureePreavisRetraite/steps/component/DecryptedResult";
C'est un `type` qu'on utilise. Il faudrait mieux gérer l'import

2021-10-21 14:23 UTC, m-maillot requested changes

2021-10-21 14:23 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/DureePreavisRetraite/utils/index.ts
> +import { supportedCcn } from "@socialgouv/modeles-social";
Cela ne concerne que le simulateur de préavis de retraite. Les CC supportées ne sont pas les mêmes dans les autres simulateurs.

2021-10-21 14:23 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/DureePreavisRetraite/utils/index.ts
> +export const getAgreementStatus = (ccn: any): AgreementStatus => {
Le type de ccn est `ConventionCollective` dans le fichier WizardType.ts

2021-11-09 14:28 UTC, maxgfr commented
Le `package.json` a été modifié afin d'intégrer les logs à lerna via l'option de `stream`

2021-11-09 17:24 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/DureePreavisRetraite/utils/index.ts
> +import { supportedCcn } from "@socialgouv/modeles-social";
Voir issue #3733

2021-11-09 18:04 UTC, maxgfr commented
https://github.com/SocialGouv/code-du-travail-numerique/issues/3733#issuecomment-964400914 <=> A voir avant de review

2021-11-09 18:05 UTC, maxgfr commented
https://github.com/SocialGouv/code-du-travail-numerique/issues/3733#issuecomment-964400914 <=> A voir avant de review

2021-11-15 10:41 UTC, m-maillot approved these changes
Top ! et marche nickel :)

2021-11-15 10:58 UTC, carolineBda reviewed
Je me demande si on devrait pas rajouter un test unitaire sur la fonction `trackConventionCollective` juste pour être sur que ça crash jamais ?

2021-11-15 10:58 UTC, carolineBda commented on packages/code-du-travail-frontend/src/lib/matomo/index.ts
> +  switch (currentPath) {
ça marche si on a des query params ?

2021-11-15 10:58 UTC, carolineBda commented on packages/code-du-travail-frontend/src/lib/matomo/index.ts
> +      const realSupported = retraiteData.map((item) => {
On devrait pas faire ça hors de la function (pour le faire qu'une seule fois) ?

2021-11-15 10:58 UTC, carolineBda commented on packages/code-du-travail-frontend/src/piwik.js
> +  if (window && window._paq) {
👍

2021-11-16 14:19 UTC, maxgfr commented on packages/code-du-travail-frontend/src/lib/matomo/index.ts
> +  switch (currentPath) {
A faire dans les tests

2021-11-16 16:15 UTC, carolineBda approved these changes

2021-11-17 08:45 UTC, merged