feat(modeles): add cc 1517 retirement
SocialGouv/code-du-travail-numerique pull request #4001
Opened 2021-11-12 13:34 UTC by maxgfr

2021-11-16 15:09 UTC, carolineBda requested changes

2021-11-16 15:09 UTC, carolineBda commented on packages/code-du-travail-modeles/src/modeles/conventions/commerces_de_detail_non_alimentaires.yaml
> +  description: La catégorie professionnelle du salarié est habituellement mentionnée sur le bulletin de salaire.
```suggestion
  description: La catégorie professionnelle du salarié est habituellement mentionnée sur le **bulletin de salaire**.
```

2021-11-16 15:09 UTC, carolineBda commented on packages/code-du-travail-modeles/src/modeles/conventions/commerces_de_detail_non_alimentaires.yaml
> +  références:
je crois que la reference on la repete sur les 2 regles où il y a applicable si: mise/départ à la retraite pour pas que ça clash avec les futur utilisation de la CC pour un autre simulateur

2021-11-16 15:35 UTC, maxgfr commented on packages/code-du-travail-modeles/src/modeles/conventions/commerces_de_detail_non_alimentaires.yaml
> +  références:
Bonne question, après sémantiquement, c'est mieux comme ça

Il faudrait le faire sur d'autres CC aussi

2021-11-16 15:44 UTC, carolineBda commented on packages/code-du-travail-modeles/src/modeles/conventions/commerces_de_detail_non_alimentaires.yaml
> +  références:
il me semble que c'est ce qu'on a fait depuis le début non ?

2021-11-16 18:24 UTC, maxgfr commented on packages/code-du-travail-modeles/src/modeles/conventions/commerces_de_detail_non_alimentaires.yaml
> +  références:
Il faudrait le mettre au dessus du fichier en fait. Il y a une discussion sur les namespace dans publicodes pour gérer ça.

Sur d'autres simulateurs, ça peut poser de soucis.

A en discuter avec tous demain @m-maillot @carolineBda

2021-11-17 10:26 UTC, carolineBda commented on packages/code-du-travail-modeles/src/modeles/conventions/commerces_de_detail_non_alimentaires.yaml
> +  références:
du coup ça aussi on en avait déjà discuté, c'est pareil on laisse comme ça @m-maillot (ça me va)

2021-11-17 10:27 UTC, maxgfr commented on packages/code-du-travail-modeles/src/modeles/conventions/commerces_de_detail_non_alimentaires.yaml
> +  références:
https://github.com/SocialGouv/code-du-travail-numerique/pull/4003#discussion_r751099877

2021-11-17 16:19 UTC, m-maillot requested changes

2021-11-17 16:19 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/commerces_de_detail_non_alimentaires.yaml
> +  références:
On avait conclu que l'on explose les références pour qu'elle soit sur la règle dédiée. 
Ici, on a l'article qui indique les tranches. Il faut donc que la référence soit sur les règles où l'on parle de tranche:

```
contrat salarié . convention collective . commerces de detail non alimentaires . catégorie professionnelle . employes . mise
```
et 
```
contrat salarié . convention collective . commerces de detail non alimentaires . catégorie professionnelle . employes . depart
```

Ca perd son sens dans la lecture du fichier si on n'indique pas les références qui ont permis de rédiger cette grille.

2021-11-17 16:19 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/commerces_de_detail_non_alimentaires.yaml
> +  description: La catégorie professionnelle du salarié est habituellement mentionnée sur le **bulletin de salaire**.
```suggestion
  description: La catégorie professionnelle du salarié est habituellement mentionnée sur le <b>bulletin de salaire</b>.
```

2021-11-21 20:18 UTC, carolineBda commented on packages/code-du-travail-modeles/src/modeles/conventions/commerces_de_detail_non_alimentaires.yaml
> +  description: La catégorie professionnelle du salarié est habituellement mentionnée sur le **bulletin de salaire**.
Ah non pas de <b> please
```suggestion
  description: La catégorie professionnelle du salarié est habituellement mentionnée sur le <strong>bulletin de salaire</strong>.
```

2021-11-22 10:54 UTC, maxgfr commented on packages/code-du-travail-modeles/src/modeles/conventions/commerces_de_detail_non_alimentaires.yaml
> +  références:
Nous avons dit ça sur le namespace, non ?

2021-11-22 11:01 UTC, maxgfr commented on packages/code-du-travail-modeles/src/modeles/conventions/commerces_de_detail_non_alimentaires.yaml
> +  références:
La raison principale pour laquelle on devait pas wrapper les références sur le namespace principale était la scalabilité du namespace lorsqu'on ajoutera de nouveaux simulateurs.

En soit, vu que là, on le link à la catégorie principale, il n'y a plus trop l'utilité de faire ça.

De plus, je trouverai ça intéressant de mettre un linter en place, car cela n'est pas super scalable, et reste assez inherent à notre use case... Dans le cas où un autre développeur arrive, cela peut être problématique.

2021-11-22 11:02 UTC, maxgfr commented on packages/code-du-travail-modeles/src/modeles/conventions/commerces_de_detail_non_alimentaires.yaml
> +  références:
D'un point de vue sémantique, pour moi, tout ce qui est dans le fichier de la CC sera lié à ce simulateur, et donc tout ce qui est `namespace . convention collective . *` est lié à ce simulateur

Au risque de complexifier encore plus l'écriture du modèle

2021-11-22 15:09 UTC, m-maillot approved these changes
:+1:

2021-11-23 08:11 UTC, carolineBda approved these changes
:+1: :+1: :+1:

2021-11-23 08:16 UTC, merged