feat(modeles): add cc 3127 retirement
SocialGouv/code-du-travail-numerique pull request #4004
Opened 2021-11-12 16:34 UTC by maxgfr

2021-11-16 15:25 UTC, carolineBda commented on packages/code-du-travail-modeles/src/modeles/conventions/entreprises_services_a_la_personne.yaml
> +contrat salarié . convention collective . entreprises de services à la personne . départ à la retraite:
meme si c'est les même valeurs que le code du travail, il faut quand même les définir ici pour ensuite pouvoir dire que ce sont bien les valeur de la CC qui ont été pris en compte. Non ?

2021-11-16 15:28 UTC, maxgfr commented on packages/code-du-travail-modeles/src/modeles/conventions/entreprises_services_a_la_personne.yaml
> +contrat salarié . convention collective . entreprises de services à la personne . départ à la retraite:
En vrai, non quand y'a pas le remplace, ça passe. C'est au plus simple comme ça

2021-11-16 15:47 UTC, carolineBda commented on packages/code-du-travail-modeles/src/modeles/conventions/entreprises_services_a_la_personne.yaml
> +contrat salarié . convention collective . entreprises de services à la personne . départ à la retraite:
C'est pour pouvoir afficher ça dans le résultat (on a une erreur de retour à la ligne) 
![Screenshot 2021-11-16 at 16 46 16](https://user-images.githubusercontent.com/4971715/142018023-7192a47a-4d19-426b-8703-25bfbbd77cae.png)
:

2021-11-16 15:51 UTC, carolineBda commented on packages/code-du-travail-modeles/src/modeles/conventions/entreprises_services_a_la_personne.yaml
> +contrat salarié . convention collective . entreprises de services à la personne . départ à la retraite:
Ah non mais toi ça s'affiche quand même aussi, donc je penses que c'est bon.

2021-11-16 15:57 UTC, maxgfr commented on packages/code-du-travail-modeles/src/modeles/conventions/entreprises_services_a_la_personne.yaml
> +contrat salarié . convention collective . entreprises de services à la personne . départ à la retraite:
Oui :) D'ailleurs j'ai mis les tests unitaire qui test bien

2021-11-17 10:56 UTC, carolineBda commented on packages/code-du-travail-modeles/src/modeles/conventions/entreprises_services_a_la_personne.yaml
> +contrat salarié . convention collective . entreprises de services à la personne . départ à la retraite:
en fait j'ai retrouvé pourquoi ça pause un problème (je crois). C'est parce que toi ça affiche ça :
![Screenshot 2021-11-17 at 11 55 01](https://user-images.githubusercontent.com/4971715/142187711-1812b816-b3dd-4324-841e-56c6ee28ee95.png)

Alors que c'est faux, la ligne
Durée prévue par la convention collective (durée conventionnelle) : pas de préavis
devrait afficher :
Durée prévue par la convention collective (durée conventionnelle) : 2 mois

2021-11-17 15:20 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/entreprises_services_a_la_personne.yaml
> +contrat salarié . convention collective . entreprises de services à la personne . départ à la retraite:
Je suis d'accord avec @carolineBda. Il faut définir les tranches ici. Cela signifie du coup qu'il faudrait des tests spécifiques à la CC pour valider que l'on retourne la bonne information ici 🤔

2021-11-17 15:21 UTC, m-maillot requested changes
Il faut implémenter la tranche de la CC pour afficher le bon résultat de la CC dans le résultat décrypter.

Est ce que l'on ne mettrai pas en place des tests ciblés sur le résultat de la CC ?

2021-11-21 20:20 UTC, carolineBda commented
> Il faut implémenter la tranche de la CC pour afficher le bon résultat de la CC dans le résultat décrypter.
> 
> Est ce que l'on ne mettrai pas en place des tests ciblés sur le résultat de la CC ?

Oui effectivement

2021-11-22 15:41 UTC, m-maillot approved these changes

2021-11-22 16:21 UTC, merged