fix(rgaa): 8.9 P05 à P14
SocialGouv/code-du-travail-numerique pull request #4076
Opened 2021-12-03 08:32 UTC by maxgfr

2021-12-03 16:20 UTC, maxgfr commented
En plus, des éléments notés sur l'issue, j'ai 4 snapshot qui me lancent des console.error que je n'ai pas réussi à régler sur le `CallToActionTile` au niveau du `StyledTile` qui devrait se definir comme un `div` mais qui se comporte comme un `p`. Je ne comprends pas ce comportement.

D'ailleurs le `Tile` qui est redefinie comme un `h2` n'est pas ouf, car il wrap des div et non pas exclusivement le teste.

D'ailleurs, je pense ouvrir une discussion sur le clean code concernant les `children`, car passer une string en `children` n'est vraiment pas le principe......

2021-12-06 09:11 UTC, carolineBda commented on packages/code-du-travail-frontend/src/common/Answer.js
> +                  <p>{intro}</p>
on aura jamais du html ici ?

2021-12-06 09:11 UTC, carolineBda commented on packages/react-ui/src/Titles/common/Header.js
> +      margin-bottom: spacings.medium;
il manque le $
```suggestion
      margin-bottom: ${spacings.medium};
```

2021-12-06 09:11 UTC, carolineBda commented on packages/react-ui/src/Text/index.js
> +    $isLikeSpan &&
ça fait quoi ça ?

2021-12-06 09:11 UTC, carolineBda commented on packages/react-ui/src/Collapse/index.js
> +        <StyledText isLikeSpan fontSize="hsmall" {...textProps}>
pourquoi le fontWeight="600" ne marche pas ici ?

2021-12-06 09:11 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/common/InfosCCn.tsx
> +            <Paragraph isLikeSpan>
ça fait pas un p dans un p ça ?

2021-12-06 09:21 UTC, maxgfr commented on packages/code-du-travail-frontend/src/common/Answer.js
> +                  <p>{intro}</p>
Le text wrappé, est toujours un texte de ce que je vois, car le résultat actuelle est de le mettre dans une div....

2021-12-06 09:22 UTC, maxgfr commented on packages/react-ui/src/Titles/common/Header.js
> +      margin-bottom: spacings.medium;
Merci ! Je vais le rajouter, en revanche, je crois vu qu'on utilise cela :
```
 return css`
....
`
```
On peut glisser directement la variable, mon IDE me l'a pas notifié

2021-12-06 09:23 UTC, maxgfr commented on packages/react-ui/src/Text/index.js
> +    $isLikeSpan &&
ça permet d'enlever les éléments par défaut générer lorsqu'un `p` est utilisé côté HTML

2021-12-06 09:24 UTC, maxgfr commented on packages/react-ui/src/Collapse/index.js
> +        <StyledText isLikeSpan fontSize="hsmall" {...textProps}>
Je ne sais pas, ce que j'ai fait, c'est cela :

```
const StyledText = styled(Paragraph)`
  margin-left: ${spacings.small};
  font-weight: 600 !important;
`;
```

2021-12-06 09:24 UTC, maxgfr commented on packages/react-ui/src/Collapse/index.js
> +        <StyledText isLikeSpan fontSize="hsmall" {...textProps}>
Avec un `!important` l'override se fait.... Je suis vraiment pas fan de ce genre d'override mais je n'ai pas su faire autrement

2021-12-06 09:25 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/common/InfosCCn.tsx
> +            <Paragraph isLikeSpan>
Ouuuui :)

Peut-être le `isLikeSpan`, on pourrait trouver un autre nom plus explicite

2021-12-06 09:28 UTC, carolineBda commented on packages/react-ui/src/Collapse/index.js
> +        <StyledText isLikeSpan fontSize="hsmall" {...textProps}>
lais si tu laisse `fontWeight="600"` comme avant ça marche plus ?

2021-12-06 09:29 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/common/InfosCCn.tsx
> +            <Paragraph isLikeSpan>
en fait je comprend pas bien pourquoi on a besoin d'un `isLikeSpan` ?

2021-12-06 09:52 UTC, maxgfr commented on packages/react-ui/src/Collapse/index.js
> +        <StyledText isLikeSpan fontSize="hsmall" {...textProps}>
Oui :(

2021-12-06 09:53 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/common/InfosCCn.tsx
> +            <Paragraph isLikeSpan>
Pour éviter d'avoir des `StyledP` sur chacune des pages

2021-12-06 14:36 UTC, carolineBda commented on packages/react-ui/src/Collapse/index.js
> +        <StyledText isLikeSpan fontSize="hsmall" {...textProps}>
c'est ton `all: revert;`
Si tu merge ma branch ça va re-marcher normalement.

2021-12-06 14:37 UTC, carolineBda commented on packages/react-ui/src/ArrowLink/index.js
> +  all: unset;
franchement il vaut mieux pas faire des `all: unset;`

2021-12-06 14:39 UTC, carolineBda commented on packages/code-du-travail-frontend/src/web-components/tooltip-cc.js
> +      <p
on peut utiliser `<Paragraph noMargin>` non ?
Si c'est galère laisse tel quel pas de souci

2021-12-06 14:50 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/common/Question.tsx
> +  const onChangeVisibility = (): void => {
t'as du modifier tout ça ?

2021-12-06 14:50 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/common/Disclaimer.tsx
> +const WarningTitle = styled.p`
<Paragraph fontWeight="600" fontSize ...

2021-12-06 14:50 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/IndemniteLicenciement/steps/Info.js
> +        <Paragraph isLikeSpan>
```suggestion
        <Paragraph noMargin fontWeight="600">
          L’indemnité légale de licenciement n’est pas dûe en cas de faute grave.
        </Paragraph>
        <Paragraph> 
          Lorsqu’il est invoqué, le motif de faute grave doit apparaître
          précisément dans le courrier. Reportez vous à la lettre de
          notification de licenciement.
        </Paragraph>
```

2021-12-06 14:50 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/ConventionCollective/steps/Introduction.tsx
> +            <Text as="p" fontWeight="700">
```suggestion
            <Paragraph noMargin fontWeight="700">
```

2021-12-06 14:50 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/ConventionCollective/agreement/SearchAgreementInput.tsx
> +  Paragraph,
c'est utilisé?

2021-12-06 14:50 UTC, carolineBda commented on packages/code-du-travail-frontend/src/conventions/Search/index.tsx
>              <div>Le service de recherche est indisponible.</div>
On le met ici aussi ?

2021-12-06 14:50 UTC, carolineBda commented on packages/code-du-travail-frontend/src/contributions/Contribution.js
> +                  <span>
pas besoin de `span`

2021-12-06 14:50 UTC, carolineBda commented on packages/code-du-travail-frontend/src/common/Answer.js
> +                  <p>{intro}</p>
oui mais comment être sur qu'il n'y aura jamais de html ? Answer est utilisé sur beaucoup de page non ?

2021-12-06 15:42 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/ConventionCollective/agreement/SearchAgreementInput.tsx
> +  Paragraph,
Nop :)

2021-12-07 14:48 UTC, maxgfr commented on packages/code-du-travail-frontend/src/conventions/Search/index.tsx
>              <div>Le service de recherche est indisponible.</div>
Oh bien vu :p

2021-12-07 15:15 UTC, maxgfr commented on packages/code-du-travail-frontend/src/common/Answer.js
> +                  <p>{intro}</p>
Oui, ah des endroits, il y a du code HTML.... mais à d'autres une string :(

2021-12-07 15:51 UTC, maxgfr commented on packages/code-du-travail-frontend/src/common/Answer.js
> +                  <p>{intro}</p>
J'ai mis en place une fonction qui detect si c'est de l'HTML ou pas, et du coup si c'est une string, c'est wrappé dans un `P` par défaut

2021-12-07 15:53 UTC, maxgfr commented on packages/react-ui/src/Collapse/index.js
> +        <StyledText isLikeSpan fontSize="hsmall" {...textProps}>
Ouaip bah j'ai fait ce que t'as dit, à voir

2021-12-07 15:56 UTC, maxgfr commented on packages/react-ui/src/ArrowLink/index.js
> +  all: unset;
Ouaip

2021-12-07 15:56 UTC, maxgfr commented on packages/code-du-travail-frontend/src/web-components/tooltip-cc.js
> +      <p
Nop, car c'est pas géré via React

2021-12-07 15:58 UTC, maxgfr commented
Aucune erreur html n'est throw dans les snapshots !

2021-12-09 10:23 UTC, carolineBda requested changes

2021-12-09 10:23 UTC, carolineBda commented on packages/code-du-travail-frontend/src/common/Answer.js
> +                  {isHTML(intro) ? <Html>{intro}</Html> : <p>{intro}</p>}
top

2021-12-09 10:23 UTC, carolineBda commented on packages/code-du-travail-frontend/src/lib/__tests__/converter.test.ts
> +describe("isHtml", () => {
:+1:

2021-12-09 10:23 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/ConventionCollective/steps/Introduction.tsx
> +            <Paragraph noMarginfontWeight="700">
```suggestion
            <Paragraph noMargin fontWeight="700">
```

2021-12-09 10:23 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/common/InfosCCn.tsx
> +            <Paragraph noMargin>
t'as un p dans un p la

2022-01-03 16:18 UTC, carolineBda commented on packages/code-du-travail-frontend/src/home/Partners.js
> +        <Title as="p" isFirst stripe="left">
du coup tu peux virer `withoutHeader` de `PageTitle` je crois

2022-01-03 16:25 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/IndemniteLicenciement/ccn/0044/__tests__/__snapshots__/EchelonChimie.test.js.snap
> +  <label
pas le droit d'avoir un `<p>` dans un `<label>`

2022-01-03 16:29 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/common/Disclaimer.tsx
> +const WarningTitle = styled(Paragraph)`
On peut juste mettre des params à `Paragraph` (pas important)

2022-01-04 11:26 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/common/Disclaimer.tsx
> +const WarningTitle = styled(Paragraph)`
Concernant la font-family, on l'a pas override sur `Paragraph`. Je suis plus fan de cette approche conventionnée pour modifier ce qui est lié au style de manière globale, en fait

2022-01-04 11:29 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/IndemniteLicenciement/ccn/0044/__tests__/__snapshots__/EchelonChimie.test.js.snap
> +  <label
OUI, très juste

2022-01-04 11:31 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/common/Disclaimer.tsx
> +const WarningTitle = styled(Paragraph)`
et la font-size aussi

2022-01-04 11:32 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/IndemniteLicenciement/ccn/0044/__tests__/__snapshots__/EchelonChimie.test.js.snap
> +  <label
Le problème est l'agencement du composant `Question` qui passe un children..........

Dans le children, on sait pas ce qu'on reçoit, des fois un paragraph, d'autre fois une string....

2022-01-04 11:42 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/common/Disclaimer.tsx
> +const WarningTitle = styled(Paragraph)`
La limite est dans les paramètre de la lib :
```js
fontSize: PropTypes.oneOf([
    "default",
    "tiny",
    "small",
    "medium",
    "hsmall",
    "hmedium",
    "hmobileMedium",
    "hlarge",
  ]),
  fontWeight: PropTypes.oneOf(["300", "400", "500", "600", "700"]),
  noMargin: PropTypes.bool,
  variant: PropTypes.oneOf(["primary", "secondary", "error", "placeholder"]),
```

2022-01-05 09:07 UTC, carolineBda commented on packages/react-ui/src/Text/index.js
> +  noMargin: false,
juste pour info, pourquoi t'as rajouté ça ?

2022-01-05 09:40 UTC, carolineBda approved these changes
:+1:

2022-01-06 07:49 UTC, m-maillot approved these changes
Bien joué ! 🔥 
Pas spécialement fan des `as=` mais pas d'alernative en tête.

2022-01-12 17:39 UTC, merged