fix(headings): on tabs
SocialGouv/code-du-travail-numerique pull request #4114
Opened 2021-12-10 08:48 UTC by carolineBda

Fix #3514

2022-01-19 21:05 UTC, carolineBda commented on packages/react-fiche-service-public/src/components/Tabulator.js
> +          <Heading
On passe un heading avec le bon headingLevel

2022-01-19 21:05 UTC, carolineBda commented on packages/react-ui/src/Tabs/index.js
> +              <StyledTab key={index}>{tab}</StyledTab>
Au lieu de mettre que le texte on ajoute le component lui même (qui contient le heading)

2022-01-19 21:05 UTC, carolineBda commented on packages/react-ui/src/Tabs/index.js
> -            <ScreenReaderOnly>{tab}</ScreenReaderOnly>
On vire le ScreenReaderOnly qui duplique le heading

2022-01-20 09:51 UTC, maxgfr approved these changes
Niquel, merci pour les commentaires

2022-01-20 09:51 UTC, maxgfr commented on packages/react-fiche-service-public/src/components/Tabulator.js
> +          <Heading
Ah pas mal du tout

2022-01-20 09:51 UTC, maxgfr commented on packages/react-ui/src/Tabs/index.js
> -            <ScreenReaderOnly>{tab}</ScreenReaderOnly>
Et c'est bien accessible du coup ?

2022-01-20 11:09 UTC, maxgfr requested changes

2022-01-20 11:09 UTC, maxgfr commented on .github/workflows/quality.yml
> +#            ${{ runner.os }}-yarn-
👀

2022-01-20 14:36 UTC, maxgfr approved these changes

2022-01-20 15:33 UTC, carolineBda commented on .github/workflows/quality.yml
> +#            ${{ runner.os }}-yarn-
c'était une tentative :laughing:

2022-01-26 17:02 UTC, m-maillot approved these changes

2022-01-28 12:52 UTC, merged