fix(api): set search option same as before
SocialGouv/code-du-travail-numerique pull request #4161
Opened 2022-01-05 15:06 UTC by maxgfr

fix #4160

2022-01-06 07:59 UTC, m-maillot requested changes
J'ai remarqué quelques petites nuances avec l'ancienne version :)

2022-01-06 07:59 UTC, m-maillot commented on packages/code-du-travail-api/src/routes/search/search.elastic.js
> -                },
Avant ce changement, il y avait ce code :
```
                {
                  match_phrase_prefix: {
                    "synonymes.french": {
                      query,
                    },
                  },
                },
```

Je pense qu'il faut le remettre comme avant ici.

2022-01-06 07:59 UTC, m-maillot commented on packages/code-du-travail-api/src/routes/search/index.js
> -        getSemBody({ query, query_vector, size, sources }),
Il faut également supprimer `query` à la ligne 123

2022-01-06 14:19 UTC, maxgfr commented on packages/code-du-travail-api/src/routes/search/search.elastic.js
> -                },
Je l'ai ajouté avec #4126

2022-01-06 14:20 UTC, maxgfr commented on packages/code-du-travail-api/src/routes/search/index.js
> -        getSemBody({ query, query_vector, size, sources }),
Je l'ai ajouté avec #4129

2022-01-07 09:14 UTC, carolineBda approved these changes
Pour moi c'est ok. J'ai comparé avec le [commit du 20/12](https://github.com/SocialGouv/code-du-travail-numerique/commit/4e4ec1ebaf0be91b3240ee1c706d7db35fbe120a).
@m-maillot si t'as un doute on vérifie ensemble tout les 3?

2022-01-12 08:52 UTC, m-maillot commented on packages/code-du-travail-api/src/routes/search/index.js
> -        getSemBody({ query, query_vector, size, sources }),
On n'a pas dit que l'on retourner à un état antérieur ? Je me suis basé sur sur le tag 4.60.3 (https://github.com/SocialGouv/code-du-travail-numerique/blob/v4.60.3/packages/code-du-travail-api/src/routes/search/index.js) et il n'y a pas de query. 

De plus, tu l'as supprimé dans cet PR dans la fonction `getSemQuery` : https://github.com/SocialGouv/code-du-travail-numerique/pull/4161/files#diff-d1573653268aac55c0f4c8bf0269d4eeb17dc34a6ba12c79f1f9fc7208623b3dR3

Du coup, il ne sert plus à rien 🤔

2022-01-12 08:52 UTC, m-maillot commented on packages/code-du-travail-api/src/routes/search/search.elastic.js
> -                },
Je pensais que l'on supprimé les modifs sur la fin de l'année en attendant de voir avec @rmelisson 

@carolineBda ?

2022-01-12 08:52 UTC, m-maillot commented on packages/code-du-travail-api/src/routes/search/search.elastic.js
> -                },
Et [ligne 58](https://github.com/SocialGouv/code-du-travail-numerique/pull/4161/files#diff-09481b674e212fc363d68e4ede2ae3d059c6c6fc009546a57a44d8621f367e96R50) tu as supprimé le query que tu avais ajouté dans la même PR 🤔

2022-01-12 09:38 UTC, m-maillot approved these changes

2022-01-12 09:53 UTC, merged