fix(frontend): page stats when matomo is down
SocialGouv/code-du-travail-numerique pull request #4193
Opened 2022-01-21 17:07 UTC by maxgfr

fix #4191

2022-01-21 17:11 UTC, maxgfr commented on packages/code-du-travail-api/src/routes/__tests__/stats.test.ts
> +    expect(response.ok).toBe(false);
Je teste bien ça pour être sûr qu'on tombe bien sur le ok a false sur le frontend

2022-01-25 09:24 UTC, m-maillot requested changes
Top le passage en typescript :)

On aurai pu ajouter un test sur le render de la page dans la cas où l'on pas de data avec la testing-library.

Par contre, je ne comprends pas le code 404, pour moi on devrait avoir des erreurs 500.

2022-01-25 09:24 UTC, m-maillot commented on packages/code-du-travail-api/src/routes/stats/index.js
> +    ctx.status = 404;
Pourquoi 404 ? Ici on a un soucis car la page devrait être accessible, elle existe bien. Du coup ce doit retourner une 500 non ? La 404 risque d'induire en erreur l'utilisateur et les moteurs de recherche.

2022-01-25 09:24 UTC, m-maillot commented on packages/code-du-travail-api/src/routes/__tests__/stats.test.ts
> +    expect(response.status).toBe(404);
Je ne m'attends pas à avoir une 404. La route existe bien mais elle a une erreur interne lors de son exécution. 🤔 
Est ce que l'on aurait pas un soucis ici ?

2022-01-25 09:24 UTC, m-maillot commented on packages/code-du-travail-api/src/routes/__tests__/stats.test.ts
> +    expect(response.body).toMatchInlineSnapshot(`Object {}`);
Je crois que ça peut s'écrire comme ça :
`expect(response.body).toBe({});`

je ne vois pas l'intérêt d'avoir un inline snapshot ici.

2022-01-25 14:06 UTC, maxgfr commented on packages/code-du-travail-api/src/routes/stats/index.js
> +    ctx.status = 404;
On est côté API et non frontend. Là, je dis juste que côté API, je ne trouve pas la donnée donc 404 c'est ok pour moi

2022-01-25 14:08 UTC, maxgfr commented on packages/code-du-travail-api/src/routes/__tests__/stats.test.ts
> +    expect(response.body).toMatchInlineSnapshot(`Object {}`);
Oui, j'ai repris le test plus haut

2022-01-26 14:48 UTC, maxgfr commented on packages/code-du-travail-api/src/routes/__tests__/stats.test.ts
> +    expect(response.body).toMatchInlineSnapshot(`Object {}`);
Corrigé !

2022-01-26 14:51 UTC, maxgfr commented on packages/code-du-travail-api/src/routes/__tests__/stats.test.ts
> +    expect(response.status).toBe(404);
Oui, mais c'est l'API et non lié au frontend

2022-01-26 15:10 UTC, maxgfr commented on packages/code-du-travail-api/src/routes/stats/index.js
> +    ctx.status = 404;
On s'est mis d'accord sur 502

2022-01-26 15:11 UTC, m-maillot commented on packages/code-du-travail-api/src/routes/stats/index.js
> +    ctx.status = 404;
Suite à la suggestion de @carolineBda , on part sur une erreur 503

2022-01-26 17:03 UTC, m-maillot approved these changes
:+1:

2022-01-27 09:32 UTC, carolineBda approved these changes
:+1:

2022-01-27 09:32 UTC, carolineBda commented on packages/code-du-travail-api/src/routes/__tests__/stats.test.ts
> +
Top le test !

2022-01-27 09:32 UTC, carolineBda commented on packages/code-du-travail-api/src/routes/stats/index.js
> +        return null;
j'aurais mis dreictement ici :
```    
   ctx.status = 502;
    ctx.body = {};
   return
```

2022-01-27 15:42 UTC, maxgfr commented on packages/code-du-travail-api/src/routes/stats/index.js
> +        return null;
C'est pas possible de faire comme ça avec `koa` car on est dans le `catch`

2022-01-27 15:42 UTC, merged