feat(simulator): add help button + events
SocialGouv/code-du-travail-numerique pull request #4210
Opened 2022-01-25 14:15 UTC by maxgfr

fix #4015

2022-01-26 14:37 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/common/SelectQuestion.tsx
> +      </OnFocus>
ça s'est super important, c'est grâce à ça qu'on perçoit le changement à la première selection. Le onChange est pas explicite, comme ça pourrait l'être dans un `Select`

2022-01-26 14:37 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/common/StepDynamicPublicodes.tsx
> +      trackQuestion(titleQuestion, MatomoActionEvent.RETIREMENT, false);
j'ai mis un boolean au lieu d'un type par défaut, car pour l'instant on a que le select et le help. Si on rajoute un type, dans le futur, il faudra crée un type typescript, ça serait plus élégant, comme le second param de la fonction

2022-01-26 14:37 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/common/PubliQuestion.tsx
> +            trackQuestion(titre, MatomoActionEvent.RETIREMENT);
Le second parametre definit le simulateur dans lequel on est

2022-01-26 14:37 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/common/PubliQuestion.tsx
> +            trackQuestion(titre, MatomoActionEvent.RETIREMENT);
C'est le `view_step`

2022-01-26 14:37 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/HeuresRechercheEmploi/steps/Informations.tsx
> +                );
Cette partie est grave optimisable au sein de tous les simulateurs... Pour l'instant je l'ai laissé comme ça, mais je trouve que tout ces composants se rajoutent pour peu de valeurs ajoutées

2022-01-26 14:37 UTC, maxgfr commented on packages/code-du-travail-data/simulateurs/preavis-demission.data.json
> +      "note": "Le niveau du salarié est habituellement mentionné sur le <strong>bulletin de salaire</strong>."
Je rajoute là la question histoire que ça fasse comme avec publicodes. D'ailleurs sur publicode, ça aurait été cool de centraliser les questions pour éviter d'ajouter une description à chaque fois

2022-01-26 14:37 UTC, maxgfr commented on packages/code-du-travail-frontend/src/lib/matomo/index.ts
> +export * from "./types";
j'ai split en plusieurs fichiers

2022-01-26 14:37 UTC, maxgfr commented on packages/code-du-travail-frontend/src/lib/matomo/question.ts
> +  });
beaucoup plus lisible et simple

2022-01-26 14:37 UTC, maxgfr commented on packages/code-du-travail-frontend/src/lib/matomo/types.ts
> +    synonyms: ["Échelon", "échelon"],
c'est ici que je fais le mapping entre le nom de qui trigger les events et les events

2022-01-26 14:37 UTC, maxgfr commented on packages/code-du-travail-frontend/src/lib/matomo/types.ts
> +    synonyms: ["Échelon", "échelon"],
beaucoup mieux qu'un dictionnaire

2022-01-26 17:11 UTC, m-maillot commented on packages/code-du-travail-data/simulateurs/preavis-demission.data.json
> +      "note": "Le niveau du salarié est habituellement mentionné sur le <strong>bulletin de salaire</strong>."
En effet, on en avait parlé et je pensais que tu l'aurais fait ici 😄

2022-01-26 17:12 UTC, m-maillot commented on packages/code-du-travail-frontend/src/lib/matomo/question.ts
> +  });
La variable `v`n'est pas très explicite ici :/

2022-01-26 17:47 UTC, m-maillot requested changes
J'ai l'impression que l'on va passer à coté de certains events à cause de la casse.
Je ne comprends pas le OnFocus, je me demande si le soucis n'est pas à un autre endroit. Je sais qu'avec publicodes et react-final-form, y a des comportements étranges.

Top la PR et le passage en typescript ! 👍  La partie matomo va me faire galérer avec des conflits :p

2022-01-26 17:47 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/DureePreavisLicenciement/steps/Status.tsx
> +          subLabel="Choisissez parmi les catégories d'ancienneté telles que définies par le Code du travail"
🕵️ 👍

2022-01-26 17:47 UTC, m-maillot commented on packages/code-du-travail-frontend/src/lib/matomo/types.ts
> +  DISMISSAL = "view_step_Préavis de licenciement",
Pas certains que le nommage soit très parlant ici. Pourquoi ne pas utilisé comme en dessous le nom des simulateurs.

```js
PREAVIS_RETRAITE = "/outils/preavis-retraite",
  PREAVIS_DEMISSION = "/outils/preavis-demission",
  PREAVIS_LICENCIEMENT = "/outils/preavis-licenciement",
  INDEMNITE_PRECARITE = "/outils/indemnite-precarite",
  HEURE_RECHERCHE_EMPLOI = "/outils/heures-recherche-emploi",
```

2022-01-26 17:47 UTC, m-maillot commented on packages/code-du-travail-frontend/src/lib/matomo/types.ts
> +type Mapping = Array<{
lint n'a pas ralé pour le Array ? Moi il me dit toujours d'utiliser la syntaxe `[]`

2022-01-26 17:47 UTC, m-maillot commented on packages/code-du-travail-frontend/src/lib/matomo/types.ts
> +  synonyms: Array<string>;
A la place de synonymes, le terme `questionLabels` me semble plus cohérents. Si je ne me trompe, ça sert à matcher sur le label de la question ?

2022-01-26 17:47 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/DureePreavisDemission/steps/Informations.tsx
> +    (state, v) => ({ ...state, [v.name]: v }),
Je pense que le nommage de `v` pourrait être revu pour être plus explicite :)

2022-01-26 17:47 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/HeuresRechercheEmploi/steps/Informations.tsx
> +                );
Assez d'accord, pas mal de duplication de composant ayant le même objectif. Je pense que c'est dans des devs liés au business que l'on devrait en profiter pour refactorer le code et le rendre plus simple. Il faudrait que l'on identifie le besoin de refacto avant le sprint planning et en discuter pour savoir si on l'intègre en même temps ou non. Sinon on ne fera jamais évoluer notre code base "legacy"

2022-01-26 17:47 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/common/PubliQuestion.tsx
> +            trackQuestion(titre, MatomoActionEvent.RETIREMENT);
J'ai justement ajouté une note pour avoir un nommage plus parlant :)

2022-01-26 17:47 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/common/SelectQuestion.tsx
> +      </OnFocus>
Si je prends la doc de `react-final-form-listeners`:

> OnFocus
> Calls its children callback whenever the specified field becomes active. It renders nothing.

https://github.com/final-form/react-final-form-listeners#onfocus

Du coup je ne comprends pas le onChange sur le OnFocus. N'y a t il pas un soucis ailleurs ?

2022-01-26 17:47 UTC, m-maillot commented on packages/code-du-travail-frontend/src/lib/matomo/types.ts
> +    synonyms: ["groupe", "Groupe"],
Est ce qu'il ne faudrait pas le rendre insensible à la casse ? 
Je pense notamment à coefficient qui est en minuscule ici et que l'on retrouve en majuscule `Coefficient` dans la CC industries pharma pour le préavis de retraite. 
Du coup ça ne doit pas fonctionner dans cas ?

2022-01-26 17:47 UTC, m-maillot commented on packages/code-du-travail-frontend/src/lib/matomo/question.ts
> +  });
Après review, la méthode apporte en effet beaucoup de clarté dans cette partie, bien joué :+1:

2022-01-27 08:58 UTC, romain-b13 commented
Quelques retours :

1) Je n'ai pas de help button sur la catégorie pro 

2) comportement étrange : quand je clique sur le help d'une question, que je sélectionne une valeur pour cette question, si la question qui s'affiche en dessous a égalemeent un bouton help celui-ci s'ouvre automatiquement et celui que moi j'avais ouvert sur la question d'avant se ferme. Ex ici, moi j'avais cliqué sur le help uniquement pour la question sur la position du salarié
![image](https://user-images.githubusercontent.com/84397271/151323335-8b53d238-2a59-4a1f-9d99-3ed012bb0424.png)

3) pour les questions :
"quelle est la classe" 
"quelle est la position" 
"quelle est l'ancienneté"
=> il faut ajouter un "e" à "mentionné" 

![image](https://user-images.githubusercontent.com/84397271/151323410-fc13c27f-e11c-4c1c-9b27-783c1a0c9951.png)

![image](https://user-images.githubusercontent.com/84397271/151323540-d7e5a812-0db9-409a-8fab-0f4dbd6a980b.png)

![image](https://user-images.githubusercontent.com/84397271/151323583-e26b71c0-b79e-40de-947c-f16db0a82d2b.png)

4) quand je clique sur le help button d'une question lorsque je sélectionne une réponse pour cette question le message d'aide se ferme

2022-01-27 09:14 UTC, maxgfr commented
Merci pour les retours @romain-b13 et @m-maillot 😉

2022-01-27 09:28 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/DureePreavisDemission/steps/Informations.tsx
> +          tooltip={
est-ce qu'il ne faudrai pas n'ajouter l'attribut tooltip qu si on a questionsMap[key].note plutot que d'ajouter un tooltip avec undefined

2022-01-27 09:28 UTC, carolineBda commented on packages/code-du-travail-frontend/src/lib/matomo/cc.ts
> +      isTracked = !!(idccInfo && idccInfo.preavisRetraite);
c'est pas plutot `isTreated` que `isTracked` ?

2022-01-27 09:28 UTC, carolineBda commented on packages/code-du-travail-frontend/src/lib/matomo/types.ts
> +  DISMISSAL = "view_step_Préavis de licenciement",
je plussoie

2022-01-27 09:28 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/common/SelectQuestion.tsx
> +      </OnFocus>
Oui très bizarre de devoir avoir les 2 ?

2022-01-27 09:29 UTC, carolineBda reviewed
Bravo le code est beaucoup plus clair et facile à utiliser

2022-01-27 10:58 UTC, maxgfr commented on packages/code-du-travail-frontend/src/lib/matomo/types.ts
> +  DISMISSAL = "view_step_Préavis de licenciement",
la question du français ou de l'anglais dans le code est intéressant. je suis d'accord qu'en fr, c'est mieux, mais bon pas très consistant au sein de l'application. après je pense on peut les mettre en français dans les enums et sur le noms des variables en anglais. mais il faudrait qu'on fasse une discussion

2022-01-27 16:04 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/common/SelectQuestion.tsx
> +      </OnFocus>
@m-maillot Effectivement, la fonction ne dispose pas de paramètres. Dans tous les cas, on s'en servait pas au niveau de la `Question`
@carolineBda oui le on focus permet de tracker le premier event, le on change ne s'active que si on change une valeur déjà sélectionnée..... c'est très chelou, j'ai mis grave du temps à comprendre cela

2022-01-27 16:08 UTC, maxgfr commented on packages/code-du-travail-frontend/src/lib/matomo/types.ts
> +type Mapping = Array<{
nop

2022-01-27 16:09 UTC, maxgfr commented on packages/code-du-travail-frontend/src/lib/matomo/types.ts
> +type Mapping = Array<{
moi ça me choque pas, je trouve cela plus explicite, et lisible

2022-01-27 16:09 UTC, maxgfr commented on packages/code-du-travail-frontend/src/lib/matomo/types.ts
> +  synonyms: Array<string>;
ouaip exact

2022-01-27 16:12 UTC, maxgfr commented on packages/code-du-travail-frontend/src/lib/matomo/types.ts
> +    synonyms: ["groupe", "Groupe"],
non en fait, c'est lié à l'id des données issues de `code-du-travail-data`, où les keys sont différentes de celles issues des questions, et c'est pas tellement une pb de case. Le problème vient surtout du fait que les simulateurs sont gérés de manière différente........ Y'en a un où on utilise la position et l'autre l'id de la question, d'où le fait que je preferai gérer manuellement comme ça c'est moi qui gère l'input

2022-01-27 16:28 UTC, maxgfr commented on packages/code-du-travail-frontend/src/lib/matomo/cc.ts
> +      isTracked = !!(idccInfo && idccInfo.preavisRetraite);
c'est pour dire qu'on track l'event de la cc, dans c'est plus `isTracked`

2022-01-27 16:33 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/DureePreavisDemission/steps/Informations.tsx
> +          tooltip={
après ce que je fais plus bas c'est que je le met en undefined donc ça revient à ce que tu dis, sauf que le if je le fais au sein de l'attribut et non au sein de la propriété

c'est un peu comme ça : https://stackoverflow.com/a/48816255/6491071

2022-01-27 16:33 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/DureePreavisDemission/steps/Informations.tsx
> +          tooltip={
c'est pas ouf de mettre les if dans le body des attributs

2022-01-29 10:45 UTC, romain-b13 commented
Dernier retour :
il faudrait mettre un help button pour la question "Quelle est la catégorie professionnelle du salarié ? (obligatoire)"
 avec le message suivant  "La catégorie professionnelle du salarié est habituellement mentionnée sur le bulletin de salaire."

2022-01-31 10:05 UTC, m-maillot commented on packages/code-du-travail-frontend/src/lib/matomo/types.ts
> +    synonyms: ["groupe", "Groupe"],
Le soucis est que l'on a `coefficient ` ligne 96 (https://github.com/SocialGouv/code-du-travail-numerique/pull/4210/files/df8dbc6cb414547537734e19ed15c26c18d0da63#diff-a7fd5b145ab56f48d626ffa1a590f3ab24dba390dd1e5ece43c5bbe61ff4856aR96) en minuscule. Or dans le publicodes de préavis de retraite, on a `Coefficient` avec le C en majuscule. Du coup, pour simplifier, est ce que le fait de le rendre insensible à la casse éviterai ce genre de soucis :

Dans l'outil de simulation de retraite :

 * Choisir départ à la retraite
 * Choisir la CC 292 
 * Choisir la catégorie pro `Collaborateurs`
 * Cliquer sur le bouton help de la question `Quel est le coefficient du salarié ?`
 
 Il n'y a pas d'event matomo envoyer car le coefficient est en majuscule dans publicode alors qu'il est en minuscule dans les synonyms.

2022-01-31 10:17 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/DureePreavisDemission/steps/Informations.tsx
> +          tooltip={
ok :+1:

2022-01-31 10:21 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/DureePreavisDemission/steps/Informations.tsx
> +                  ? isOpenArray.find((v) => v.key === nextQuestionKey)?.status
On peut pas mettre direct
`isOpenArray.find((v) => v.key === nextQuestionKey)?.status`

?
La ça fait 2 fois le find...

2022-01-31 16:22 UTC, carolineBda approved these changes

2022-02-01 09:02 UTC, m-maillot approved these changes

2022-02-01 09:02 UTC, m-maillot commented on packages/code-du-travail-frontend/src/lib/matomo/cc.ts
> +      isTracked = !!(idccInfo && idccInfo.preavisRetraite);
Tu es sûr ?
```
isTracked
      ? MatomoAgreementEvent.CC_TREATED
      : MatomoAgreementEvent.CC_UNTREATED,
```
J'ai l'impression en effet que c'est isTreated également 🤔

2022-02-01 09:02 UTC, m-maillot commented on packages/code-du-travail-frontend/src/lib/matomo/question.ts
> +  // FIXME: send event only for preavis de retraite
Normalement le `FIXME` explique ce que l'on doit fixer. Là on dit qu'il faut envoyer seulement pour le préavis de retraite, c'est ce que l'on fait déjà ici. Pas vraiment utile du coup le commentaire sur le FIXME 😄

2022-02-01 09:02 UTC, m-maillot commented on packages/code-du-travail-frontend/src/lib/matomo/question.ts
> +      mappingElement.questionLabels.includes(trackTitle.toLowerCase())
Comme il n'y a plus qu'un seul champ dans les tableaux, on pourrait passer `questionLabels` en string au lieu d'un tableau.

2022-02-01 09:02 UTC, m-maillot commented on packages/code-du-travail-frontend/src/lib/matomo/question.ts
> +export const trackQuestion = (
Après relecture, je pense que deux fonctions `trackQuestionSelect` et `trackQuestionHelp` auraient été plus parlant dans le code.

2022-02-01 10:55 UTC, merged