fix(events): wrapping same component + optimization with callback
SocialGouv/code-du-travail-numerique pull request #4222
Opened 2022-02-01 16:19 UTC by maxgfr

fix #4228

2022-02-01 16:20 UTC, maxgfr commented on packages/code-du-travail-frontend/src/lib/matomo/question.ts
>      return;
c'est pas ouf mais faut que je trouve une way pour aussi éviter d'écrire le code côté frontend pour verifier que c'est pas null ou undefined

2022-02-03 14:50 UTC, maxgfr commented on packages/code-du-travail-frontend/.babelrc.js
> +    "@babel/preset-typescript",
https://jestjs.io/docs/getting-started#using-typescript

2022-02-03 14:51 UTC, maxgfr commented
Je pense en next step mettre des TU de qualité sur le step information

2022-02-04 10:53 UTC, carolineBda approved these changes
c'était pourquoi déjà cette PR ?

2022-02-04 10:53 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/common/StepInformations.tsx
> +        <div key={index + key}>
:+1:

2022-02-04 10:55 UTC, carolineBda reviewed
en fait on a fait le boulot en double, pour ma carte on avait dit que je passais le Preavis de demission ts  : https://github.com/SocialGouv/code-du-travail-numerique/issues/3659#issuecomment-1022956636

2022-02-04 10:58 UTC, carolineBda requested changes

2022-02-04 10:58 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/common/Wizard.tsx
> +                    <Step form={form} dispatch={dispatch} {...StepProps} />
pourquoi on doit ajouter ça ? On mets pas des params explicite ?
`actionEvent=...`

2022-02-04 10:58 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/common/type/WizardType.ts
> +  componentProps?: { actionEvent: MatomoActionEvent };
pourquoi pas direct `actionEvent: MatomoActionEvent` ?
Pourquoi passer par `componentProps` ?

2022-02-07 11:04 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/common/type/WizardType.ts
> +  componentProps?: { actionEvent: MatomoActionEvent };
Je voulais créer un paramètre générique dans le cas d'une extensibilité du feature, en gros, je voulais vraiment dire que cela s'ajoute au component du haut que de créer des énièmes paramètre dont on sait pas à quel élément cela correspond, au moins là tout est au même endroit

2022-02-07 11:06 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/common/Wizard.tsx
> +                    <Step form={form} dispatch={dispatch} {...StepProps} />
Du fait que les propriétés sont optionnelles, et que `componentProps` (voir commentaire plus bas) soit un élément poussé à l'extensibilité, j'ai préféré utilisé un spread operator pour passer les éléments issues de ces props. Après nous sommes, en TS, et tout est typé, donc on peut facilement retrouvé les propriétés qui lui sont attachés

2022-02-07 15:39 UTC, carolineBda approved these changes
Est-ce qu'on fait tester à Romain ?

2022-02-08 09:37 UTC, maxgfr commented
@carolineBda bah en soit, je sais pas trop s'il pourra tester au niveau des events... concernant les simulateurs, j'ai quand même tester pour voir que je ne pétais rien

2022-02-24 07:56 UTC, m-maillot approved these changes
Ok pour moi :)

2022-02-24 07:56 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/common/StepInformations.tsx
> +      case MatomoActionEvent.HEURE_RECHERCHE_EMPLOI:
Je ne suis pas fan d'utiliser un enum dédié aux events pour matomo pour de la logique métier. Il aurait été plus sage d'avoir un enum dédié pour chaque simu.

2022-02-28 15:17 UTC, merged