fix(deps): upgrade next to v12 WIP
SocialGouv/code-du-travail-numerique pull request #4280
Opened 2022-03-03 16:20 UTC by maxgfr

fix #4044

2022-03-03 18:41 UTC, maxgfr commented on packages/code-du-travail-frontend/src/common/ErrorBoundary.js
> +  // };
ça bugguait si je faisais pas ça, c'est bizarre

2022-03-03 18:41 UTC, maxgfr commented on packages/code-du-travail-frontend/src/constants.ts
> +  },
c'est pour le `redirect.json` du serveur

2022-03-03 18:41 UTC, maxgfr commented on packages/code-du-travail-frontend/src/lib/url.ts
> +            }
pour switcher de path

2022-03-03 18:41 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/common/__tests__/situations.utils.test.js
> +]);
j'étais obligé de faire ça car ccnList n'est pas instancié, c'est bizarrrrree

2022-03-03 18:41 UTC, maxgfr commented on packages/code-du-travail-frontend/src/search/SearchBar/DocumentSuggester.js
> +  // };
la aussi bizarre

2022-03-03 18:41 UTC, maxgfr commented on packages/code-du-travail-frontend/src/constants.ts
> +    newPath: "information",
c'est ça la `newPath`

2022-03-03 18:41 UTC, maxgfr commented on packages/code-du-travail-frontend/pages/_document.jsx
> +          <Script key="smarttag" src="/static/smarttag.js" />
next n'aime pas avoir ça là, mais j'ai hacké le truc

2022-03-03 18:41 UTC, maxgfr commented on packages/code-du-travail-frontend/pages/_document.jsx
> +          <Script key="smarttag" src="/static/smarttag.js" />
il faudrait l'avoir sur les pages

2022-03-03 18:41 UTC, maxgfr commented on packages/code-du-travail-frontend/pages/_document.jsx
> +          <Script key="smarttag" src="/static/smarttag.js" />
mais pas dans le document

2022-03-03 18:41 UTC, maxgfr commented on .eslintrc.yml
> -root: true
ça faisait bugguer le nouveau linter de next

2022-03-03 18:41 UTC, maxgfr commented on .eslintrc.yml
> -root: true
et j'ai pas vu de changement sur les autres repos

2022-03-03 18:41 UTC, maxgfr commented on .eslintignore
> -packages/code-du-travail-frontend/public/static
je vois pas l'utilité hmm

2022-03-03 18:41 UTC, maxgfr commented on .yarnclean
> -images
ça faisait bugguer le nouveau compiler

2022-03-03 18:42 UTC, maxgfr commented
TODO: il faut gérer le `robots.txt`

2022-03-07 16:26 UTC, maxgfr commented on packages/code-du-travail-frontend/package.json
> +    "prebuild": "node -r @swc-node/register scripts/prebuild.ts",
c'est plus rapide que ts-node

2022-03-07 16:31 UTC, maxgfr commented on packages/code-du-travail-frontend/.gitignore
> +robots.txt
en gros le prebuild, genere le robots.txt, il faudrait que je vois que si le dockerfile nous permet de generer le bon robots.txt au niveau de la prod et de la preview

2022-03-07 16:31 UTC, maxgfr commented on packages/code-du-travail-frontend/next.config.js
> +const csp = {
c'est ici les csp

2022-03-07 16:31 UTC, maxgfr commented on packages/code-du-travail-frontend/next.config.js
> +      },
pour garder le endpoint health qui renvoie un json ok

2022-03-07 16:31 UTC, maxgfr commented on packages/code-du-travail-frontend/pages/404.jsx
> +        <Metas title="Page non trouvée" description="Page 404" />
une description qui manqué au niveau de la page 404 et qui m'a été souligné, du coup j'ai mis ça mais on peut mettre une chaine de caractère vide

2022-03-07 16:31 UTC, maxgfr commented on packages/code-du-travail-frontend/scripts/prebuild.ts
> +export const generateRobotsTxt = (isOnProduction: boolean, host: string) => {
j'exporte pour tester de manière unitaire

2022-03-07 16:31 UTC, maxgfr commented on packages/code-du-travail-frontend/src/lib/__tests__/url.test.ts
> +    ${"https://code.travail.gouv.fr/dossiers/ministere-du-travail-notre-dossier-sur-le-coronavirus/ce-que-changent-les-ordonnances-en-droit-du-travail"} | ${"https://code.travail.gouv.fr/dossiers/min
les deux nouveaux tu pour le merge du `redirect.json` du serveur et de notre approche locale

2022-03-07 16:41 UTC, maxgfr commented on packages/code-du-travail-frontend/src/common/ErrorBoundary.js
> +  // };
je vais les réecrire, en sortant les proptypes du composant

2022-03-07 17:05 UTC, maxgfr commented on packages/code-du-travail-frontend/next.config.js
> +                : "all",
pour ne pas indexer le robots.txt

j'ai essayé de l'écrire comme cela: 
```tsx
...(process.env.NEXT_PUBLIC_IS_PRODUCTION_DEPLOYMENT !== "true" && {
  key: "x-robots-tag",
  value: "noindex, nofollow, nosnippet",
}),
```

mais cela n'a pas fonctionné, je l'ai mais en all pour la prod d'après la doc : 

https://developers.google.com/search/docs/advanced/robots/robots_meta_tag

2022-03-07 17:06 UTC, maxgfr commented
TODO: à tester les robots.txt en changeant les variables

2022-03-10 10:28 UTC, maxgfr commented on packages/code-du-travail-frontend/scripts/prebuild.ts
> +export const generateRobotsTxt = (isOnProduction: boolean, host: string) => {
c'est fait

2022-03-10 11:04 UTC, carolineBda approved these changes
Vraiment bien joué, bravo pour cette PR !

2022-03-10 11:04 UTC, carolineBda commented on packages/code-du-travail-frontend/next.config.js
> +            key: "X-Robots-Tag",
A verifier en prod

2022-03-10 11:04 UTC, carolineBda commented on packages/code-du-travail-frontend/next.config.js
> +const ContentSecurityPolicy = `
A vérifier en prod

2022-03-10 11:04 UTC, carolineBda commented on packages/code-du-travail-frontend/pages/404.jsx
> +        <Metas
:+1:

2022-03-10 11:04 UTC, carolineBda commented on packages/code-du-travail-frontend/pages/api/simulateurs/index.ts
> -        process.env.NEXT_PUBLIC_IS_PRODUCTION_DEPLOYMENT !== "true"
je penses que tu t'es trompé ici

2022-03-10 11:04 UTC, carolineBda commented on packages/code-du-travail-frontend/server/redirects.json
> -    "code": 303,
je sais pas pourquoi ici on avant un 303. Chelou

2022-03-10 11:04 UTC, carolineBda commented on packages/code-du-travail-frontend/src/lib/__tests__/url.test.ts
> +    ${"https://code.travail.gouv.fr/dossiers/ministere-du-travail-notre-dossier-sur-le-coronavirus/ce-que-changent-les-ordonnances-en-droit-du-travail"} | ${"https://code.travail.gouv.fr/dossiers/min
les 2 urls n'existent plus... donc y'avait pas besoin de les bouger en fait

2022-03-10 11:04 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/common/__tests__/situations.utils.test.js
> +]);
chelou

2022-03-10 11:11 UTC, carolineBda commented on packages/code-du-travail-frontend/next.config.js
> +const csp = {
quand tu test en local, tu peux regarder si t'ajoute une image depuis une url externe qu'elle est bien bloquée stp ?

2022-03-10 16:07 UTC, m-maillot approved these changes
:+1:

2022-03-10 16:07 UTC, m-maillot commented on packages/code-du-travail-frontend/scripts/__tests__/prebuild.test.ts
> +describe("robots.txt", () => {
😍😍😍

2022-03-10 16:07 UTC, m-maillot commented on packages/code-du-travail-frontend/scripts/__tests__/prebuild.test.ts
> +    expect(fs.writeFileSync).toHaveBeenCalledWith(filePath, robotsProd);
ça serait bien de vérifier le filepath, pour éviter de le changer et qu'il se retrouve au mauvais endroit :)

2022-03-10 16:07 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/common/__tests__/situations.utils.test.js
> +]);
Le problème est que l'on importe `import data from "@cdt/data...prime-precarite/precarite.data.json";` puis derrière, on fait un `jest.mock("@cdt/data...prime-precarite/precarite.data.json"`. Par contre, à part split le fichier en 2, je n'ai pas de solution...

2022-03-11 08:26 UTC, carolineBda commented on packages/code-du-travail-frontend/next.config.js
> +prefetch-src 'self' *.fabrique.social.gouv.fr;
on avait pas ça avant si ?
https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-frontend/server/koaServer.js#L29

2022-03-11 08:30 UTC, maxgfr commented on packages/code-du-travail-frontend/next.config.js
> +prefetch-src 'self' *.fabrique.social.gouv.fr;
je l'ai rajouté le prefetch en pensant que ça reglerait, c'est un test

2022-03-11 08:39 UTC, maxgfr commented on packages/code-du-travail-frontend/next.config.js
> +prefetch-src 'self' *.fabrique.social.gouv.fr;
et effectivement c'est ce qu'il fallait rajouter

2022-03-11 09:32 UTC, carolineBda commented on packages/code-du-travail-frontend/next.config.js
> +prefetch-src 'self' *.fabrique.social.gouv.fr;
ça fix un warning qu'on voyant dans la console c'est ça ?

2022-03-18 14:18 UTC, carolineBda commented on packages/code-du-travail-frontend/next.config.js
> +  process.env.AZURE_BASE_URL
cette var est undefined :
voila le header qu'on a :
`img-src 'self' data: *.fabrique.social.gouv.fr https://travail-emploi.gouv.fr https://mon-entreprise.urssaf.fr undefined;`

2022-03-18 14:39 UTC, maxgfr commented on packages/code-du-travail-frontend/next.config.js
> +  process.env.AZURE_BASE_URL
Ahhh en effet, quand c'est non defini on met undefined, il faudrait faire 

```suggestion
img-src 'self' data: *.fabrique.social.gouv.fr https://travail-emploi.gouv.fr/ https://mon-entreprise.urssaf.fr/ ${
  process.env.AZURE_BASE_URL ?? ""}
```

2022-03-18 16:01 UTC, carolineBda commented on packages/code-du-travail-frontend/next.config.js
> +  process.env.AZURE_BASE_URL ?? ""
non c'est bon il faut que cette var fonctionne

2022-03-18 16:01 UTC, carolineBda requested changes
fix process.env.AZURE_BASE_URL

2022-03-21 09:47 UTC, carolineBda approved these changes
:+1: :+1: :+1:

2022-03-22 10:06 UTC, merged