Update courriers.json
SocialGouv/code-du-travail-numerique pull request #431
Opened 2019-01-16 16:12 UTC by jrduscher

update des thèmes dans le json  qui doivent régler #429

2019-01-17 12:40 UTC, douglasduteil requested changes

2019-01-17 12:40 UTC, douglasduteil commented on packages/code-du-travail-data/dataset/courrier-type/courriers.json
> +      "theme": "harcèlement,
Missing double quote.

2019-01-28 12:01 UTC, jrduscher commented
douglas,

could you look at the changes i made last week. Why this PR is still blocked? thx

2019-01-28 12:57 UTC, lionelB commented
@jrduscher  je m'en occupe, il faut que je mette à jour le docx et regénère les documents

2019-01-28 16:16 UTC, douglasduteil approved these changes

2019-01-28 16:18 UTC, merged