feat(simulator): precise date to the result
SocialGouv/code-du-travail-numerique pull request #4368
Opened 2022-04-06 16:57 UTC by maxgfr

fix #4283

2022-04-07 15:32 UTC, maxgfr commented on packages/code-du-travail-frontend/src/lib/date.ts
> +export const convertPeriodToHumanDate = (
dîtes moi si vous avez des idées pour simplifier cette fonction, je vous invite a lire les TU avant #tdd

2022-04-11 09:01 UTC, carolineBda requested changes
c'est top ! mes retours sont juste de l'optim mais ça pourrait aller en prod comme ça :+1:

2022-04-11 09:01 UTC, carolineBda commented on packages/code-du-travail-frontend/src/lib/__tests__/date.test.ts
> +describe("convertPeriodToHumanDate", () => {
:heart_eyes:

2022-04-11 09:01 UTC, carolineBda commented on packages/code-du-travail-frontend/src/lib/date.ts
> +  MappingUnit.forEach((v) => {
```suggestion
  const unit: Unit | undefined = MappingUnit.find((v) => {
```

2022-04-11 09:01 UTC, carolineBda commented on packages/code-du-travail-frontend/src/lib/date.ts
> +    if (v.label.includes(secondElement)) {
```suggestion
   return v.label.includes(secondElement)
```

2022-04-11 09:01 UTC, carolineBda commented on packages/code-du-travail-frontend/src/lib/date.ts
> +  if (extra === Extra.OPEN) {
vu qu'on gère des cas spéciaux que pour 2 extra, on peut ne pas faire le forEach et faire direct :
```
if (MappingExtra.MID.label.includes(otherElements)) {
...
else if ...
```

2022-04-11 09:01 UTC, carolineBda commented on packages/code-du-travail-frontend/src/lib/date.ts
> +const countWeekendDays = (startDate: Date, endDate: Date): number => {
sur le front on a la library : https://date-fns.org/

je penses qu'elle peut faire ça pour nous.

Par exemple on fait un peu pareil ici :
https://github.com/SocialGouv/code-du-travail-numerique/blob/dev/packages/code-du-travail-frontend/src/outils/IndemniteLicenciement/steps/Salaires.js#L127

2022-04-11 09:01 UTC, carolineBda commented on packages/code-du-travail-frontend/src/lib/date.ts
> +const addDay = (date: Date, day: number): Date => {
idem

2022-04-11 09:01 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/common/PrecisionResult.tsx
> +  switch (simulator) {
je vois pas trop l'intéret d'avoir mis dans un meme composant pour ensuite refaire un switch. Ce qui est important c'est que la logique soit dans une methode commune à tous non ?

2022-04-11 09:01 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/common/PrecisionResult.tsx
> +const FROM_DATE = new Date("2022-04-22");
on hardcode cette date ? Il faudra pas faire un truc relatif à aujourd'hui ? ou au moins que l'année soit l'année courante ?

2022-04-11 09:01 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/common/PrecisionResult.tsx
> +const StyledSmallText = styled(SmallText)`
on peut mettre ça dans stepStyles.js

2022-04-12 09:30 UTC, m-maillot commented on packages/code-du-travail-frontend/src/lib/date.ts
> +const countWeekendDays = (startDate: Date, endDate: Date): number => {
On peut même la retirer car non utilisé.

2022-04-12 09:56 UTC, m-maillot requested changes
Je ne suis pas trop fan de la complexité du code pour le résultat attendu.

Je pense que le problème est lié au fait que le code gère dynamiquement les dates, or on ne veut pas les gérer dynamiquement, elles sont statiques comme dans les exemples founis dans le document word.

Je crois que l'on devrait revoir notre copie sur ce dev pour le simplifier.
Dans le fichier json, on a l'answer 3 qui contient la durée en jours. Ce qui nous permet de faire le calcul 22 avril + X jours sans devoir extraire le nombre de jour d'un string.

Pour les cas spécifiques `jours ouvrés` et `jours calendaires` : on peut détecter la précense des mots clés ouvré/calendaire pour afficher le détail personnalisé.

De mon point de vu, une fonction qui prend en entrée le nombre de jours + le résultat en string et qui retourne la phrase personnalisée est suffisant. On peut en effet garder la logique de calculer le dernier jour via une fonction date en se basant sur le 22 avril 2022 pour éviter un if selon le nombre de jour.

Pour info, voici les différents résultats que l'on a dans le json : 
```
Démission

[
  "Le code du travail ne prévoit pas une durée précise du préavis de Démission. Il prévoit qu'un texte du niveau légal conventionnel, un accord d'entreprise voire un usage en prévoit les durées et modalités. ",
  "1 mois",
  "3 mois",
  "2 semaines",
  "1 semaine",
  "2 mois",
  "15 jours",
  "3 mois (si les salariés bénéficient pas des dispositions de l'article 4 de la convention collective nationale de retraite et de prévoyance des cadres du 14/3/1947 )",
  "4 mois (si les salariés bénéficient pas des dispositions de l'article 4 de la convention collective nationale de retraite et de prévoyance des cadres du 14/3/1947 )",
  null,
  "8 jours",
  "1 jour ouvré",
  "2 jours ouvrés",
  "7 jours calendaires",
  "14 jours calendaires",
  "2 jours",
  "8 jours calendaires",
  "15 jours calendaires",
  "Pour les salariés hors classification, la durée du préavis est fixée par le contrat de travail dans la limite de 3 mois",
  "6 mois",
  "1 semaine (de date à date)",
  "1 mois (de date à date)",
  "2 mois (de date à date)",
  "4 mois (de date à date)"
]


Licenciement:

[
  "1 mois",
  "2 mois",
  "Pas de préavis",
  "La convention collective ne prévoit pas de préavis pour ce cas de figure",
  "3 mois",
  "1 semaine",
  "4 mois",
  "6 mois",
  "2 semaines",
  "3 mois (si les salariés ne bénéficient pas des dispositions de l'article 4 de la convention collective nationale de retraite et de prévoyance des cadres du 14/3/1947)",
  "4 mois (si les salariés bénéficient  des dispositions de l'article 4 de la convention collective nationale de retraite et de prévoyance des cadres du 14/3/1947)",
  "15 jours",
  "1 mois et demi",
  "3 mois (sauf stipulation contractuelle différente)",
  "8 jours",
  "1 jour ouvré",
  "2 jours ouvrés",
  "7 jours calendaires",
  "14 jours calendaires",
  "la convention collective ne prévoit pas de préavis pour ce cas de figure",
  "2 jours",
  "pour les salariés hors classification, la durée du préavis est fixée par le contrat de travail dans la limite de 3 mois",
  "8 jours calendaires",
  "15 jours calendaires",
  "1 semaine (de date à date)",
  "1 mois (de date à date)",
  "2 mois (de date à date)",
  "4 mois (de date à date)"
]
```

2022-04-12 10:46 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/common/PrecisionResult.tsx
> +const StyledSmallText = styled(SmallText)`
Excellent idées ! Je suis assez fan de regrouper les composants visuel dans un même fichier 🔥

2022-04-12 10:47 UTC, maxgfr commented on packages/code-du-travail-frontend/src/lib/date.ts
> +const countWeekendDays = (startDate: Date, endDate: Date): number => {
Oui, on l'utilisait auparavant au niveau des jours ouvrés. La fonctionnalité a été retirée

2022-04-13 13:50 UTC, m-maillot approved these changes
Top ! :) j'ai eu encore quelques idées pour simplifier le code que j'ai mis en suggestions

2022-04-13 13:50 UTC, m-maillot commented on packages/code-du-travail-frontend/src/lib/date.ts
> +};
```suggestion
export const addWeek = (date: Date, week: number): Date => addDay(date, week * 7);
```

2022-04-13 13:50 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/common/NoticeExample.tsx
> +  const resultFound = React.useMemo(
petite suggestion sur le naming pour le ne pas confondre avec le resultat du simulateur. 

```suggestion
  const lastDayExample = React.useMemo(
```

2022-04-13 13:50 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/common/NoticeExample.tsx
> +      return <></>;
Ce n'est pas grand chose mais en terme de perf, retourner null est plus efficient qu'un fragment vide.

2022-04-13 13:50 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/utils/calculateNumberOfElements.ts
> +};
```suggestion
export const calculateNumberOfElements = (...args: [unknown]): number => args.filter(item => item !== null && item !== undefined).length;
```

2022-04-13 13:50 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/utils/extractDates.ts
> +export const convertPeriodToHumanDate = (
```suggestion
export const getLastDay = (
```

2022-04-13 13:50 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/utils/extractDates.ts
> +  let firstElement = parseInt(splitString[0]);
Vraiment étrange le `parseInt`, un `parseInt("2a2")` va retourner `22` 😵‍💫

2022-04-13 13:50 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/utils/extractDates.ts
> +};
On ne peut pas juste valider que l'input contient le mot clé de l'extra ?

```suggestion
const extractExtra = (input: string): Extra | null => {
  for (var extra of Object.values(Extra)) {
    if (input.includes(extra)) {
      return extra;
    }
  }
  return null;
};
```

2022-04-13 13:50 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/utils/extractDates.ts
> +};
Idem ici, on n'a pas besoin de split 
```suggestion
export const extractUnit = (input: string): Unit | null => {
  for (var unit of Object.values(Unit)) {
    if (input.includes(unit)) {
      return unit;
    }
  }
  return null;
};
```

2022-04-13 13:50 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/common/NoticeNote.tsx
> +              ))}
je vais la garder en tête quand je dois créer des listes en JS :)

2022-04-13 15:50 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/utils/extractDates.ts
> +export const convertPeriodToHumanDate = (
je trouve ça plus parlant perso

2022-04-13 15:52 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/utils/calculateNumberOfElements.ts
> +};
Merci 😄

2022-04-13 15:53 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/common/NoticeExample.tsx
> +      return <></>;
T'es sûr ?

2022-04-13 15:54 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/common/NoticeExample.tsx
> +      return <></>;
Je pense que ça revient au même, sinon je suis pas forcément d'accord avec toi, c'est plus simple de renvoyer un fragment, car on reste sur du jsx. Après tu devras gérer les cas où ton composant est null et écrire encore plus de code

2022-04-13 15:55 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/common/NoticeExample.tsx
> +  const resultFound = React.useMemo(
je l'ai renommé en period, pour moi, c'est plus une période qu'un dernier jour

2022-04-13 15:56 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/utils/extractDates.ts
> +  let firstElement = parseInt(splitString[0]);
On peut passer par le constructor Number, au moins ça met en undefined ^^

2022-04-13 15:58 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/utils/extractDates.ts
> +};
C'est beaucoup mieux, thanks !

2022-04-14 07:37 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/common/NoticeExample.tsx
> +      return <></>;
Niveau clarté je préfère le fragment, niveau perf c'est un null. Mais je préfère comme c'est également :)

2022-04-14 13:44 UTC, carolineBda approved these changes

2022-04-14 13:44 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/common/__tests__/NoticeExample.test.tsx
> +      expect(() => getByText(/Exemple/)).toThrow("Unable to find an element");
```suggestion
      expect(queryByText(/Exemple/)).toBeNull();
```

2022-06-01 14:25 UTC, merged