Update faq.json
SocialGouv/code-du-travail-numerique pull request #438
Opened 2019-01-17 12:47 UTC by jrduscher

suppression des références à  des tests ou des soucis de validité dans le texte. il peut encore en rester... :\

2019-01-17 16:48 UTC, douglasduteil requested changes

2019-01-17 16:48 UTC, douglasduteil commented on packages/code-du-travail-data/dataset/faq.json
> +      "branche": "";
You can't use `;` here. 
You should use `,`

2019-01-17 16:48 UTC, douglasduteil commented on packages/code-du-travail-data/dataset/faq.json
> +      "commentaire": "contenu équipe projet";
You can't use `;` here. 
You should use `` as it's the last one

2019-01-17 16:48 UTC, douglasduteil commented on packages/code-du-travail-data/dataset/faq.json
> +    "reponse": "La question fait encore l'obje de débats, et l'une des pistes de réponse à l'étude est la suivante: L’APC est un accord de droit commun s’agissant des règles relatives à sa durée : il
Strange `’`...
Should be a `'` I think

2019-01-17 16:48 UTC, douglasduteil commented on packages/code-du-travail-data/dataset/faq.json
> +    "reponse": "<p>Les conditions de validité de l’accord de performance collective sont identiques à celles de tout accord collectif d’entreprise : en présence d’un délégué syndical, il doit être si
Strange `’`...
Should be a `'` I think

2019-01-28 17:06 UTC, jrduscher commented
le fichier dans sa dernière version passe dans jsonlint.

2019-01-29 09:59 UTC, lionelB approved these changes
merci !

2019-01-29 11:35 UTC, douglasduteil approved these changes
You work @lionelB :+1:

2019-01-29 11:39 UTC, merged