feat(indemnite-licenciement): ajout des primes dans l'input de salaires
SocialGouv/code-du-travail-numerique pull request #4451
Opened 2022-06-27 14:53 UTC by maxgfr

2022-06-30 09:10 UTC, m-maillot requested changes
Top la nouvelle implémentation ! 🚀 

Par contre j'ai découvert un bug sur le calcul du salaire de ref.

2022-06-30 09:10 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/IndemniteLicenciement/common/usecase/computeReferenceSalary.ts
> +  const salaryValues = salaires.map((a) => a.value).filter(Boolean);
Attention ! Si un salaire est à 0 (car il était en congés sabbatique par exemple), tu vas le retirer de la liste à tord car ensuite on fait l'opération : `sum(salaryValues) / salaires.length`

Exemple avec 3 salaires : 
 * 1000
 * 0
 * 1000
 
la moyenne doit être : 1000 + 0 + 1000 / 3 => 666 (😈 )
Or avec le filtre, on retire le 0 est on va faire 1000 + 1000 / 2 => 1000

2022-06-30 09:15 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/IndemniteLicenciement/common/usecase/computeReferenceSalary.ts
> +  const salaryValues = salaires.map((a) => a.value).filter(Boolean);
Yes, je rajoute un TU, merci ;)

2022-06-30 14:45 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/IndemniteLicenciement/common/usecase/computeReferenceSalary.ts
> +  const salaryValues = salaires.map((a) => a.value).filter(Boolean);
Concernant le bug, il est déjà corrigé sur l'autre branche, du coup, au prochain merge dans la branche feature, normalement ça serait bon

2022-07-04 10:51 UTC, m-maillot approved these changes
:fire:

2022-07-04 12:30 UTC, ViCode approved these changes

2022-07-04 12:36 UTC, merged