fix(1090): rename "congé parental d'éducation totale" to "congé parental d'éducation à temps plein"
SocialGouv/code-du-travail-numerique pull request #4878
Opened 2023-01-11 15:13 UTC by carolineBda

Fix [#4867](https://github.com/SocialGouv/code-du-travail-numerique/issues/4867)

2023-01-12 13:30 UTC, m-maillot approved these changes

2023-01-12 13:45 UTC, m-maillot requested changes
Je viens de voir qu'il y a aussi l'enum MotifKeys qui contient congesParentalEducationTotal à renommer aussi.

2023-01-12 14:10 UTC, carolineBda commented
> Je viens de voir qu'il y a aussi l'enum MotifKeys qui contient congesParentalEducationTotal à renommer aussi.

Ah oui bien vue !

2023-01-13 08:16 UTC, m-maillot approved these changes

2023-01-13 08:16 UTC, merged