feat(indemnite-licenciement): ajout de la cc 675
SocialGouv/code-du-travail-numerique pull request #4980
Opened 2023-03-02 08:04 UTC by maxgfr

fix https://github.com/SocialGouv/code-du-travail-numerique/issues/4471

2023-03-06 09:41 UTC, m-maillot requested changes
Il faut bien penser à ajouter la CC au tableau des CC pas prête pour la prod.

J'ai un doute sur l'utilisation de l'ancienneté requise pour détecter la tranche. Faut que l'on valide avec le métier.

2023-03-06 09:41 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/675_habillement_commerce_succursales/indemnite-licenciement.yaml
> +contrat salarié . convention collective . habillement commerce succursales . indemnité de licenciement . catégorie:
Dans toutes les CCs, on utilise le terme ` catégorie professionnelle` dans le namespace. Je pense que ça peut être bien de garder une cohérence à ce niveau.

2023-03-06 09:41 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/675_habillement_commerce_succursales/indemnite-licenciement.yaml
> +      - contrat salarié . indemnité de licenciement . ancienneté conventionnelle requise en année <= 15 ans
Faut qu'on valide ce point avec le métier, mais pour mois l'ancienneté conventionnelle requise est utilisée pour savoir si tu as le droit à l'indémnité. Pour les tranches de calcul, on va utiliser l'ancienneté conventionnelle.

2023-03-06 09:41 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/675_habillement_commerce_succursales/salary.ts
> +  computeExtraInfo({
:+1:

2023-03-06 09:41 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/common/supported-agreements.ts
> +  IDCC0675 = "675",
Il faut aussi l'ajouter dans le tableau `productionNotReady` dans le fichier `IndemniteLicenciement/common/usecase/getSupportedCC.ts` (je me dis qu'il est pas au meilleur endoit peut être :D )

2023-03-08 09:43 UTC, Viczei approved these changes

2023-03-08 09:52 UTC, maxgfr commented on packages/code-du-travail-modeles/src/modeles/conventions/675_habillement_commerce_succursales/indemnite-licenciement.yaml
> +      - contrat salarié . indemnité de licenciement . ancienneté conventionnelle requise en année <= 15 ans
Dans tous les cas, il me semble qu'on doit fallback sur le legal, et par défaut ce sont les messages du légal qui sont affichés à l'utilisateur final

2023-03-08 09:55 UTC, maxgfr commented on packages/code-du-travail-modeles/src/modeles/common/supported-agreements.ts
> +  IDCC0675 = "675",
Yes je fais ça, et je partage le même avis. J'ai fait cette remarque aussi sur la PR de Victor

2023-03-08 09:56 UTC, maxgfr commented on packages/code-du-travail-modeles/src/modeles/conventions/675_habillement_commerce_succursales/indemnite-licenciement.yaml
> +contrat salarié . convention collective . habillement commerce succursales . indemnité de licenciement . catégorie:
Oui 😂

2023-03-10 16:25 UTC, maxgfr commented on packages/code-du-travail-modeles/src/modeles/conventions/675_habillement_commerce_succursales/indemnite-licenciement.yaml
> +      - contrat salarié . indemnité de licenciement . ancienneté conventionnelle requise en année <= 15 ans
En effet, il faudra modifier cela suite aux retours métiers

2023-03-16 16:38 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/IndemniteLicenciement/common/usecase/getSupportedCc.ts
> +
```suggestion

```

Erreur au merge 🙈

2023-03-16 16:38 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/675_habillement_commerce_succursales/__tests__/indemnite-licenciement/indemnite.spec.ts
> +      category                  | isCollectifFiring | seniority | salary  | expectedCompensation
Ce serait bien d'avoir la seniority (ancienneté pour le calcul) et la seniority (ancienneté pour le droit) dans les tests. L'idée est de placer l'ancienneté pour le droit toujours au minimum (ici > 1 an) pour voir qu'il n'y a pas d'impact sur le calcul.

2023-03-28 08:49 UTC, m-maillot approved these changes
:fire:

2023-03-28 08:50 UTC, merged