feat: implement cc 1505
SocialGouv/code-du-travail-numerique pull request #4994
Opened 2023-03-07 15:03 UTC by Viczei

2023-03-08 09:49 UTC, maxgfr requested changes, later dismissed
Il faut ajouter la CC à `productionNotReady` aussi

const productionNotReady: number[] = [
  1516, 1517, 1702, 2098, 2511, 2609, 787, 843, 1996, 1505
];

2023-03-08 09:49 UTC, maxgfr commented on packages/code-du-travail-modeles/src/modeles/conventions/1505_commerces_detail_fruits_legumes/__tests__/indemnite-licenciement/anciennete.spec.ts
> +  `(
c'est vrai que moi j'ai pour habitude de rajouter plus de TUs ici

histoire de bien tout tester

2023-03-08 09:49 UTC, maxgfr commented on packages/code-du-travail-modeles/src/modeles/conventions/1505_commerces_detail_fruits_legumes/__tests__/indemnite-licenciement/formule.spec.ts
> +      ${18}     | ${"(1/4 * Sref * A1) + (1/3 * Sref * A2)"} | ${["A1 : Ancienneté de 10 ans ou moins (10 ans)", "A2 : Ancienneté au-delà de 10 ans (8 ans)", "Sref : Salaire de référence (2800 €)"]}
là aussi, je trouve ça assez lite, j'ai l'habitude de prendre tous les tests effectuées via `indemnite.spec.ts`

2023-03-08 09:49 UTC, maxgfr commented on packages/code-du-travail-modeles/src/modeles/conventions/1505_commerces_detail_fruits_legumes/__tests__/indemnite-licenciement/formule.spec.ts
> +      ${18}     | ${"(1/4 * Sref * A1) + (1/3 * Sref * A2)"} | ${["A1 : Ancienneté de 10 ans ou moins (10 ans)", "A2 : Ancienneté au-delà de 10 ans (8 ans)", "Sref : Salaire de référence (2800 €)"]}
le but c'est d'être sûr que tout est bien couvert, quitte à dupliquer le test

2023-03-08 09:49 UTC, maxgfr commented on packages/code-du-travail-modeles/src/modeles/conventions/1505_commerces_detail_fruits_legumes/__tests__/indemnite-licenciement/indemnite.spec.ts
> +      ${20}     | ${15166.67}
👌

2023-03-08 09:49 UTC, maxgfr commented on packages/code-du-travail-modeles/src/modeles/conventions/1505_commerces_detail_fruits_legumes/indemnite-licenciement.yaml
> +      formula: (1/4 * Sref * A1) + (1/3 * Sref * A2)
il me semble qu'on peut utiliser directement les règles situées dans `common.yaml` pour éviter de réecrire celle du légal

2023-03-08 09:51 UTC, maxgfr commented
D'ailleurs pour le productionNotReady, il faudrait voir si on peut pas le mettre autre part, car en effet, il est pas si accessible que ça et on y pense peut etre pas assez

2023-03-08 13:54 UTC, Viczei commented on packages/code-du-travail-modeles/src/modeles/conventions/1505_commerces_detail_fruits_legumes/__tests__/indemnite-licenciement/formule.spec.ts
> +      ${18}     | ${"(1/4 * Sref * A1) + (1/3 * Sref * A2)"} | ${["A1 : Ancienneté de 10 ans ou moins (10 ans)", "A2 : Ancienneté au-delà de 10 ans (8 ans)", "Sref : Salaire de référence (2800 €)"]}
Personnellement je pense pas qu'il faut faire du test pour faire du test mais qu'il faut un test pour chaque cas que l'on veut tester. Ici j'ai un test avec une ancienneté < 10 ans et une autre > 10 parce que la formule s'affiche différemment pour le s 2. La formule n'a pas d'autres cas donc je ne pense qu'il soit intéressant de rajouter plein d'autres tests couteux qui vont juste retesté ce qui est déjà testé ici

2023-03-09 08:21 UTC, m-maillot approved these changes
🚀

2023-03-09 08:21 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/1505_commerces_detail_fruits_legumes/__tests__/indemnite-licenciement/formule.spec.ts
> +      ${18}     | ${"(1/4 * Sref * A1) + (1/3 * Sref * A2)"} | ${["A1 : Ancienneté de 10 ans ou moins (10 ans)", "A2 : Ancienneté au-delà de 10 ans (8 ans)", "Sref : Salaire de référence (2800 €)"]}
Je rejoins @Viczei sur ce point. Avec un cas simple, on peut rester simple sur les tests. Moi aussi je prends l'habitude de reprendre les tests d'indemnité mais souvent ce sont des CCs très complexe où je ne suis pas sûr de mon publicodes. 
Après je me disais que ce serait pas mal d'unifier les tests pour avoir un jeu de test en entrée et en sortie on valide le résultat, la formule, les références, l'ancienneté. Mais après ça n'aide pas au TDD...

2023-03-09 08:21 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/1505_commerces_detail_fruits_legumes/__tests__/indemnite-licenciement/formule.spec.ts
> +      "Avec une ancienneté $seniority ans, un salaire de référence $salaireRef € => $expectedFormula",
Je crois que tu peux enlever salaire de référence :) 
```suggestion
      "Avec une ancienneté $seniority ans => $expectedFormula",
```

2023-03-09 08:21 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/1505_commerces_detail_fruits_legumes/__tests__/indemnite-licenciement/formule.spec.ts
> +      ${18}     | ${"(1/4 * Sref * A1) + (1/3 * Sref * A2)"} | ${["A1 : Ancienneté de 10 ans ou moins (10 ans)", "A2 : Ancienneté au-delà de 10 ans (8 ans)", "Sref : Salaire de référence (2800 €)"]}
Par contre, ce qui peut être intéressant c'est de tester le cas limite des 10 ans. Pour valider que ça switch bien à ce moment.

2023-03-09 08:21 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/1505_commerces_detail_fruits_legumes/__tests__/indemnite-licenciement/indemnite.spec.ts
> +      ${20}     | ${15166.67}
:+1:

2023-03-09 08:21 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/1505_commerces_detail_fruits_legumes/__tests__/indemnite-licenciement/references.spec.ts
> +  test("Licenciement pour inaptitude non professionnelle", () => {
Je crois que le libellé n'est pas exact ici ? 🤔

2023-03-09 08:21 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/1505_commerces_detail_fruits_legumes/indemnite-licenciement.yaml
> +  applicable si: indemnité de licenciement
On a encore ce reliquat... il faudra qu'on pense à le supprimer. Ce flag était utilisé pour désactiver les règles du préavis de retraitre. Or maintenant on a splitté les yaml donc plus besoin de ce flag.

2023-03-09 08:21 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/1505_commerces_detail_fruits_legumes/indemnite-licenciement.yaml
> +  applicable si: indemnité de licenciement . ancienneté conventionnelle requise en année <= 10 an
En cours de validation avec le métier mais il faudrait utiliser `indemnité de licenciement . ancienneté conventionnelle en année`

2023-03-09 08:21 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/1505_commerces_detail_fruits_legumes/indemnite-licenciement.yaml
> +      formula: (1/4 * Sref * A1) + (1/3 * Sref * A2)
On aurait pu si c'était la même ancienneté que le légal mais ici la règle de calcul est différente. Il faut donc bien redéfinir la formule.

2023-03-09 08:21 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/1505_commerces_detail_fruits_legumes/__tests__/indemnite-licenciement/anciennete.spec.ts
> +  `(
Ca me semble suffisant également, après on peut ajouter un cas avec maladie non pro pour valider qu'il retire mais la méthode de base est déjà testé sur ce point. 
On a tendance à beaucoup tester sur nos CCs par habitude mais en soit on est peut être par moment un peu trop exhaustif :)

2023-03-09 08:44 UTC, Viczei commented on packages/code-du-travail-modeles/src/modeles/conventions/1505_commerces_detail_fruits_legumes/__tests__/indemnite-licenciement/references.spec.ts
> +  test("Licenciement pour inaptitude non professionnelle", () => {
en effet

2023-03-13 08:50 UTC, carolineBda commented on packages/code-du-travail-modeles/src/modeles/conventions/1505_commerces_detail_fruits_legumes/indemnite-licenciement.yaml
> +  applicable si: indemnité de licenciement
ah oui exacte

2023-03-13 08:53 UTC, carolineBda approved these changes

2023-03-14 08:48 UTC, m-maillot requested changes

2023-03-14 08:48 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/1505_commerces_detail_fruits_legumes/indemnite-licenciement.yaml
> +  applicable si: indemnité de licenciement . ancienneté conventionnelle requise en année <= 10 an
Il faut utilisé résultat conventionnelle ici 
```suggestion
  applicable si: indemnité de licenciement . ancienneté conventionnelle en année <= 10 an
```

2023-03-14 08:48 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/1505_commerces_detail_fruits_legumes/indemnite-licenciement.yaml
> +  applicable si: indemnité de licenciement . ancienneté conventionnelle requise en année > 10 an
```suggestion
  applicable si: indemnité de licenciement . ancienneté conventionnelle en année > 10 an
```

2023-03-14 08:48 UTC, maxgfr commented on packages/code-du-travail-modeles/src/modeles/conventions/1505_commerces_detail_fruits_legumes/indemnite-licenciement.yaml
> +  applicable si: indemnité de licenciement . ancienneté conventionnelle requise en année > 10 an
👀

2023-03-14 08:48 UTC, maxgfr commented on packages/code-du-travail-modeles/src/modeles/conventions/1505_commerces_detail_fruits_legumes/indemnite-licenciement.yaml
> +  applicable si: indemnité de licenciement . ancienneté conventionnelle requise en année <= 10 an
+ 1

2023-03-23 09:06 UTC, m-maillot approved these changes

2023-03-23 09:06 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/1505_commerces_detail_fruits_legumes/__tests__/indemnite-licenciement/indemnite.spec.ts
> +    ${20}          | ${20}     | ${15166.67}
```suggestion
    seniorityRight | seniority | expectedCompensation
    ${6 / 12}      | ${1} | ${0}
    ${8/12}        | ${0.67}   | ${435.5}
    ${8/12}           | ${6}      | ${3900}
    ${8/12}           | ${6}      | ${3900}
    ${8/12}          | ${11}     | ${7366.67}
    ${8/12}          | ${11}     | ${7366.67}
    ${8/12}          | ${20}     | ${15166.67}
```

Je pense que l'on peut challenger les variables avec ces valeurs :)

2023-03-23 13:44 UTC, maxgfr approved these changes

2023-03-27 08:17 UTC, merged