WIP fix(indexing): make unique slugs for faqs and fiches s-p
SocialGouv/code-du-travail-numerique pull request #500
Opened 2019-02-04 14:07 UTC by revolunet

this will allow referencing specific content from our data

should help for#280 #469

2019-02-05 10:40 UTC, lionelB commented
Merci pour la PR.

Je me demande si utiliser le contenu comme `seed` pour générer le hash ne risque pas de nous poser problème ensuite si le contenu change mais pas le titre, on aura une url différente. Il me semble qu'on avait évoqué le fait d'utiliser le hash sur (title + source + tags) pour limiter les risques de changement ?

2019-02-06 11:04 UTC, revolunet commented
j'ai modifié en utilisant `source+titre` pour générer le "hash"

2019-02-06 11:23 UTC, lionelB requested changes
Could it be simpler to pass makeHash( title, source)
and do `(source+title).encode('utf-8')

fiche_service_public doesn't need to have uniq hash since we can use their url. I think we only need to uniqify faq's content.

2019-02-12 09:13 UTC, lionelB commented
> Could it be simpler to pass makeHash( title, source)
and do `(source+title).encode('utf-8')
> fiche_service_public doesn't need to have uniq hash since we can use their url. I think we only need to uniqify faq's content.

@revolunet je peux faire la modif si tu veux

2019-02-12 09:20 UTC, lionelB commented
before 
---
slug | count
-----|----
faq/lemployeur-peut-il-faire-travailler-un-salarie-le-samedi-et-le-dimanche-convention-collective-de-la-boulangerie-artisanale | 2
faq/mon-employeur-peut-til-me-demander-de-travailler-la-nuit-ou-en-soiree | 2
faq/quelle-est-la-date-a-laquelle-selon-la-loi-mon-employeur-doit-verser-mon-salaire | 3
faq/quelle-est-la-duree-maximale-de-la-periode-dessai | 4
fiches_ministere_travail/cesu-quelles-sont-les-activites-comprises-dans-les-services-aux-personnes | 2
fiches_ministere_travail/la-protection-en-cas-de-licenciement-quelle-est-la-duree-dapplication-du-statut-protecteur | 2
fiches_ministere_travail/la-protection-en-cas-de-licenciement-quelle-est-la-protection-en-cas-de-transfert-dactivite | 2
fiches_ministere_travail/la-protection-en-cas-de-licenciement-quels-sont-les-moyens-de-recours | 2
fiches_ministere_travail/la-protection-en-cas-de-licenciement-quels-sont-les-salaries-proteges | 2
kali/magasins-prestataires-de-services-de-cuisine-a-usage-domestique-du-17-juillet-2008 | 2
themes/quest-ce-que-la-rupture-conventionnelle-collective | 2

after 
--- 
slug | count
-----|----
faq/lemployeur-peut-il-faire-travailler-un-salarie-le-samedi-et-le-dimanche-convention-collective-de-la-boulangerie-artisanale-ifre-ujizol8vq | 2
faq/mon-employeur-peut-til-me-demander-de-travailler-la-nuit-ou-en-soiree-p64zdlocvq9snq | 2
faq/quelle-est-la-date-a-laquelle-selon-la-loi-mon-employeur-doit-verser-mon-salaire-p5ze3iguowoqqw | 3
faq/quelle-est-la-duree-maximale-de-la-periode-dessai-x14tybo3-8oibw | 4
fiches_ministere_travail/cesu-quelles-sont-les-activites-comprises-dans-les-services-aux-personnes | 2
fiches_ministere_travail/la-protection-en-cas-de-licenciement-quelle-est-la-duree-dapplication-du-statut-protecteur | 2
fiches_ministere_travail/la-protection-en-cas-de-licenciement-quelle-est-la-protection-en-cas-de-transfert-dactivite | 2
fiches_ministere_travail/la-protection-en-cas-de-licenciement-quels-sont-les-moyens-de-recours | 2
fiches_ministere_travail/la-protection-en-cas-de-licenciement-quels-sont-les-salaries-proteges | 2
kali/magasins-prestataires-de-services-de-cuisine-a-usage-domestique-du-17-juillet-2008 | 2
themes/quest-ce-que-la-rupture-conventionnelle-collective | 2

2019-02-12 09:20 UTC, lionelB commented
@revolunet it's seems we still have the problem :)

2019-02-13 06:53 UTC, lionelB approved these changes

2019-02-13 06:54 UTC, merged