fix(indemnite-licenciement): correctif de la cc 44
SocialGouv/code-du-travail-numerique pull request #5028
Opened 2023-03-15 14:58 UTC by maxgfr

fix #4923

2023-03-16 08:18 UTC, m-maillot reviewed
Ce serait pas mal de mettre à jour les TUs de la 44 pour ajouter ce cas ?

2023-03-16 10:23 UTC, maxgfr commented
@m-maillot Oui je suis absolument d'accord 👍

2023-03-16 10:34 UTC, maxgfr commented on packages/code-du-travail-frontend/package.json
> +    "jest-environment-jsdom": "29.5.0",
j'ai eu des soucis avec jest, je pouvais plus runner les tests de manière utilitaires (je pense toi aussi @Viczei), le fait d'upgrade corrige ce soucis sur vscode de mon côté

2023-03-16 13:53 UTC, Viczei commented on packages/code-du-travail-frontend/package.json
> +    "jest-environment-jsdom": "29.5.0",
Ah nice ! Oui le plugin vscode ne marchait plus sur le frontend

2023-03-16 13:55 UTC, Viczei approved these changes

2023-03-16 16:11 UTC, carolineBda requested changes

2023-03-16 16:11 UTC, carolineBda commented on packages/code-du-travail-frontend/__tests__/__snapshots__/a-propos.test.tsx.snap
t'as un pb avec jest, toutes les class sont revenus dans les snapshots

2023-03-16 16:11 UTC, carolineBda commented on packages/code-du-travail-frontend/package.json
> +    "jest-environment-jsdom": "29.5.0",
mais je crois que ça a fait régresser les snapshots

2023-03-16 16:11 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/IndemniteLicenciement/__tests__/cc44.test.tsx
:+1:

2023-03-20 15:23 UTC, maxgfr commented on packages/code-du-travail-frontend/__tests__/__snapshots__/a-propos.test.tsx.snap
Non du coup c'est lié à l'update

2023-03-21 11:00 UTC, maxgfr commented
@carolineBda je n'ai pas vu d'options pour les desactiver, c'est assez bizarre. Dans tous les cas, on est  a la dernière version de jest là

2023-03-22 09:15 UTC, maxgfr commented on packages/code-du-travail-frontend/test/jest.setup.js
> -import "jest-styled-components";
Le CSS venait de là : cc @carolineBda

2023-03-22 09:49 UTC, m-maillot approved these changes

2023-03-22 09:49 UTC, carolineBda approved these changes
top le test et les dependencies

2023-03-22 09:53 UTC, merged