feat(indemnite-licenciement): ajout d'un tooltip sur un `SectionTitle`
SocialGouv/code-du-travail-numerique pull request #5059
Opened 2023-03-29 12:15 UTC by maxgfr

fix #4991

2023-03-29 12:32 UTC, maxgfr commented on packages/code-du-travail-frontend/src/common/Tooltip.tsx
> -  cursor: pointer;
J'ai modifié ce composant car il était pas accessible vu que c'était une div. Alors qu'avec un bouton si

2023-03-29 12:34 UTC, carolineBda commented on packages/code-du-travail-frontend/src/common/Tooltip.tsx
> +  cursor: pointer;
on a plus besoin non du cursor: pointer il y est déjà sur le bouton ?

2023-03-29 12:40 UTC, carolineBda requested changes

2023-03-29 12:40 UTC, carolineBda commented on packages/code-du-travail-frontend/src/questionnaire/Components/Summary/SummaryItem.tsx
> +                title={"Plus d'informations"}
c'est déjà le title par défaut je crois

2023-03-29 12:40 UTC, carolineBda commented on packages/code-du-travail-frontend/src/outils/IndemniteLicenciement/steps/Anciennete/components/SectionTitleWithTooltip.tsx
> +const SectionTitle = styled.h2`
ici on peut utiliser directement `SectionTitle` de` src/outils/common/stepStyles.ts`

2023-03-29 13:31 UTC, Viczei commented on packages/code-du-travail-frontend/src/common/Tooltip.tsx
> -  cursor: pointer;
Je crois qu'il n'est plus utilisé ce composant. C'était le tooltip du dossier licenciement mais maintenant on utilise le composant Infobulle. Il faudrait supprimer se composant je pense

2023-03-29 13:32 UTC, Viczei commented on packages/code-du-travail-frontend/src/outils/IndemniteLicenciement/steps/Anciennete/components/SectionTitleWithTooltip.tsx
> +const StyledTooltip = styled(Tooltip)`
Peut être plutôt utilisé Infobulle ?

2023-03-30 07:35 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/IndemniteLicenciement/steps/Anciennete/components/SectionTitleWithTooltip.tsx
> +const SectionTitle = styled.h2`
Le problème c'est qu'il set un margin top et un margin bottom

2023-03-30 07:36 UTC, maxgfr commented on packages/code-du-travail-frontend/src/questionnaire/Components/Summary/SummaryItem.tsx
> +                title={"Plus d'informations"}
C'est le composant du dossier licenciement, à voir si on l'utilise cc @Viczei

2023-03-30 07:37 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/IndemniteLicenciement/steps/Anciennete/components/SectionTitleWithTooltip.tsx
> +const StyledTooltip = styled(Tooltip)`
Le problème vient du `flex`

2023-03-30 09:44 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/IndemniteLicenciement/steps/Anciennete/components/SectionTitleWithTooltip.tsx
> +const SectionTitle = styled.h2`
Ok je suis reparti dessus et j'ai `styled` le composant

2023-03-30 09:44 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/IndemniteLicenciement/steps/Anciennete/components/SectionTitleWithTooltip.tsx
> +const StyledTooltip = styled(Tooltip)`
Ok, j'ai enlevé les `flex`, je fais sans du coup 😅

2023-03-30 14:33 UTC, carolineBda approved these changes

2023-04-05 12:41 UTC, m-maillot approved these changes

2023-04-05 14:09 UTC, merged