fix(scrap): add ariane+tags for fiches min.t
SocialGouv/code-du-travail-numerique pull request #510
Opened 2019-02-07 13:27 UTC by revolunet

ajout des données manquantes dans le JSON des fiches min.t (pour EIG)

2019-02-07 13:51 UTC, lionelB requested changes
thnaks :)
Should we do the same for fiche-service-public ?

2019-02-07 13:51 UTC, lionelB commented on packages/code-du-travail-data/dataset/fiches_ministere_travail/index.js
> +  const ariane = $(dom.window.document, "nav.page__breadcrumb")
could be better to target `nav.page__breadcrumb a` so you don't need to remove `\n` and `>`

2019-02-07 13:51 UTC, lionelB commented on packages/code-du-travail-data/dataset/fiches_ministere_travail/index.js
> +  const ariane = $(dom.window.document, "nav.page__breadcrumb")
```js
$$(dom.window.document, "nav.page__breadcrumb").slice(1).map(el => el.textContent.trim())

2019-02-08 15:02 UTC, douglasduteil approved these changes
LGTM

2019-02-12 09:10 UTC, lionelB approved these changes

2019-02-12 09:11 UTC, merged