feat: indemnite licenciement 1404
SocialGouv/code-du-travail-numerique pull request #5133
Opened 2023-05-04 09:34 UTC by Viczei

2023-05-16 10:24 UTC, maxgfr approved these changes

2023-05-25 14:51 UTC, carolineBda requested changes, later dismissed

2023-05-25 14:51 UTC, carolineBda commented on packages/code-du-travail-frontend/src/common/__tests__/__snapshots__/ServiceRenseignement.test.js.snap
> +      <div
c'est chelou ce truc ajouté ?

2023-05-25 14:51 UTC, carolineBda commented on packages/react-ui/src/field/Input.js
> +        {Icon ? <Icon /> : <span>{text}</span>}
c'est ici il faut gérer le cas ou pas d'icon et pas de text pour ne rien afficher

2023-06-20 07:24 UTC, m-maillot approved these changes

2023-06-20 07:37 UTC, merged