feat(contributions): nouvelle version pages personnalisables
SocialGouv/code-du-travail-numerique pull request #5280
Opened 2023-07-17 09:36 UTC by carolineBda

2023-07-27 12:45 UTC, maxgfr approved these changes
top !

2023-07-31 09:37 UTC, m-maillot requested changes
Top ! 

Attention, il reste des reliquats de tests à supprimer avant merge

2023-07-31 09:37 UTC, m-maillot commented on packages/code-du-travail-frontend/pages/contribution/[slug].tsx
> +function PageContribution(props: Props): JSX.Element {
JSX.Element est deprecated (https://stackoverflow.com/questions/76224848/what-is-the-correct-return-type-replacement-for-jsx-element-after-the-global-jsx)

```suggestion
function PageContribution(props: Props): React.ReactElement {
```

2023-07-31 09:37 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/CommonSteps/Agreement/index.tsx
> +          AA
Kezako ?? 🤔 😄

2023-08-03 15:22 UTC, merged