feat(data): update fiche-service public
SocialGouv/code-du-travail-numerique pull request #560
Opened 2019-02-27 11:07 UTC by lionelB

mise à jour des fiches service public

    ## 246 Fiches supprimées
     - [F10041 - Diplômes professionnels (BEP, CAP...)](https://www.service-public.fr/particuliers/vosdroits/F10041)
 - [F10252 - Compte épargne-temps (CET) dans la fonction publique territoriale (FPT)](https://www.service-public.fr/particuliers/vosdroits/F10252)
 - [F1049 - Rachat des années d'études du fonctionnaire](https://www.service-public.fr/particuliers/vosdroits/F1049)
 - [F11016 - Arrêt maladie d'un agent public pendant les congés : quelles sont les règles ?](https://www.service-public.fr/particuliers/vosdroits/F11016)
 - [F11683 - Intégration directe d'un fonctionnaire dans un autre corps/cadre d'emplois](https://www.service-public.fr/particuliers/vosdroits/F11683)
 - [F1190 -  Formation des jeunes : établissement pour l'insertion dans l'emploi (Épide)](https://www.service-public.fr/particuliers/vosdroits/F1190)
 - [F11992 - Évaluation professionnelle dans la fonction publique d'État](https://www.service-public.fr/particuliers/vosdroits/F11992)
 - [F12163 - Remboursement des frais de transport domicile-travail (fonction publique)](https://www.service-public.fr/particuliers/vosdroits/F12163)
 - [F12219 - Un étranger peut-il travailler dans la fonction publique française ?](https://www.service-public.fr/particuliers/vosdroits/F12219)
 - [F1225 - Revenus à déclarer : éléments du salaire imposable](https://www.service-public.fr/particuliers/vosdroits/F1225)
 - [F1234 - Comment un assistant maternel doit-il déclarer ses revenus ?](https://www.service-public.fr/particuliers/vosdroits/F1234)
 - [F12344 - Catégorie, corps, cadre d'emplois, grade et échelon : quelles différences ?](https://www.service-public.fr/particuliers/vosdroits/F12344)
 - [F12382 - Chômage : compte personnel de formation (CPF) d'un demandeur d'emploi](https://www.service-public.fr/particuliers/vosdroits/F12382)
 - [F12386 - Allocation d'aide au retour à l'emploi (ARE) d'un ancien agent public](https://www.service-public.fr/particuliers/vosdroits/F12386)
 - [F12387 - Retraite complémentaire d'un fonctionnaire (RAFP)](https://www.service-public.fr/particuliers/vosdroits/F12387)
 - [F12390 - Retraite complémentaire d'un agent non titulaire (Ircantec)](https://www.service-public.fr/particuliers/vosdroits/F12390)
 - [F12391 - Un contractuel peut-il bénéficier d'un temps partiel thérapeutique ?](https://www.service-public.fr/particuliers/vosdroits/F12391)
 - [F12392 - Un agent public perd-il les congés non pris pour cause de maladie ?](https://www.service-public.fr/particuliers/vosdroits/F12392)
 - [F12395 - Retraite dans la fonction publique : limite d'âge](https://www.service-public.fr/particuliers/vosdroits/F12395)
 - [F12402 - Retraite d'un fonctionnaire : cumul emploi - retraite de base](https://www.service-public.fr/particuliers/vosdroits/F12402)
 - [F12413 - Quelles sont les positions administratives dans la fonction publique ?](https://www.service-public.fr/particuliers/vosdroits/F12413)
 - [F1251 - Un agent à temps partiel peut-il déplacer son jour non travaillé s'il est férié?](https://www.service-public.fr/particuliers/vosdroits/F1251)
 - [F12565 - Arrêt maladie d'un fonctionnaire : en quoi consiste l'indemnité différentielle ?](https://www.service-public.fr/particuliers/vosdroits/F12565)
 - [F12686 - Fonction publique : recrutement dans le cadre du Pacte](https://www.service-public.fr/particuliers/vosdroits/F12686)
 - [F12788 - Un fonctionnaire peut-il bénéficier d'un temps partiel thérapeutique ?](https://www.service-public.fr/particuliers/vosdroits/F12788)
 - [F12811 - Comment est versée la pension de retraite de base d'un fonctionnaire ?](https://www.service-public.fr/particuliers/vosdroits/F12811)
 - [F13104 - Pension de réversion - Défunt ayant travaillé dans le privé](https://www.service-public.fr/particuliers/vosdroits/F13104)
 - [F13117 - Conditions d'emploi d'un agent contractuel de la fonction publique](https://www.service-public.fr/particuliers/vosdroits/F13117)
 - [F13272 - Quelles sont les conditions d'accès à la fonction publique ? ](https://www.service-public.fr/particuliers/vosdroits/F13272)
 - [F13300 - Retraite de base des fonctionnaires : minimum garanti](https://www.service-public.fr/particuliers/vosdroits/F13300)
 - [F13322 - Abandon de poste : quelles sont les règles dans la fonction publique ?](https://www.service-public.fr/particuliers/vosdroits/F13322)
 - [F13712 - Dans la fonction publique, perd-on des RTT en cas de maladie ?](https://www.service-public.fr/particuliers/vosdroits/F13712)
 - [F13736 - Retraite du fonctionnaire : services pris en compte](https://www.service-public.fr/particuliers/vosdroits/F13736)
 - [F13765 - Congé de 3 jours pour naissance ou adoption dans la fonction publique](https://www.service-public.fr/particuliers/vosdroits/F13765)
 - [F13825 - Maladie ou inaptitude d'un fonctionnaire stagiaire : quelles conséquences ?](https://www.service-public.fr/particuliers/vosdroits/F13825)
 - [F13839 - Recrutement d'un agent contractuel dans la fonction publique territoriale (FPT)](https://www.service-public.fr/particuliers/vosdroits/F13839)
 - [F13852 - Agent contractuel de la fonction publique : passage automatique en CDI](https://www.service-public.fr/particuliers/vosdroits/F13852)
 - [F13861 - Le jour de carence pour maladie existe-t-il dans la fonction publique ?](https://www.service-public.fr/particuliers/vosdroits/F13861)
 - [F13890 - Retraite dans la fonction publique : droit à l'information du futur retraité](https://www.service-public.fr/particuliers/vosdroits/F13890)
 - [F13896 - Prise en charge des frais de changement de résidence (fonction publique)](https://www.service-public.fr/particuliers/vosdroits/F13896)
 - [F13943 - Recrutement d'un agent contractuel dans la fonction publique hospitalière (FPH)](https://www.service-public.fr/particuliers/vosdroits/F13943)
 - [F13944 - Quel lien entre procédures disciplinaire et pénale pour un fonctionnaire ?](https://www.service-public.fr/particuliers/vosdroits/F13944)
 - [F13946 - Fonction publique : retraite anticipée pour carrière longue](https://www.service-public.fr/particuliers/vosdroits/F13946)
 - [F13970 - Suspension de fonctions en cas de faute grave dans la fonction publique](https://www.service-public.fr/particuliers/vosdroits/F13970)
 - [F13974 - Télétravail dans le secteur public](https://www.service-public.fr/particuliers/vosdroits/F13974)
 - [F13975 - Agent public à temps non complet, incomplet et partiel : quelles différences ?](https://www.service-public.fr/particuliers/vosdroits/F13975)
 - [F13976 - Fonction publique : peut-on encore bénéficier des concours réservés ?](https://www.service-public.fr/particuliers/vosdroits/F13976)
 - [F14012 - Recrutement d'un agent contractuel dans la fonction publique d'État (FPE)](https://www.service-public.fr/particuliers/vosdroits/F14012)
 - [F14060 - Retraite anticipée pour handicap dans la fonction publique](https://www.service-public.fr/particuliers/vosdroits/F14060)
 - [F14809 - Allocation d'éducation de l'enfant handicapé (AEEH)](https://www.service-public.fr/particuliers/vosdroits/F14809)
 - [F14868 - Accident du travail : indemnisation des ayants droit en cas de décès du salarié](https://www.service-public.fr/particuliers/vosdroits/F14868)
 - [F15132 - Allocation journalière de présence parentale (AJPP)](https://www.service-public.fr/particuliers/vosdroits/F15132)
 - [F1544 - Capital décès versé pour le décès d'un fonctionnaire](https://www.service-public.fr/particuliers/vosdroits/F1544)
 - [F1564 - Que se passe-t-il si le fonctionnaire stagiaire n'est pas titularisé ?](https://www.service-public.fr/particuliers/vosdroits/F1564)
 - [F15813 - Séjour d'un jeune étranger stagiaire aide familial "au pair"](https://www.service-public.fr/particuliers/vosdroits/F15813)
 - [F1591 - Une candidate enceinte peut-elle passer un concours administratif ?](https://www.service-public.fr/particuliers/vosdroits/F1591)
 - [F1599 - Congé bonifié ](https://www.service-pu [...]

2019-02-27 14:11 UTC, jrduscher commented
modifications checked: j'ai accepté certaines fiches pas liés mais péripériques au droit du travail; on verra à l'usage, et si elles polluent de trop: on les virera ( avec la liste en une fois)

2019-02-27 14:51 UTC, jrduscher commented
mise à jour des fiches service public

## 246 Fiches supprimées
**NE PAS SUPPRIMER**- [F10041 - Diplômes professionnels (BEP, **CAP...)](https://www.service-public.fr/particuliers/vosdroits/F10041) 
**NE PAS SUPPRIMER**- - [F1190 -  Formation des jeunes : établissement pour l'insertion dans l'emploi (Épide)](https://www.service-public.fr/particuliers/vosdroits/F1190)
**NE PAS SUPPRIMER**- - [F12163 - Remboursement des frais de transport domicile-travail (fonction publique)](https://www.service-public.fr/particuliers/vosdroits/F12163)
**NE PAS SUPPRIMER**- - [F1234 - Comment un assistant maternel doit-il déclarer ses revenus ?](https://www.service-public.fr/particuliers/vosdroits/F1234)
**NE PAS SUPPRIMER**- - [F12382 - Chômage : compte personnel de formation (CPF) d'un demandeur d'emploi](https://www.service-public.fr/particuliers/vosdroits/F12382)
**NE PAS SUPPRIMER**- - [F14809 - Allocation d'éducation de l'enfant handicapé (AEEH)](https://www.service-public.fr/particuliers/vosdroits/F14809)
**NE PAS SUPPRIMER**- - [F14868 - Accident du travail : indemnisation des ayants droit en cas de décès du salarié](https://www.service-public.fr/particuliers/vosdroits/F14868)
** dans le doute laisser** - [F15132 - Allocation journalière de présence parentale (AJPP)](https://www.service-public.fr/particuliers/vosdroits/F15132)
**NE PAS SUPPRIMER**- - [F15813 - Séjour d'un jeune étranger stagiaire aide familial "au pair"](https://www.service-public.fr/particuliers/vosdroits/F15813)
 **NE PAS SUPPRIMER**-- [F174 - Victime de l'amiante : comment être indemnisé ?](https://www.service-public.fr/particuliers/vosdroits/F174)
**NE PAS SUPPRIMER**- - [F2140 - Intéressement](https://www.service-public.fr/particuliers/vosdroits/F2140)
**NE PAS SUPPRIMER**- - [F2142 - Plan d'épargne entreprise (PEE)](https://www.service-public.fr/particuliers/vosdroits/F2142)
**NE PAS SUPPRIMER - dans le doute-**- - [F24610 - Mon enfant est en situation de handicap](https://www.service-public.fr/particuliers/vosdroits/F24610)
**NE PAS SUPPRIMER** - [F2642 - Accueil d'un enfant par une assistante maternelle agréée](https://www.service-public.fr/particuliers/vosdroits/F2642)
**NE PAS SUPPRIMER** - [F32709 - Peut-on entrer en apprentissage après la classe de troisième ?](https://www.service-public.fr/particuliers/vosdroits/F32709)
**NE PAS SUPPRIMER** - [F34030 - Qu'est-ce que le compte engagement citoyen (CEC) ?](https://www.service-public.fr/particuliers/vosdroits/F34030)
**NE PAS SUPPRIMER** - [F345 - Complément de libre choix du mode de garde (Cmg) - Assistante maternelle](https://www.service-public.fr/particuliers/vosdroits/F345)
 **NE PAS SUPPRIMER**- [F92 - Qu'est-ce qu'un congé de solidarité internationale ?](https://www.service-public.fr/particuliers/vosdroits/F92)
## 170 Fiches ajoutées 
** SUPPRIMER**- [F10027 - Couverture maladie universelle complémentaire (CMU-C)](https://www.service-public.fr/particuliers/vosdroits/F10027)
 ** SUPPRIMER**- [F13375 - Aide à l'acquisition d'une couverture maladie complémentaire (ACS)](https://www.service-public.fr/particuliers/vosdroits/F13375)
** SUPPRIMER** - [F20314 - Couverture maladie complémentaire (mutuelle)](https://www.service-public.fr/particuliers/vosdroits/F20314)
 ** SUPPRIMER**- [F20678 - Comment un micro-entrepreneur doit-il déclarer sa cessation d'activité ?](https://www.service-public.fr/professionnels-entreprises/vosdroits/F20678)
** SUPPRIMER** - [F21789 - Fin de contrat : documents à remettre au salarié](https://www.service-public.fr/professionnels-entreprises/vosdroits/F21789)
 ** SUPPRIMER**- [F22290 - Mandat ad hoc](https://www.service-public.fr/professionnels-entreprises/vosdroits/F22290)
 ** SUPPRIMER**- [F22295 - Conciliation](https://www.service-public.fr/professionnels-entreprises/vosdroits/F22295)
 ** SUPPRIMER**- [F22354 - Qu'est ce qu'un créancier chirographaire ?](https://www.service-public.fr/professionnels-entreprises/vosdroits/F22354)
 ** SUPPRIMER**- [F22356 - Qu'est ce qu'un créancier privilégié ?](https://www.service-public.fr/professionnels-entreprises/vosdroits/F22356)
  ** SUPPRIMER**- [F22359 - Déclaration de créances](https://www.service-public.fr/professionnels-entreprises/vosdroits/F22359)
 ** SUPPRIMER - suite à discussions**- [F22424 - Contrat d'apprentissage](https://www.service-public.fr/professionnels-entreprises/vosdroits/F22424)
 ** SUPPRIMER**- [F22726 - Contribution sociale de solidarité des sociétés (C3S)](https://www.service-public.fr/professionnels-entreprises/vosdroits/F22726)
 ** SUPPRIMER**- [F23369 - Quels sont les droits à la retraite des micro-entrepreneurs ?](https://www.service-public.fr/professionnels-entreprises/vosdroits/F23369)
 ** SUPPRIMER**- [F23459 - Contribution à la formation professionnelle (CFP) des travailleurs indépendants](https://www.service-public.fr/professionnels-entreprises/vosdroits/F23459)
 ** SUPPRIMER**- [F23460 - Crédit d'impôt pour la formation des dirigeants d'entreprise](https://www.service-public.fr/professionnels-entreprises/vosdroits/F23460)
 ** SUPPRIMER**- [F23507 - Cession de fonds de commerce ou de clientèle : déclarations fiscales](https://www.service-public.fr/professionnels-entreprises/vosdroits/F23507)
 ** SUPPRIMER**- [F23756 - Quelles contributions un artiste doit-il payer sur les redevances perçues ?](https://www.service-public.fr/professionnels-entreprises/vosdroits/F23756)
 ** SUPPRIMER**- [F23992 - À quoi sert le numéro d'objet ?](https://www.service-public.fr/professionnels-entreprises/vosdroits/F23992)
 ** SUPPRIMER**- [F23994 - Un travailleur indépendant a-t-il droit à une assurance-chômage ?](https://www.service-public.fr/professionnels-entreprises/vosdroits/F23994)
 ** SUPPRIMER pour l'instant**- [F23997 - Recrutement d'un volontaire international en entreprise (VIE)](https://www.service-public.fr/professionnels-entreprises/vosdroits/F23997)
** SUPPRIMER** - [F24005 - Déclaration pour la retraite complémentaire](https://www.service-public.fr/professionnels-entreprises/vosdroits/F24005)
** SUPPRIMER** - [F24013 - Déclaration et paiement des cotisations sociales](https://www.service-public.fr/professionnels-entreprises/vosdroits/F24013)
** SUPPRIMER** - [F31233 - Cotisations et contributions sociales des professions libérales](https://www.service-public.fr/professionnels-entreprises/vosdroits/F31233)
** SUPPRIMER** - [F31409 - Cotisation au régime de garantie des salaires (AGS)](https://www.service-public.fr/professionnels-entreprises/vosdroits/F31409)
 ** SUPPRIMER**- [F31422 - Comment obtenir une attestation de vigilance ?](https://www.service-public.fr/professionnels-entreprises/vosdroits/F31422)
** SUPPRIMER** - [F31427 - Cession d'une entreprise aux salariés : exonérations pour les cédants](https://www.service-public.fr/professionnels-entreprises/vosdroits/F31427)
** SUPPRIMER** - [F31479 - Déclaration de transfert du siège social d'une entreprise](https://www.service-public.fr/professionnels-entreprises/vosdroits/F31479)
 * SUPPRIMER** - [F31670 - Quelles indemnités un débitant de tabac peut-il toucher en fin d'activité ?](https://www.service-public.fr/professionnels-entreprises/vosdroits/F31670)
** SUPPRIMER** - [F31712 - Le rachat d'une entreprise par ses salariés (LBO) est-il exonéré d'impôt ?](https://www.service-public.fr/professionnels-entreprises/vosdroits/F31712)
** SUPPRIMER** - [F31713 - Qu'est-ce qu'un LBO (Leverage buy out) ?](https://www.service-public.fr/professionnels-entreprises/vosdroits/F31713)
** SUPPRIMER** - [F31837 - Réductions et exonérations fiscales pour les repreneurs d'entreprise](https://www.service-public.fr/professionnels-entreprises/vosdroits/F31837)
** SUPPRIMER** - [F31926 - Que devient le bail commercial en cas de dépôt de bilan ?](https://www.service-public.fr/professionnels-entreprises/vosdroits/F31926)
 * SUPPRIMER** - [F32095 - Rétablissement professionnel](https://www.service-public.fr/professionnels-entreprises/vosdroits/F32095)
** SUPPRIMER** - [F32258 - Que devient la garantie décennale  [...]

2019-02-27 16:13 UTC, lionelB commented
## 16 Fiches ajoutées
- [F10041 - Diplômes professionnels (BEP, CAP...)](https://www.service-public.fr/particuliers/vosdroits/F10041)
 - [F1190 -  Formation des jeunes : établissement pour l'insertion dans l'emploi (Épide)](https://www.service-public.fr/particuliers/vosdroits/F1190)
 - [F1234 - Comment un assistant maternel doit-il déclarer ses revenus ?](https://www.service-public.fr/particuliers/vosdroits/F1234)
 - [F12382 - Chômage : compte personnel de formation (CPF) d'un demandeur d'emploi](https://www.service-public.fr/particuliers/vosdroits/F12382)
 - [F14809 - Allocation d'éducation de l'enfant handicapé (AEEH)](https://www.service-public.fr/particuliers/vosdroits/F14809)
 - [F14868 - Accident du travail : indemnisation des ayants droit en cas de décès du salarié](https://www.service-public.fr/particuliers/vosdroits/F14868)
 - [F15132 - Allocation journalière de présence parentale (AJPP)](https://www.service-public.fr/particuliers/vosdroits/F15132)
 - [F15813 - Séjour d'un jeune étranger stagiaire aide familial "au pair"](https://www.service-public.fr/particuliers/vosdroits/F15813)
 - [F174 - Victime de l'amiante : comment être indemnisé ?](https://www.service-public.fr/particuliers/vosdroits/F174)
 - [F2140 - Intéressement](https://www.service-public.fr/particuliers/vosdroits/F2140)
 - [F2142 - Plan d'épargne entreprise (PEE)](https://www.service-public.fr/particuliers/vosdroits/F2142)
 - [F24610 - Mon enfant est en situation de handicap](https://www.service-public.fr/particuliers/vosdroits/F24610)
 - [F2642 - Accueil d'un enfant par une assistante maternelle agréée](https://www.service-public.fr/particuliers/vosdroits/F2642)
 - [F32709 - Peut-on entrer en apprentissage après la classe de troisième ?](https://www.service-public.fr/particuliers/vosdroits/F32709)
 - [F34030 - Qu'est-ce que le compte engagement citoyen (CEC) ?](https://www.service-public.fr/particuliers/vosdroits/F34030)
 - [F92 - Qu'est-ce qu'un congé de solidarité internationale ?](https://www.service-public.fr/particuliers/vosdroits/F92)
  
## 38 Fiches supprimées
- [F10027 - Couverture maladie universelle complémentaire (CMU-C)](https://www.service-public.fr/particuliers/vosdroits/F10027)
 - [F13375 - Aide à l'acquisition d'une couverture maladie complémentaire (ACS)](https://www.service-public.fr/particuliers/vosdroits/F13375)
 - [F20314 - Couverture maladie complémentaire (mutuelle)](https://www.service-public.fr/particuliers/vosdroits/F20314)
 - [F20678 - Comment un micro-entrepreneur doit-il déclarer sa cessation d'activité ?](https://www.service-public.fr/professionnels-entreprises/vosdroits/F20678)
 - [F22290 - Mandat ad hoc](https://www.service-public.fr/professionnels-entreprises/vosdroits/F22290)
 - [F22295 - Conciliation](https://www.service-public.fr/professionnels-entreprises/vosdroits/F22295)
 - [F22354 - Qu'est ce qu'un créancier chirographaire ?](https://www.service-public.fr/professionnels-entreprises/vosdroits/F22354)
 - [F22356 - Qu'est ce qu'un créancier privilégié ?](https://www.service-public.fr/professionnels-entreprises/vosdroits/F22356)
 - [F22359 - Déclaration de créances](https://www.service-public.fr/professionnels-entreprises/vosdroits/F22359)
 - [F22424 - Contrat d'apprentissage](https://www.service-public.fr/professionnels-entreprises/vosdroits/F22424)
 - [F22726 - Contribution sociale de solidarité des sociétés (C3S)](https://www.service-public.fr/professionnels-entreprises/vosdroits/F22726)
 - [F23369 - Quels sont les droits à la retraite des micro-entrepreneurs ?](https://www.service-public.fr/professionnels-entreprises/vosdroits/F23369)
 - [F23459 - Contribution à la formation professionnelle (CFP) des travailleurs indépendants](https://www.service-public.fr/professionnels-entreprises/vosdroits/F23459)
 - [F23460 - Crédit d'impôt pour la formation des dirigeants d'entreprise](https://www.service-public.fr/professionnels-entreprises/vosdroits/F23460)
 - [F23507 - Cession de fonds de commerce ou de clientèle : déclarations fiscales](https://www.service-public.fr/professionnels-entreprises/vosdroits/F23507)
 - [F23756 - Quelles contributions un artiste doit-il payer sur les redevances perçues ?](https://www.service-public.fr/professionnels-entreprises/vosdroits/F23756)
 - [F23992 - À quoi sert le numéro d'objet ?](https://www.service-public.fr/professionnels-entreprises/vosdroits/F23992)
 - [F23994 - Un travailleur indépendant a-t-il droit à une assurance-chômage ?](https://www.service-public.fr/professionnels-entreprises/vosdroits/F23994)
 - [F23997 - Recrutement d'un volontaire international en entreprise (VIE)](https://www.service-public.fr/professionnels-entreprises/vosdroits/F23997)
 - [F24005 - Déclaration pour la retraite complémentaire](https://www.service-public.fr/professionnels-entreprises/vosdroits/F24005)
 - [F24013 - Déclaration et paiement des cotisations sociales](https://www.service-public.fr/professionnels-entreprises/vosdroits/F24013)
 - [F31233 - Cotisations et contributions sociales des professions libérales](https://www.service-public.fr/professionnels-entreprises/vosdroits/F31233)
 - [F31409 - Cotisation au régime de garantie des salaires (AGS)](https://www.service-public.fr/professionnels-entreprises/vosdroits/F31409)
 - [F31422 - Comment obtenir une attestation de vigilance ?](https://www.service-public.fr/professionnels-entreprises/vosdroits/F31422)
 - [F31427 - Cession d'une entreprise aux salariés : exonérations pour les cédants](https://www.service-public.fr/professionnels-entreprises/vosdroits/F31427)
 - [F31479 - Déclaration de transfert du siège social d'une entreprise](https://www.service-public.fr/professionnels-entreprises/vosdroits/F31479)
 - [F31670 - Quelles indemnités un débitant de tabac peut-il toucher en fin d'activité ?](https://www.service-public.fr/professionnels-entreprises/vosdroits/F31670)
 - [F31712 - Le rachat d'une entreprise par ses salariés (LBO) est-il exonéré d'impôt ?](https://www.service-public.fr/professionnels-entreprises/vosdroits/F31712)
 - [F31713 - Qu'est-ce qu'un LBO (Leverage buy out) ?](https://www.service-public.fr/professionnels-entreprises/vosdroits/F31713)
 - [F31837 - Réductions et exonérations fiscales pour les repreneurs d'entreprise](https://www.service-public.fr/professionnels-entreprises/vosdroits/F31837)
 - [F31926 - Que devient le bail commercial en cas de dépôt de bilan ?](https://www.service-public.fr/professionnels-entreprises/vosdroits/F31926)
 - [F32095 - Rétablissement professionnel](https://www.service-public.fr/professionnels-entreprises/vosdroits/F32095)
 - [F32258 - Que devient la garantie décennale en cas de dépôt de bilan du constructeur ?](https://www.service-public.fr/professionnels-entreprises/vosdroits/F32258)
 - [F32307 - Transmission d'entreprise : exonération de la plus-value professionnelle](https://www.service-public.fr/professionnels-entreprises/vosdroits/F32307)
 - [F32308 - Conséquence fiscale de la transformation d'une entreprise individuelle en société](https://www.service-public.fr/professionnels-entreprises/vosdroits/F32308)
 - [F32581 - Comment calculer les droits d'enregistrement lors d'une mutation de fonds de commerce ?](https://www.service-public.fr/professionnels-entreprises/vosdroits/F32581)
 - [F32703 - Cessation temporaire d'activité ou mise en sommeil d'une entreprise](https://www.service-public.fr/professionnels-entreprises/vosdroits/F32703)
 - [F33843 - Pension de réversion pour l'époux(se) d'un travailleur indépendant](https://www.service-public.fr/professionnels-entreprises/vosdroits/F33843)

2019-03-01 15:55 UTC, jrduscher approved these changes

2019-03-01 16:11 UTC, UnbearableBear approved these changes
Ok nickel, je vais la merger moi même pour garder le diff sous la main !

2019-03-01 17:54 UTC, lionelB commented
@UnbearableBear je te laisse squash 'n merge ?

2019-03-03 22:19 UTC, UnbearableBear requested changes
Je vais intégrer le filter à ma PR à venir, et je garde celle là en change requested en attendant. Je la close quand l'autre sera merge.

2019-03-04 10:26 UTC, UnbearableBear commented
Mergé ici:
https://github.com/SocialGouv/code-du-travail-numerique/pull/569/files#diff-fba60daf0a547b70959d7b47857838c6

2019-03-06 16:59 UTC, UnbearableBear approved these changes

2019-03-06 17:02 UTC, merged