parse XML to json
SocialGouv/code-du-travail-numerique pull request #569
Opened 2019-03-04 09:10 UTC by UnbearableBear

Je me demande si il ne vaut pas mieux générer des fiches unes par unes plutôt que je faire un seul gros fichier. Là on se rapproche dangereusement des 50mo pour la taille du fichier (le json est plus "dense") ? Je pense que le travail pour y parvenir est pas dingue, vous en pensez quoi ?

2019-03-04 09:48 UTC, revolunet commented
Pas vraiment un souci les 50Mo imho... sauf pour vscode 😈

2019-03-04 09:56 UTC, UnbearableBear commented
Même VSCode ça va :D Par contre si je vire la fonction de filtre sur les fichiers de @lionelB le fichier peut dépasser les 100mo en minifié 😱 
Et node a besoin de bcp de mémoire vive pour générer le gros gros fichier donc je suis obligé de rajouter l'option `node --max-old-space-size=4096 index.js` alors que si je génère plein de petits fichiers, un à la fois, et que je modifie la partie en python qui intègre ça dans ES, tout roule !

2019-03-07 15:16 UTC, lionelB commented on packages/code-du-travail-data/dataset/fiches_service_public/diff.js
> +);
bien vu !

2019-03-07 15:18 UTC, lionelB commented on packages/code-du-travail-data/dataset/fiches_service_public/filter.js
> +  if (excludeDossierId.some(id => arianeIDs.includes(id))) {
je trouvais plus lisible avec la fonction matchFildAriane(id)

2019-03-07 15:24 UTC, lionelB commented on packages/code-du-travail-data/dataset/fiches_service_public/format.js
> +  const joint = "#";
ca sert à quoi ce caractère ? si il est utilisé qu'une seule fois, tu peux l'inliner directement

2019-03-07 15:46 UTC, lionelB commented on packages/code-du-travail-data/dataset/fiches_service_public/index.js
> +const fiches = fichesParticuliers.concat(fichesPro);
const fiches = [].concat(
  getFiches("./data/vosdroits-particuliers"),
  getFiches("./data/vosdroits-professionnels")
);

2019-03-07 16:57 UTC, lionelB commented on packages/code-du-travail-data/dataset/fiches_service_public/index.js
> +    fs.writeFileSync("./fiches-sp-travail.json", JSON.stringify(formatedFiches, null, 2));
je preferai qu'on garde le console.log et qu'on fasse le `>` dans un run scripts pour garder la flexibilité du truc

2019-03-07 16:59 UTC, lionelB commented on packages/code-du-travail-data/search/indexing/cdtn_documents.py
> +                'all_text': f"{val['title']} {val['text']}",
all_text n'est plus utilisé, tu peux l'enlever.

2019-03-07 17:00 UTC, lionelB requested changes
merci @UnbearableBear !
j'ai vu qu'il reste des commit sur l'autre PR qui concerne les data, est ce que tu pourrais les cherry-pick de l'autre branche ?

2019-03-07 17:13 UTC, UnbearableBear commented on packages/code-du-travail-data/dataset/fiches_service_public/filter.js
> +  if (excludeDossierId.some(id => arianeIDs.includes(id))) {
T'avais qu'à faire le rebase toi :p Non plus sérieusement, je peux surement "fonctionniser" arianeIDs.includes pour l'appeler matchFilDAriane mais du coup le bout de code qui extrait les IDs du fil d'ariane sera executé 3 fois plus.

2019-03-07 17:15 UTC, UnbearableBear commented on packages/code-du-travail-data/dataset/fiches_service_public/format.js
> +  const joint = "#";
Alors par défaut chaque groupe de mots est séparé par un espace, pour elasticsearch. Sauf que pour les tags on veut resplitter en arrays ces groupes de mots donc je suis obligé de spécifier un séparateur spécifique. Pour avoir un array de groupe de mots et pas un array de mots.

2019-03-07 17:18 UTC, UnbearableBear commented on packages/code-du-travail-data/dataset/fiches_service_public/index.js
> +    fs.writeFileSync("./fiches-sp-travail.json", JSON.stringify(formatedFiches, null, 2));
Moi ça m'a rendu ouf ce truc, je devais commenter / dé-commenter à gogo toutes les trois secondes en fonction de si je voulais avoir le résultat ou des logs.
Rien n'empêche, si tu veux des logs archi balèze de continuer à mettre des consoles log et de faire > quand tu le souhaites. Mais là au moins tu sais que dans ton fichiers de resultats tu as les resultats et basta, et tu peux faire tous les console.log que tu veux entre temps.

2019-03-07 17:22 UTC, UnbearableBear commented
Yes je vais essayer, j'espère jusque que j'ai bien mis ça dans un commit spécifique et que je vais pas avoir à split mes commits, après la frayeur de ce matin je préfère éviter les aventures 😅

2019-03-07 17:22 UTC, lionelB commented on packages/code-du-travail-data/dataset/fiches_service_public/filter.js
> +  if (excludeDossierId.some(id => arianeIDs.includes(id))) {
```js
 if (excludeDossierId.some(id => matchFilDAriane(id)) {
```

2019-03-07 17:36 UTC, lionelB commented on packages/code-du-travail-data/dataset/fiches_service_public/format.js
> +  const joint = "#";
est ce que tu aurais un exemple ?

2019-03-11 13:47 UTC, UnbearableBear commented on packages/code-du-travail-data/dataset/fiches_service_public/filter.js
> +  if (excludeDossierId.some(id => arianeIDs.includes(id))) {
done !

2019-03-11 13:52 UTC, UnbearableBear commented
> merci @UnbearableBear !
> j'ai vu qu'il reste des commit sur l'autre PR qui concerne les data, est ce que tu pourrais les cherry-pick de l'autre branche ?

Done !

2019-03-12 08:24 UTC, lionelB commented on packages/code-du-travail-data/dataset/fiches_service_public/index.js
> +const fiches = [].concat(fichesParticuliers, fichesPro);
ca me parraissait plus clair de de faire le concat avec les getFiches directement, la fichePro et fichePart ne serve que pour le concat il me semble

2019-03-12 08:34 UTC, lionelB commented on packages/code-du-travail-data/dataset/fiches_service_public/index.js
> +    fs.writeFileSync("./fiches-sp-travail.json", JSON.stringify(formatedFiches, null, 2));
je comprend mais
- l'ensemble des script de data fonctionne sur ce principe, je trouve que c'est bien de conserver une certaine cohérence.
-  tu peux conserver l'output des messages d'erreurs dans la console et piper la sortie vers un fichier si tu fais des `console.error` 

```index.js
console.log("hello from log")
console.error("dawn, an error")
```

```
node index  >  output.json 
dawn, an error
```
tout en ayant  "hello from log" dans output.json

2019-03-12 09:35 UTC, UnbearableBear commented on packages/code-du-travail-data/dataset/fiches_service_public/index.js
> +    fs.writeFileSync("./fiches-sp-travail.json", JSON.stringify(formatedFiches, null, 2));
Ok pas de soucis je vais changer mais comme j'avais jamais vu ça ailleurs j'ai aussi surpris par la combinaison du console.log et du > pour générer un fichier. Enfin, je trouve que l'intention est pas claire avec ce procédé mais maintenant que je le sais ! Pour ce qui est de la flexibilité, si le nom du fichier doit être décidé en ldc, il suffit de passer un arg

2019-03-12 09:53 UTC, UnbearableBear commented on packages/code-du-travail-data/dataset/fiches_service_public/format.js
> +  const joint = "#";
Faire une fonction qui renvoie un tableau directement (getTags ?)

2019-03-12 09:55 UTC, UnbearableBear commented on packages/code-du-travail-data/dataset/fiches_service_public/index.js
> +const fiches = fichesParticuliers.concat(fichesPro);
Ok !

2019-03-15 10:36 UTC, lionelB approved these changes

2019-03-15 10:41 UTC, merged