feat(indemnite-licenciement): use calculate from information step rupture
SocialGouv/code-du-travail-numerique pull request #5703
Opened 2024-03-15 16:08 UTC by m-maillot

closes [#5626](https://github.com/SocialGouv/code-du-travail-numerique/issues/5626)

2024-03-18 13:01 UTC, carolineBda commented on packages/code-du-travail-modeles/src/publicodes/RuptureConventionnellePublicodes.ts
> +        console.log(`Compute for reason: ${name}`);
```suggestion
```

2024-04-02 11:38 UTC, carolineBda requested changes
![Screenshot from 2024-04-02 13-33-32](https://github.com/SocialGouv/code-du-travail-numerique/assets/4971715/c4a1d649-762b-4ebc-a6e3-241e3bceadf7)

Regression sur la page résultat de l'IL on dit " l’indemnité de rupture conventionnelle "

2024-04-03 09:16 UTC, m-maillot commented
> ![Screenshot from 2024-04-02 13-33-32](https://private-user-images.githubusercontent.com/4971715/318763062-c4a1d649-762b-4ebc-a6e3-241e3bceadf7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMzU1MjUsIm5iZiI6MTcxMjEzNTIyNSwicGF0aCI6Ii80OTcxNzE1LzMxODc2MzA2Mi1jNGExZDY0OS03NjJiLTRlYmMtYTZlMy0yNDFlM2JjZWFkZjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDNUMDkwNzA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjQ2M2U2NzJmMjQ2MGU4MDA2YTE2OWMwOWY0MjM3MTAyMzYwODA3NzZmNDI4MWExMmI0OTg0ZGZhNjBkY2U2NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.81xq8PMhlQYXZ1tXanPYY4K6mjaHrOaDBj38wgUNhQ8)
> 
> Regression sur la page résultat de l'IL on dit " l’indemnité de rupture conventionnelle "

C'est corrigé :)

2024-04-03 10:20 UTC, Viczei commented on packages/code-du-travail-frontend/src/outils/CommonIndemniteDepart/steps/ContratTravail/store/store.ts
> +              : PublicodesSimulator.RUPTURE_CONVENTIONNELLE;
C'est dommage de ne pas avoir un seul enum

2024-04-03 10:53 UTC, maxgfr reviewed
Top, énorme taff pour le refacto 💪

2024-04-03 10:53 UTC, maxgfr commented on packages/code-du-travail-frontend/pages/outils/index.tsx
> +    const isProd = process.env.NEXT_PUBLIC_SENTRY_ENV === "production"
Je  pense qu'il est plus preferrable d'utiliser : `NEXT_PUBLIC_IS_PRODUCTION_DEPLOYMENT`, que de se baser sur la variable de sentry

2024-04-03 10:53 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/CommonIndemniteDepart/steps/Resultat/components/DecryptResult.tsx
> +  label: string;
Je pense on aurait pu le typer fort en `licenciement` | `rupture`

```suggestion
  label: 'licenciement' | 'rupture conventionnelle'
```

2024-04-03 10:53 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/CommonIndemniteDepart/steps/Resultat/components/FilledElements.tsx
> +                      * {item.detail}
Je pense qu'il y aura deux `*` si on fait çaAvant, on affichait la deuxieme étoile que si y'avait pas de `isAgreementBetter`

2024-04-03 10:53 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/CommonIndemniteDepart/steps/Resultat/components/ForMoreInfo.tsx
>          {message}
On aurait peut être pu garder ce composant en le renommer `ForMoreInfoIndemniteLicenciement`, car de la sorte, il est pas si utile que ça. Le but de ce composant était de garder la logique métier d'affichage

2024-04-03 10:53 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/CommonIndemniteDepart/steps/Salaires/components/TempsPartiel.tsx
> +        actuellement en cours de développement.
On utilise souvent cette logique, il faudrait voir comment la mettre ailleurs, c'est ce que je disais dans une des suggestion que j'avais fait plus haut

2024-04-03 10:53 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/CommonIndemniteDepart/steps/Resultat/components/DecryptResult.tsx
> +  label: string;
Ou alors reprendre le type : `IndemniteDepartType` que t'utilises à d'autre endroit

2024-04-03 10:53 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/CommonSteps/Agreement/store/store.ts
>        ]);
c'est top, du coup, ça règle la problématique dont on parlait pour la différenciation des events entre la rupture co et l'indemnité de licenciement

2024-04-03 10:53 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/CommonSteps/Agreement/store/store.ts
>        ]);
Car en soit, le toolName et le type sont assez similaire. Pourquoi avoir rename la variable ?

2024-04-03 10:53 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/CommonSteps/Agreement/store/store.ts
>        ]);
D'ailleurs, pour rester sur cette problématique des events, j'aimerai bien voir comment on pourrait refacto pour l'enlever de la logique des store, et que ça soit géré dans une classe à part entière. Je trouve ça tellement pas top de mettre la logique dans le store en fait

2024-04-03 10:53 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/IndemniteLicenciement/steps/Resultat/Eligible.tsx
> +// Do not optimize the following import
Il faudrait voir comment on peut régler ce soucis, c'est vraiment atroce 😢

A l'époque, j'avais essayé d'upgrade typescript, etc. Rien ne bougeait.

D'ailleurs dans le futur, il faudrait qu'on se fasse une tâche upgrade typescript + next.js

2024-04-03 10:53 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/IndemniteLicenciement/steps/Resultat/Eligible.tsx
> +// Do not optimize the following import
Même si malheuresement je ne pense pas que ça règle grand chose

2024-04-03 10:53 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/IndemniteLicenciement/steps/Resultat/Eligible.tsx
> +          ].concat(
J'aime bien cette approche, car ça permet au composant d'être assez générique entre les deux simulateurs ! Bien joué

2024-04-03 10:53 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/IndemniteLicenciement/steps/Resultat/index.tsx
> +  );
A l'époque, on avait gardé l'`init`, car ça permettait de re-update le résultat manuellement et le calculer si des éléments de la situation avait bougé. Je suis pas sûr d'avoir bien compris le mécanisme qui permet de gérer ce use-case

2024-04-03 10:53 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/IndemniteLicenciement/index.tsx
> +    />
C'est bien mieux comme ça 💪

2024-04-03 10:53 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/RuptureCoventionnelle/steps/Anciennete/index.tsx
Perso ça me choque pas de dupliquer l'information, car en soit d'un point de vue métier, il y a quand même une approche différente. 

La problématique est que lorsqu'il faudra modifier un texte, il faudra penser aux deux occurences (sur l'indemnité et la rupture)

2024-04-03 10:53 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/RuptureCoventionnelle/steps/Resultat/utils.ts
ça pour la rupture pro, on le garde ?

on avait la problématique avec le cdi d'opération également

2024-04-03 10:53 UTC, maxgfr commented on packages/code-du-travail-frontend/src/outils/types.ts
> +  RUPTURE_CONVENTIONNELLE = "Indemnité de rupture conventionnelle",
Ok je vois, pourquoi on a rebrand en type le toolName

2024-04-03 10:53 UTC, maxgfr commented on packages/code-du-travail-modeles/src/modeles/base/__tests__/rupture-conventionnelle/calculate.spec.ts
> +      "contrat salarié - indemnité de licenciement - ancienneté en année"
Pourquoi avoir remis les `-`

2024-04-03 10:53 UTC, maxgfr commented on packages/code-du-travail-modeles/src/modeles/base/__tests__/rupture-conventionnelle/calculate.spec.ts
> +      "contrat salarié - indemnité de licenciement - ancienneté en année"
C'était mieux avec la logique de namespace avec les `.`

2024-04-03 11:44 UTC, Viczei approved these changes

2024-04-03 11:46 UTC, Viczei commented on packages/code-du-travail-modeles/src/modeles/base/__tests__/rupture-conventionnelle/calculate.spec.ts
> +      "contrat salarié - indemnité de licenciement - ancienneté en année"
C'est vrai qu'il faudrait uniformiser

2024-04-05 12:49 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/CommonIndemniteDepart/steps/ContratTravail/store/store.ts
> +              : PublicodesSimulator.RUPTURE_CONVENTIONNELLE;
C'est assez logique ici. Le `PublicodesSimulator` est situé dans le modèle. Il liste l'ensemble des simulateurs supportés par nos modèles (Préavis de retraitre, indemnité licenciement, rupture co)
Le `IndemniteDepartType` quand à lui permet de paramétrer la base commune entre Indemnité licenciement et Rupture co. 
Il est donc compliqué d'en faire qu'un seul.

2024-04-05 12:50 UTC, m-maillot commented on packages/code-du-travail-frontend/pages/outils/index.tsx
> +    const isProd = process.env.NEXT_PUBLIC_SENTRY_ENV === "production"
Mais oui ! Comme je suis passé à coté de ça 🤪

2024-04-05 12:55 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/CommonIndemniteDepart/steps/Resultat/components/FilledElements.tsx
> +                      * {item.detail}
Ha oui ! Bien vu... ça ne va pas m'aider ça 😅

2024-04-05 12:58 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/CommonIndemniteDepart/steps/Resultat/components/FilledElements.tsx
> +                      * {item.detail}
En fait, je le gère dans les composants de chaque simu. Mais il y avait bien un bug car j'avais inversé une condition :)

2024-04-05 13:14 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/CommonIndemniteDepart/steps/Resultat/components/ForMoreInfo.tsx
>          {message}
Yep, je supprime le composant qui n'a plus lieu d'exister. Chaque simu implémente les infos qu'il a besoin et la rupture a besoin de beaucoup moins d'info à ce niveau là.

2024-04-05 13:17 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/IndemniteLicenciement/steps/Resultat/index.tsx
> +  );
Il est toujours là mais un cran plus haut : https://github.com/SocialGouv/code-du-travail-numerique/pull/5703/files#diff-cc75f0b01797185afb8cea6c219473d616b5aa32a562b1703330bbc5496655cdR21

J'ai soustrait une partie du composant initial pour le rendre customisable pour chaque simulateur.

2024-04-05 13:17 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/IndemniteLicenciement/steps/Resultat/Eligible.tsx
> +// Do not optimize the following import
Je n'ai pas regardé plus loin, on avait déjà regardé et on avait fait chou blanc... mais c'est vrai que c'est fastidieux !

2024-04-05 13:23 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/RuptureCoventionnelle/steps/Anciennete/index.tsx
Les deux nouveaux ancienneté partagent pas mal leur composant. On pourrait en partager encore plus. Mais sur les quelques questions de cette écran, les dates changent car on ne demande pas la même chose (label) et on en demande une en moins. La partie en commun est celle sur les absences où j'ai utilisé le composant commun pour la liste des absences. Je pense qu'il est préférable de jouer sur la composition de composants ici que sur des conditions pour changer les labels et ajouter des règles spécifiques.

2024-04-05 13:28 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/RuptureCoventionnelle/steps/Resultat/utils.ts
je n'ai pas compris ce que tu voulais dire.

2024-04-05 13:42 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/base/__tests__/rupture-conventionnelle/calculate.spec.ts
> +      "contrat salarié - indemnité de licenciement - ancienneté en année"
En fait le comportement a changé ici. Avant on remontait en missingArgs manuellement (dans le ts) quand il manquait une des dates sur l'ancienneté. Sauf que quand on est sur la page info, on veut pouvoir faire un calculate sans passer de dates. On a donc changer sur l'indemnité de licenciement pour ne plus remonter des missingArgs depuis le TS. Ici c'est pareil. Du coup, le missingArgs est remonté par publicode où l'on a encore le replace des `.` par `-`. Pour le modifier, il faudrait basculer le préavis de retraitre pour ne plus utiliser hook form.

2024-04-05 13:43 UTC, m-maillot commented on packages/code-du-travail-frontend/src/outils/CommonIndemniteDepart/steps/Salaires/components/TempsPartiel.tsx
> +        actuellement en cours de développement.
Je serais partant de le faire dans un second refacto. Car j'ai peur aussi que le métier demande plus de modifications sur les textes et qu'en fait on doit revoir nos composants plus globalement. Ca te va ?

2024-04-16 15:24 UTC, carolineBda submitted a review, later dismissed
Régression sur la page résultat quand on coche licenciement pour inaptitude :

![Screenshot from 2024-04-16 17-20-34](https://github.com/SocialGouv/code-du-travail-numerique/assets/4971715/dd4308f1-bcb3-47d3-aa3b-e4945296f520)

2024-04-29 07:39 UTC, maxgfr approved these changes

2024-04-29 07:56 UTC, merged