feat: desinstaller ancienne contrib
SocialGouv/code-du-travail-numerique pull request #5712
Opened 2024-03-25 08:38 UTC by Viczei

2024-03-25 09:33 UTC, maxgfr approved these changes
Top, mais il faut la passer en draft la PR

2024-03-25 09:33 UTC, maxgfr commented
Et il y a des types et tests qui failent encore

2024-03-26 15:45 UTC, carolineBda commented on packages/code-du-travail-frontend/src/contributions/ContributionContent.tsx
> -      {"raw" in contribution ? (
faut garder ça ! c'est pour afficher les ficher SP !!!

2024-03-26 15:47 UTC, carolineBda requested changes
Il manque tout le clean de l'API. IL faut chercher `split` cette notion ne soit plus exister

2024-03-27 09:58 UTC, Viczei commented on packages/code-du-travail-frontend/src/contributions/ContributionContent.tsx
> -      {"raw" in contribution ? (
dac

2024-04-02 07:20 UTC, carolineBda commented on packages/code-du-travail-frontend/src/api/modules/contributions/queries.ts
> -        },
je penses qu'on a plus besoin de la clause
 ```
   bool: {
                  must_not: {
                    exists: {
                      field: "idcc",
```

2024-04-02 07:20 UTC, carolineBda commented on packages/code-du-travail-frontend/src/api/modules/contributions/service.ts
> +  (contrib.idcc && contrib.idcc === "0000") || !contrib.idcc;
```suggestion
contrib.idcc === "0000"
```

2024-04-02 07:22 UTC, carolineBda commented on packages/code-du-travail-frontend/src/contributions/Contribution.tsx
> -import SearchConvention from "../../src/conventions/Search";
`SearchConvention` n'est plus utilisé on peut le supprimer

2024-04-02 07:23 UTC, carolineBda commented on packages/code-du-travail-frontend/src/contributions/ContributionContent.tsx
> +      {isFicheSP ? (
:heart_eyes:

2024-04-02 07:26 UTC, carolineBda commented on packages/code-du-travail-frontend/src/conventions/Convention/Contributions.js
> -import Mdx from "../../common/Mdx";
je crois que le composant Mdx n'est plus utilisé ?

2024-04-02 09:48 UTC, Viczei commented on packages/code-du-travail-frontend/src/conventions/Convention/Contributions.js
> -import Mdx from "../../common/Mdx";
en effet

2024-04-02 09:51 UTC, Viczei commented on packages/code-du-travail-frontend/src/conventions/Convention/Contributions.js
> -import Mdx from "../../common/Mdx";
On ne peut pas encore retirer rehype par contre car il est en encore utilisé dans les pages infos

2024-04-04 09:30 UTC, m-maillot approved these changes

2024-04-04 09:30 UTC, m-maillot commented on packages/code-du-travail-frontend/src/api/modules/contributions/service.ts
> +  console.log("allGenerics", allGenerics);
```suggestion

```

log à supprimer :)

2024-04-11 09:52 UTC, carolineBda approved these changes

2024-04-12 09:42 UTC, merged