feat(RC): implement 2216 and 1702
SocialGouv/code-du-travail-numerique pull request #5759
Opened 2024-04-08 13:31 UTC by carolineBda

2024-04-10 09:25 UTC, maxgfr approved these changes

2024-04-12 12:44 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/1702_ouvriers_travaux_public/__tests__/rupture-conventionnelle/calculate.spec.ts
> +    );
```suggestion
    const { missingArgs } = engine.calculate(
      input,
      "contrat salarié . indemnité de licenciement . résultat conventionnel"
    );
    expect(result.missingArgs).toHaveNextMissingRule(
      "contrat salarié . convention collective . ouvriers travaux public . indemnité de licenciement . age"
    );
```

on peut encore plus simplifier :)

2024-04-12 12:44 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/2120_banque/__tests__/rupture-conventionnelle/calculate.spec.ts
> +    );
```suggestion
    const { missingArgs } = engine.calculate(
      input,
      "contrat salarié . indemnité de licenciement . résultat conventionnel"
    );
    expect(result.missingArgs).toHaveNextMissingRule(
      "contrat salarié . convention collective . banque . catégorie professionnelle"
    );
```

2024-04-12 12:44 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/1702_ouvriers_travaux_public/__tests__/rupture-conventionnelle/calculate.spec.ts
> +  test("Le legal est toujours plus favorable", () => {
Je pense qu'il est plus judicieux de cibler nos tests sur la convention collective ici. Dans le cas de la 1702, on veut valider que le montant retourné pour la convention collective est celui du licenciement autres.

On peut garder que le montant du légal retourné est celui attendu mais le texte du test devrait cibler cet objectif à mon avis. Dans le cas où demain la formule du légal change, cela ne devrait pas impacter ce test pour moi car on est en train de tester la CC et non la comparaison légal / CC.

2024-04-12 12:44 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/2120_banque/__tests__/rupture-conventionnelle/calculate.spec.ts
> +    "$#) Le légal est toujours plus favorable avec: catégorie pro $categoriePro, entryDate $entryDate,  salaire: $salary => $expectedAgreement",
Pareil, ici, je ciblerai des cas pour challenger la CC et expliciterai les cas dans les tests.

2024-04-12 12:44 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/2216_commerces_detail_alimentation/__tests__/rupture-conventionnelle/calculate.spec.ts
> +    );
```suggestion
    const { missingArgs } = engine.calculate(
      input,
      "contrat salarié . indemnité de licenciement . résultat conventionnel"
    );
    expect(missingArgs).toHaveNextMissingRule(
      "contrat salarié . convention collective . commerce gros et detail alimentation . indemnité de licenciement . catégorie professionnelle"
    );
```

2024-04-12 12:44 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/2216_commerces_detail_alimentation/__tests__/rupture-conventionnelle/calculate.spec.ts
> +  test("Employés et ouvriers, personnel de livraison est identique au légal", () => {
Idem, je pense qu'il ne faut pas se référer au légal mais ce qui est attendu dans le calcul de la convention collective.

2024-04-12 12:44 UTC, m-maillot commented on packages/code-du-travail-modeles/src/modeles/conventions/2216_commerces_detail_alimentation/__tests__/rupture-conventionnelle/calculate.spec.ts
> +  test("Cadres est plus favorable que le légal", () => {
Idem, je pense qu'il ne faut pas se référer au légal mais ce qui est attendu dans le calcul de la convention collective.

2024-04-12 16:16 UTC, maxgfr commented on packages/code-du-travail-modeles/src/modeles/conventions/2216_commerces_detail_alimentation/dismissal-reason.ts
> +      },
Je suis absolument d'accord avec ce que t'as fait là, mais il y a un truc que je comprends pas mais sur la 573, pourquoi on teste le Oui aussi. Car le problème de cette approche génère des missing-args.

Au niveau du résultat, ça ne pose pas de soucis, et je suis d'accord avec ton approche Caro, car dans tous les cas on prend le moins favorable, c'est d'ailleurs ce que j'ai fait avec mes 5 CCs implémentés.

@m-maillot faudrait-il tester tous les uses-case en mettant le Oui et Non quitte à avoir des missings-args ou faire de manière optimisé 

(Avant, je testais les deux, mais j'ai refacto)

2024-04-15 14:22 UTC, Viczei approved these changes

2024-04-17 13:26 UTC, maxgfr commented on packages/code-du-travail-modeles/src/modeles/conventions/2216_commerces_detail_alimentation/dismissal-reason.ts
> +      },
Rectification : Il vaut mieux tester tous les uses-cases quittte à avoir des missings-args pour être sûr de ne pas passer à côté

2024-04-17 13:26 UTC, maxgfr requested changes

2024-04-17 13:26 UTC, maxgfr commented on packages/code-du-travail-modeles/src/modeles/conventions/2216_commerces_detail_alimentation/dismissal-reason.ts
> +      },
Dans ce cas là, il faut ajouter ce use case là

2024-04-17 13:40 UTC, maxgfr approved these changes

2024-04-17 13:40 UTC, maxgfr commented on packages/code-du-travail-modeles/src/modeles/conventions/2216_commerces_detail_alimentation/dismissal-reason.ts
> +      },
perfecto !!

2024-04-17 14:15 UTC, merged