Première passe pour la génération dynamique de components
SocialGouv/code-du-travail-numerique pull request #578
Opened 2019-03-06 17:02 UTC by UnbearableBear

Vous en pensez quoi ??

2019-03-06 18:11 UTC, lionelB commented
un lien vers les definitions qui permet de mieux comprendre comment les contenu sont organisés https://www.data.gouv.fr/fr/datasets/r/d1b0f744-c997-48d2-9ec4-1c64e82202d6

2019-03-07 19:52 UTC, revolunet commented
😍 Clean code 👍 

Je n'ai juste pas compris ce qu'était `SrOnly` 

Pour les variables CSS, ce serait compliqué de les déplacer dans le package css ?

https://www.npmjs.com/package/postcss-external-vars

2019-03-07 19:53 UTC, revolunet commented
tout ça :)

<img width="170" alt="capture d ecran 2019-03-07 a 20 47 45" src="https://user-images.githubusercontent.com/124937/53985043-f660b980-411a-11e9-94fa-14bb9bc8294a.png">

2019-03-07 20:01 UTC, revolunet commented
Ce serait plus "idiomatique" d'avoir un composant `<FicheServicePublic/>` qu'une fonction `ficheBuilder` ?

2019-03-11 09:52 UTC, UnbearableBear commented
Yes j'ai hésité un petit bout de temps et comme c'était récursif je me suis dit qu'un component récursif c'est pas commun donc je vais juste faire une fonction mais, effectivement, ça fait bizarre au final

2019-03-11 09:53 UTC, UnbearableBear commented
> 😍 Clean code 👍
> 
> Je n'ai juste pas compris ce qu'était `SrOnly`
> 
> Pour les variables CSS, ce serait compliqué de les déplacer dans le package css ?
> 
> https://www.npmjs.com/package/postcss-external-vars

Yes mais je le fais dans une PR à part juste après alors ?

2019-03-12 08:19 UTC, lionelB reviewed
désolé pour le retard, juste des petites remarques

2019-03-12 08:19 UTC, lionelB commented on packages/code-du-travail-ui/src/Article.js
> +          <h1 className="article__title">{title}</h1>
Je pense que ce changement ne devrait pas être dans cette PR (même si effectivement remplacer le div par un H1 et une bonne chose)

2019-03-12 08:19 UTC, lionelB commented on packages/code-du-travail-frontend/src/ficheBuilder/utils/index.js
> +export { default as getText } from "./getText";
Je pense qu'il serait plus pratique de regrouper les 2 fonctions directement dans le fichiers plutôt que dans des fichiers séparés.

2019-03-12 08:19 UTC, lionelB commented on packages/code-du-travail-frontend/src/ficheBuilder/utils/getText.js
> +export default function getText(element = { text: "" }, joint = " ") {
joint pourrait plutot s'appellé `joinChar`

2019-03-12 08:32 UTC, revolunet commented on packages/code-du-travail-frontend/src/ficheBuilder/utils/getText.js
> +export default function getText(element = { text: "" }, joint = " ") {
separator ?

2019-03-12 08:36 UTC, lionelB commented on packages/code-du-travail-frontend/pages/fiche-service-public.js
> +            {data._source.raw && (
dans quel cas il peut ne pas y avoir de raw ?

2019-03-12 08:40 UTC, lionelB commented on packages/code-du-travail-frontend/src/FicheServicePublic/components/index.js
> +export { default as Accordion } from "./Accordion";
Est ce qu'on peut se passer de ce genre de fichier ?et juste importer les composant directement ?
Je comprend l'utilité pour des lib, mais dans notre code, je ne vois pa l'utilité de ce genre de fichier.

2019-03-12 08:42 UTC, lionelB commented on packages/code-du-travail-frontend/src/FicheServicePublic/utils/index.js
> +export { default as getText } from "./getText";
je pense que tu peux regrouper les fonction dans ce fichier,  leur taille ne nécessite pas un fichier dédié

2019-03-12 08:46 UTC, lionelB commented on packages/code-du-travail-frontend/src/FicheServicePublic/index.js
> +  const children = <ElementBuilder data={data.$} headingLevel={headingLevel} />;
je trouve le split des 2 switch un peu  perturbant, 
Si le but était de ne pas répéter la  `<ElementBuilder data={data.$} headingLevel={headingLevel} />;`
en faire un fonction 
ensuite il est possible de grouper les cases comme tu l'a fait plus haut
```
    case "SousChapitre": 
    case "Texte":  
    case "LienIntra": 
    case "LienInterne":
    case "BlocCas":
    case "Cas":
      return children;
```

2019-03-12 08:49 UTC, lionelB requested changes
Désolé pour la revue tardive, pas de grosses modif.

2019-03-12 10:27 UTC, UnbearableBear commented on packages/code-du-travail-ui/src/Article.js
> +          <h1 className="article__title">{title}</h1>
🙏

2019-03-12 10:27 UTC, UnbearableBear commented on packages/code-du-travail-frontend/src/ficheBuilder/utils/index.js
> +export { default as getText } from "./getText";
👍

2019-03-12 10:29 UTC, UnbearableBear commented on packages/code-du-travail-frontend/pages/fiche-service-public.js
> +            {data._source.raw && (
👍

2019-03-12 10:29 UTC, UnbearableBear commented on packages/code-du-travail-frontend/src/FicheServicePublic/index.js
> +  const children = <ElementBuilder data={data.$} headingLevel={headingLevel} />;
👍

2019-03-12 10:59 UTC, UnbearableBear commented on packages/code-du-travail-frontend/pages/fiche-service-public.js
> +            {data._source.raw && (
Alors si ça peut arriver dans le cas d'une 404 en fait !

2019-03-12 11:00 UTC, UnbearableBear commented on packages/code-du-travail-frontend/src/FicheServicePublic/components/index.js
> +export { default as Accordion } from "./Accordion";
👍

2019-03-12 11:00 UTC, UnbearableBear commented on packages/code-du-travail-frontend/src/FicheServicePublic/utils/index.js
> +export { default as getText } from "./getText";
👍

2019-03-12 18:25 UTC, lionelB commented on packages/code-du-travail-frontend/src/FicheServicePublic/components/__tests__/Accordion.test.js
> +      <Accordion data={accordionDataMock} headingLevel={headingLevel} />
tu peux passer directement le heading level au compo (en general pour les valeur simple type string / number)

2019-03-12 18:27 UTC, lionelB commented on packages/code-du-travail-frontend/src/FicheServicePublic/components/__tests__/Accordion.test.js
> +    expect(container.querySelectorAll("h3")).toHaveLength(4);
plutot que de vérifier à la main si les h3 sont bon, j'aurais tendance à utiliser seulement les snapshots comme dans le test plus bas

2019-03-14 10:02 UTC, lionelB commented on packages/code-du-travail-data/dataset/fiches_service_public/index.js
> +const fichesPro = getFiches("./data/vosdroits-professionnels")
tu feras attention quand on va merger dans le PR data que tes modifs soient pas perdues

2019-03-14 10:06 UTC, lionelB commented on packages/code-du-travail-frontend/src/FicheServicePublic/components/__tests__/ouSAdresserData.mock.js
> +export const classicData = {
les mock ils sont en json ou en js ?

2019-03-14 10:09 UTC, lionelB commented on packages/code-du-travail-frontend/src/FicheServicePublic/css/components/index.js
> +// Only pure css stuff here, no markup !
![nope-octopus](https://user-images.githubusercontent.com/160320/54348572-9e114680-4649-11e9-859a-052feee80542.gif)
Je préférerai que ça aille plutôt dans le packages @cdt/ui

2019-03-14 10:13 UTC, lionelB commented on packages/code-du-travail-frontend/src/FicheServicePublic/css/variables.js
> +const baseColors = {
ca me paraitrait plus logique que ce fichier devrait plutôt être dans @cdt/ui pour pouvoir etre utiliser pas les composant ui et le frontend, pas juste dans FicheServicePublic

2019-03-14 10:15 UTC, lionelB commented on packages/code-du-travail-frontend/src/FicheServicePublic/index.js
> +const parseChildren = (children, headingLevel) => (
t'as fait une fonction finalement ? :)

2019-03-14 10:18 UTC, lionelB commented on packages/code-du-travail-frontend/src/FicheServicePublic/index.js
> +      if (data.$.find(child => child.name === "Chapitre")) {
Est ce qu'on pourrait pas tester le niveau via headingLevel ?
Les accordéon de chapitre ne sont en général présent qu'au sous niveau 1

2019-03-14 10:19 UTC, lionelB commented on packages/code-du-travail-frontend/src/FicheServicePublic/utils/index.js
> +// beware, this one is recursive
Est ce qu'on pourrait pas bouger le fichier au niveau au dessus et l'appeller `utils.js`

2019-03-14 10:21 UTC, lionelB requested changes
Nickel les tests 👍 
juste 2 trois remarques, et les 2 premiers commit de la branche sont a virer (on peut le faire ensemble)

2019-03-14 10:23 UTC, UnbearableBear commented on packages/code-du-travail-data/dataset/fiches_service_public/index.js
> +const fichesPro = getFiches("./data/vosdroits-professionnels")
ah merde c'est vrai ça j'aurais du le faire dans l'autre PR celui-là. Je fais un rebase tout le temps donc ça posera pas de problème a priori ceci dit.

2019-03-14 10:23 UTC, UnbearableBear commented on packages/code-du-travail-frontend/src/FicheServicePublic/components/__tests__/ouSAdresserData.mock.js
> +export const classicData = {
json je corrige ç

2019-03-14 10:27 UTC, UnbearableBear commented on packages/code-du-travail-frontend/src/FicheServicePublic/css/variables.js
> +const baseColors = {
Je le bouge !

2019-03-14 10:58 UTC, UnbearableBear commented on packages/code-du-travail-data/dataset/fiches_service_public/index.js
> +const fichesPro = getFiches("./data/vosdroits-professionnels")
Heuu pas normal ça

2019-03-15 10:10 UTC, merged