Ajout des références juridiques aux fiches SP
SocialGouv/code-du-travail-numerique pull request #599
Opened 2019-03-18 17:40 UTC by UnbearableBear

Manque juste un test ?

2019-03-18 17:42 UTC, UnbearableBear commented on packages/code-du-travail-data/dataset/synonyms.json
> +  "document unique d'évaluation des risques professionnels, duerp",
Je ne sais pas trop pourquoi il y a ça ici mais, c'est grave ?

2019-03-18 18:24 UTC, lionelB commented on packages/code-du-travail-data/dataset/synonyms.json
> +  "document unique d'évaluation des risques professionnels, duerp",
un soucis de rebase ?

2019-03-18 18:27 UTC, lionelB commented on packages/code-du-travail-data/dataset/fiches_service_public/parseReference.js
> +const makeArticleData = num => ({
`makeArticleRef` me parait plus approprié

2019-03-18 18:28 UTC, lionelB commented on packages/code-du-travail-data/dataset/fiches_service_public/parseReference.js
> +      return {
ca pourrait être bien d'avoir l'équivalent de `makeArticleRef`

2019-03-18 18:28 UTC, lionelB commented on packages/code-du-travail-data/dataset/fiches_service_public/parseReference.js
> +        type: "journal-officiel",
ca pourrait etre bien d'avoir l'équivalent de `makeArticleRef`

2019-03-18 18:29 UTC, lionelB commented on packages/code-du-travail-data/dataset/fiches_service_public/parseReference.js
> +    if (isCodeDuTravail(qs.cidTexte)) {
je pense que ca serait plus lisible avec un switch.

2019-03-18 18:30 UTC, lionelB commented on packages/code-du-travail-data/dataset/fiches_service_public/parseReference.js
> +    let { ID: id, URL: url } = reference._;
nit: il faudrait utiliser `const`

2019-03-18 18:30 UTC, lionelB commented on packages/code-du-travail-data/dataset/fiches_service_public/parseReference.js
> +const parseReference = reference => {
ca pourrait etre bien d'avoir un exemple d'url que la fonction parse + un commentaire

2019-03-18 18:35 UTC, lionelB commented on packages/code-du-travail-data/dataset/fiches_service_public/parseReference.js
> +    if (isCodeDuTravail(qs.cidTexte)) {
``` js
// pseudo - code
const type = getType(url)
switch(type):
   case : "cdt":
      //...
   case "ccn": 
     // ..
   case "Jo":
   // ...
```

2019-03-18 18:37 UTC, lionelB commented on packages/code-du-travail-data/dataset/fiches_service_public/parseReference.js
> +  }
il manque un `return []` pour avoir une unicité des type de retour

2019-03-18 18:38 UTC, lionelB commented on packages/code-du-travail-data/dataset/fiches_service_public/parseReference.js
> +        num = getArticleNumFromId(qs.idArticle);
que se passe t'il si num est false (cf le test https://github.com/SocialGouv/code-du-travail-numerique/pull/599/files#diff-678630ff714bf4cc7fd7744243845e6bR15)

2019-03-18 19:50 UTC, lionelB commented on packages/code-du-travail-data/search/indexing/create_indexes.py
> +            '_source': removeId(body),
@revolunet est ce que le removeId est la "au cas où" ou il y des cas dans lequel on a déja une cle `_id` ?

2019-03-18 19:53 UTC, lionelB commented on packages/code-du-travail-data/search/indexing/create_indexes.py
> +            '_id': body.get("_id")
qu'est ce qu'il se passe pour les autres contenu qui non pas de clé id ? est ce que ES génère une clé si _id vaut `undefined` ?

2019-03-18 19:54 UTC, lionelB commented on packages/code-du-travail-frontend/pages/fiche-service-public.js
> +              <>
qu'est ce que `<>` ?

2019-03-18 19:54 UTC, lionelB commented on packages/code-du-travail-frontend/pages/fiche-service-public.js
> +                {Boolean(data._source.references_juridiques.length) && (
ca me parit plus clair d'avoir `data._source.references_juridiques.length > 0`

2019-03-18 19:55 UTC, lionelB commented on packages/code-du-travail-frontend/pages/fiche-service-public.js
> +                    data={data._source.references_juridiques}
la props devrait plutôt s'appeler `references`

2019-03-18 19:56 UTC, lionelB commented on packages/code-du-travail-frontend/src/FicheServicePublic/components/Accordion.js
> +          <>
a quoi sert le `<>` ?

2019-03-18 20:03 UTC, lionelB commented on packages/code-du-travail-frontend/src/FicheServicePublic/index.js
> +      // they are empty links sometimes...
typo : there

2019-03-18 20:05 UTC, lionelB commented on packages/code-du-travail-frontend/src/HierarchieDesNormes/components/ReferencesJuridiques.js
> +  <Link route="code-du-travail" params={{ slug }}>
il faut ajouter un  `passHref`au Link pour que celui-ci transmette correctement le href au `<a>`

2019-03-18 20:08 UTC, lionelB commented on packages/code-du-travail-frontend/src/HierarchieDesNormes/components/ReferencesJuridiques.js
> +  <ReferenceWrapper
ReferenceWrapper me parait un peu confus, ReferenceLink ou ReferenceHref pour garder le lien avec la balise `<a>` ?

2019-03-18 20:09 UTC, lionelB commented on packages/code-du-travail-frontend/src/HierarchieDesNormes/components/ReferencesJuridiques.js
> +    {data.map(
est ce que ca ne devrait pas etre dans un  `<ul>` / `<li>`

2019-03-18 20:09 UTC, lionelB commented on packages/code-du-travail-frontend/src/HierarchieDesNormes/components/ReferencesJuridiques.js
> +  svg {
le svg vient d'ou ?

2019-03-18 20:10 UTC, lionelB commented on packages/code-du-travail-frontend/src/HierarchieDesNormes/index.js
> +  return <ReferencesJuridiques data={data} />;
data serait plus porteur de sens avec un nom comme `textes` ou `réferences`

2019-03-18 20:11 UTC, lionelB commented on packages/code-du-travail-frontend/src/HierarchieDesNormes/index.js
> +// import styled from "styled-components";
tu peux supprimer le code commenté.

2019-03-18 20:12 UTC, lionelB commented on packages/code-du-travail-frontend/src/HierarchieDesNormes/index.js
> +import TYPE_TEXTE from "./typeTexte";
l'import ne sert pas

2019-03-18 20:13 UTC, lionelB commented on packages/code-du-travail-frontend/src/HierarchieDesNormes/typeTexte.js
> +export default {
```js
const type2Route = {} 
export default type2Route 
```
permet de véhiculer plus de sens

2019-03-18 20:13 UTC, lionelB commented on packages/code-du-travail-frontend/src/HierarchieDesNormes/typeTexte.js
> +  journalOfficiel: "journal-officiel"
on ne gere pas ce genre de routes

2019-03-18 20:13 UTC, lionelB commented on packages/code-du-travail-frontend/src/HierarchieDesNormes/typeTexte.js
> +  conventionCollective: "convention-collective",
on ne gere pas ce genre de routes

2019-03-18 20:15 UTC, lionelB requested changes
@UnbearableBear j'ai fini la review. N'oublie pas de modifier les données qu'on utilise dans l'api pour les tests et aussi le tableau des tests unitaire (des cellules références les slug des articles car ils vont changer suite à ta PR

2019-03-19 09:27 UTC, UnbearableBear commented on packages/code-du-travail-data/dataset/fiches_service_public/parseReference.js
> +const makeArticleData = num => ({
👍

2019-03-19 09:28 UTC, UnbearableBear commented on packages/code-du-travail-data/dataset/fiches_service_public/parseReference.js
> +  }
👍

2019-03-19 10:12 UTC, UnbearableBear commented on packages/code-du-travail-data/dataset/fiches_service_public/parseReference.js
> +const parseReference = reference => {
C'est un objet !
```{
  "type":"element",
  "name":"Reference",
  "_":{
    "type":"Texte de référence",
    "URL":"https://www.legifrance.gouv.fr/affichCodeArticle.do?idArticle=LEGIARTI000033020517&cidTexte=LEGITEXT000006072050",
    "ID":"R45052"
  },
  "$":[
    {
      "type":"element",
      "name":"Titre",
      "$":[
        {
          "type":"text",
          "$":"Code du travail : article L3121-1"
        }
      ]
    }
  ]
}```

2019-03-19 10:15 UTC, UnbearableBear commented on packages/code-du-travail-data/dataset/fiches_service_public/parseReference.js
> +        num = getArticleNumFromId(qs.idArticle);
Bonne question !

2019-03-19 10:17 UTC, UnbearableBear commented on packages/code-du-travail-data/dataset/synonyms.json
> +  "document unique d'évaluation des risques professionnels, duerp",
Ceci dit c'est étrange parce que ma version semble coller mieux au sigle !

2019-03-19 10:20 UTC, UnbearableBear commented on packages/code-du-travail-frontend/pages/fiche-service-public.js
> +              <>
c'est un react fragment https://reactjs.org/docs/fragments.html#short-syntax

2019-03-19 10:20 UTC, UnbearableBear commented on packages/code-du-travail-frontend/pages/fiche-service-public.js
> +                {Boolean(data._source.references_juridiques.length) && (
👍

2019-03-19 10:21 UTC, UnbearableBear commented on packages/code-du-travail-frontend/pages/fiche-service-public.js
> +                    data={data._source.references_juridiques}
très bien references !

2019-03-19 10:24 UTC, UnbearableBear commented on packages/code-du-travail-frontend/src/FicheServicePublic/components/Accordion.js
> +          <>
C'est un fragment https://reactjs.org/docs/fragments.html#short-syntax pour avoir deux enfants dans mettre une div en plus

2019-03-19 10:25 UTC, UnbearableBear commented on packages/code-du-travail-frontend/src/HierarchieDesNormes/components/ReferencesJuridiques.js
> +  <Link route="code-du-travail" params={{ slug }}>
Ah putain super ! Merci !

2019-03-19 10:33 UTC, UnbearableBear commented on packages/code-du-travail-frontend/src/HierarchieDesNormes/components/ReferencesJuridiques.js
> +  <ReferenceWrapper
ReferenceLink, très bien !

2019-03-19 10:34 UTC, UnbearableBear commented on packages/code-du-travail-frontend/src/HierarchieDesNormes/components/ReferencesJuridiques.js
> +    {data.map(
Très bonne idée !

2019-03-19 10:35 UTC, UnbearableBear commented on packages/code-du-travail-frontend/src/HierarchieDesNormes/components/ReferencesJuridiques.js
> +  svg {
de l'icone, je sais pas trop comment le target sinon

2019-03-19 10:35 UTC, UnbearableBear commented on packages/code-du-travail-frontend/src/HierarchieDesNormes/index.js
> +// import styled from "styled-components";
yeeeep

2019-03-19 10:35 UTC, UnbearableBear commented on packages/code-du-travail-frontend/src/FicheServicePublic/index.js
> +      // they are empty links sometimes...
👍

2019-03-19 10:42 UTC, UnbearableBear commented on packages/code-du-travail-frontend/src/HierarchieDesNormes/index.js
> +  return <ReferencesJuridiques data={data} />;
👍

2019-03-19 10:43 UTC, UnbearableBear commented on packages/code-du-travail-frontend/src/HierarchieDesNormes/typeTexte.js
> +  conventionCollective: "convention-collective",
oh mais c'est pas des routes !

2019-03-19 14:59 UTC, revolunet commented on packages/code-du-travail-data/search/indexing/create_indexes.py
> +            '_source': removeId(body),
c'était pour gérer le cas ou on veut forcer l'id dans ES. s'il est fourni dans body, on l'utilise, sinon on fait comme dab

2019-03-19 14:59 UTC, revolunet commented on packages/code-du-travail-data/search/indexing/create_indexes.py
> +            '_id': body.get("_id")
oui

2019-03-19 15:14 UTC, lionelB commented on packages/code-du-travail-data/search/indexing/create_indexes.py
> +            '_source': removeId(body),
@revolunet  J'ai l'impression qu'on s'en sers pas dans cette PR, du coup je me demandais si on pouvais pas faire cette modif dans une autre PR dans laquelle on ferai la modif de l'id (à partir du slug) pour chaque document et ensuite modifier la route items pour qu'elle fasse un get et plus un search

2019-03-19 15:45 UTC, lionelB commented on packages/code-du-travail-frontend/pages/fiche-service-public.js
> +              <>
aha je connaissais pas, c'est trop bizarre :)

2019-03-19 15:46 UTC, revolunet commented on packages/code-du-travail-data/search/indexing/create_indexes.py
> +            '_source': removeId(body),
Oui ça peut être fait dans une autre PR

2019-03-20 10:12 UTC, lionelB commented on packages/code-du-travail-api/tests/cdtn_document_data.json
> +    "slug": "KALICONT000005635886",
plutot l'idcc

2019-03-20 10:14 UTC, UnbearableBear commented on packages/code-du-travail-api/tests/cdtn_document_data.json
> +    "slug": "KALICONT000005635886",
L'id de la convention collective ?
C'est ce qui commence par KALICONT non ? 
`idConvention=KALICONT000005635792` dans le xml des fiches SP

2019-03-20 10:15 UTC, lionelB commented on packages/code-du-travail-data/search/indexing/cdtn_documents.py
> +                '_id': 'kali--' + val['id'],
tu peux enlever les `_id` et mettre le idcc-val['num'] dans le slug ?

2019-03-20 10:18 UTC, UnbearableBear commented on packages/code-du-travail-data/search/indexing/cdtn_documents.py
> +                '_id': 'kali--' + val['id'],
ca vient d'ou le idcc-val ? Un objet dans le kali.json ressemble à ça:
``` 
{
    "id": "KALICONT000005635524",
    "titre": "Nouvelle Convention collective nationale des métiers de la transformation des grains du 9 novembre 2016 (Avenant n° 46 du 9 novembre 2016)",
    "etat": "VIGUEUR_NON_ETEN",
    "nature": "IDCC",
    "num": "1930",
    "date_publi": "2017-01-04T23:00:00.000Z",
    "mtime": 1496948810,
    "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635524"
  }
```

2019-03-20 10:18 UTC, lionelB commented on packages/code-du-travail-frontend/src/HierarchieDesNormes/components/ReferencesJuridiques.js
> +          {(texteConventionnel.type === TYPE_REFERENCE.codeDuTravail && (
switch ?

2019-03-20 10:19 UTC, UnbearableBear commented on packages/code-du-travail-data/search/indexing/cdtn_documents.py
> +                '_id': 'kali--' + val['id'],
ok !

2019-03-20 10:20 UTC, lionelB commented on packages/code-du-travail-frontend/src/HierarchieDesNormes/components/ReferencesJuridiques.js
> +  svg {
tu peux faire 
```jsx
const Icon = styled(ArticleIcon)`
    position: relative;
    top: 1px;
    vertical-align: middle;
    margin-right: ${spacing.base};
`
```

2019-03-20 10:26 UTC, lionelB commented on packages/code-du-travail-frontend/src/HierarchieDesNormes/components/ReferencesJuridiques.js
> +  svg {
idem pour ul  d'ailleur pour un reset du padding devrait suffire et le Li n'a pas de style il me semble
```
const List  = styled.ul`
  padding-left: 0;
  list-style-type:0;
}

2019-03-20 10:27 UTC, lionelB commented on packages/code-du-travail-frontend/src/HierarchieDesNormes/typeReference.js
> +const TYPE_REFERENCE = {
Un petit commentaire pour dire que c'est lié au fichier `@cdt/data...fiches_service_public/parseReference`

2019-03-20 11:30 UTC, UnbearableBear commented on packages/code-du-travail-frontend/src/HierarchieDesNormes/typeReference.js
> +const TYPE_REFERENCE = {
👍

2019-03-20 11:35 UTC, UnbearableBear commented on packages/code-du-travail-frontend/src/HierarchieDesNormes/components/ReferencesJuridiques.js
> +  svg {
Pas fan de masquer le ul derrière un "List" mais t'as raison pour le li, il n'a ni padding ni margin par défaut !

2019-03-20 12:01 UTC, UnbearableBear commented on packages/code-du-travail-frontend/src/HierarchieDesNormes/components/ReferencesJuridiques.js
> +          {(texteConventionnel.type === TYPE_REFERENCE.codeDuTravail && (
done mais bon je vais tout changer dans la PR suivante 👎

2019-03-20 14:48 UTC, revolunet approved these changes

2019-03-20 14:49 UTC, revolunet commented
@lionelB on te laisse merger si ok pour toi ?

2019-03-20 15:00 UTC, lionelB approved these changes

2019-03-20 15:02 UTC, merged