CI deployment
SocialGouv/code-du-travail-numerique pull request #605
Opened 2019-03-20 11:02 UTC by Virasack

A chaque fois que vous déploierez une branche, elle sera accessible sur : http://code-du-travail-numerique-<votre-nom-de-branche>.dev.factory.social.gouv.fr.
La branche master sera accessible sur: http://code-du-travail-numerique.ops.factory.social.gouv.fr.
Attention, vos futures branches devront avoir le format <votre_nom>-<nom-de-la-branche> car les "/" sont interdits.
Ils restent à discuter du stage de release et voir comment améliorer la vitesse de la pipeline grâce au cache

2019-03-20 11:37 UTC, lionelB commented
@Virasack merci!

2019-03-21 15:07 UTC, sboulkour requested changes
2 petits trucs à changer rien de très impactant.
Belle grosse PR haha Merci @Virasack ça déchire :)

2019-03-21 15:07 UTC, sboulkour commented on k8s/code-du-travail-api/deployment-code-du-travail-api.yml
> +      - image:  registry.gitlab.factory.social.gouv.fr/socialgouv/code-du-travail-numerique/api:${IMAGE_TAG}
Tu peux utiliser les variables $CI_REGISTRY_IMAGE ou $CI_REGISTRY, c'est plus safe en cas de changement de nom dans le repo, et je trouve que c'est aussi plu lisible.

2019-03-21 15:07 UTC, sboulkour commented on k8s/code-du-travail-api/deployment-code-du-travail-api.yml
> +      - image:  registry.gitlab.factory.social.gouv.fr/socialgouv/code-du-travail-numerique/api:${IMAGE_TAG}
Ah ben je viens de voir que tu l'utilise déjà dans d'autres fichier @Virasack, du coup y'a plus qu'à uniformiser :)

2019-03-21 15:07 UTC, sboulkour commented on k8s/code-du-travail-data/deployment-code-du-travail-data.yml
> +    image: registry.gitlab.factory.social.gouv.fr/socialgouv/code-du-travail-numerique/data:${IMAGE_TAG}
Idem : $CI_REGISTRY ou $CI_REGISTRY_IMAGE

2019-03-21 15:07 UTC, sboulkour commented on k8s/code-du-travail-frontend/deployment-code-du-travail-frontend.yml
> +      - image:  registry.gitlab.factory.social.gouv.fr/socialgouv/code-du-travail-numerique/frontend:${IMAGE_TAG}
Idem : $CI_REGISTRY ou $CI_REGISTRY_IMAGE

2019-03-21 15:07 UTC, sboulkour commented on k8s/elasticsearch/statefulset-elasticsearch-dev.yml
> +        image: registry.gitlab.factory.social.gouv.fr/socialgouv/code-du-travail-numerique/elasticsearch:${IMAGE_TAG}
Idem : $CI_REGISTRY ou $CI_REGISTRY_IMAGE

2019-03-21 15:07 UTC, sboulkour commented on k8s/elasticsearch/statefulset-elasticsearch.yml
> +        image: registry.gitlab.factory.social.gouv.fr/socialgouv/code-du-travail-numerique/elasticsearch:${IMAGE_TAG}
Idem : $CI_REGISTRY ou $CI_REGISTRY_IMAGE

2019-03-21 15:07 UTC, sboulkour commented on packages/code-du-travail-api/Dockerfile
> +ARG BASE_IMAGE=registry.gitlab.factory.social.gouv.fr/socialgouv/code-du-travail-numerique:${TAG_BASE_IMAGE}
Idem : $CI_REGISTRY ou $CI_REGISTRY_IMAGE

2019-03-21 15:07 UTC, sboulkour commented on packages/code-du-travail-frontend/Dockerfile
> +ARG BASE_IMAGE=registry.gitlab.factory.social.gouv.fr/socialgouv/code-du-travail-numerique:${TAG_BASE_IMAGE}
Idem : $CI_REGISTRY ou $CI_REGISTRY_IMAGE

2019-03-21 15:07 UTC, sboulkour commented on .gitlab-ci.yml
> +  - pip install pipenv==11.10.1
Peut-être le variabiliser ? C'est utilisé deux fois, et ça permettrait de l'avoir en haut du fichier avec les autres versions.

2019-03-21 16:20 UTC, lionelB commented on .gitlab-ci.yml
> +  - >-
c'est quoi cette notation `- >-` ?

2019-03-21 16:22 UTC, lionelB commented on .gitlab-ci.yml
> +    node packages/code-du-travail-api/tests/create_indexes.js
l'appel du script create_indexes.js n'est plus necessaire, car on l'a passé en `pretest`  dans les `npm scripts`

2019-03-21 16:23 UTC, sboulkour approved these changes

2019-03-21 16:24 UTC, lionelB commented on .gitlab-ci.yml
> +  - npx codecov --flags frontend
est ce qu'on pourrait pas dispatcher l'envoi du coverage dans un "after_script" dans les `test-cdtn-{api|frontend}` une fois le script de test à terminer ?

2019-03-21 16:28 UTC, Virasack commented on .gitlab-ci.yml
> +  - >-
C'est juste pour pouvoir sauter des lignes. La commande est plus lisible.
C'est mieux d'avoir 
- >-
    docker build
    --build-arg REGISTRY=$CI_REGISTRY_IMAGE
    --build-arg TAG_BASE_IMAGE=$CI_COMMIT_SHA
    -t "$CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHA" .

Plutôt que - docker build --build-arg REGISTRY=$CI_REGISTRY_IMAGE --build-arg TAG_BASE_IMAGE=$CI_COMMIT_SHA -t "$CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHA" .

2019-03-21 16:37 UTC, Virasack commented on .gitlab-ci.yml
> +  - npx codecov --flags frontend
Je pense que ça peut se faire

2019-03-21 16:47 UTC, lionelB commented on k8s/kibana/.deploy-kibana-k8s.yml
> +  - envsubst < k8s/kibana/service-kibana.yml > k8s/kibana/service-cdtn-kibana.yml
est ce qu'il manque pas un ingres pour kibana pour qu'il soit visible de l'extérieur ?
comment fait on pour l'auth ?

2019-03-22 10:14 UTC, Virasack commented on .gitlab-ci.yml
> +  - npx codecov --flags frontend
Cependant le problème avec after script, c'est que la commande est exécutée même si le test a foiré

2019-03-22 10:14 UTC, Virasack commented on .gitlab-ci.yml
> +  - >-
C'est pour prendre en compte le saut de ligne dans la commande

2019-03-22 10:15 UTC, Virasack commented on .gitlab-ci.yml
> +    node packages/code-du-travail-api/tests/create_indexes.js
OK je regarde ce qui a été fait et j'adapte

2019-03-22 10:58 UTC, lionelB commented on .gitlab-ci.yml
> +  - npx codecov --flags frontend
donc on laisse comme c'est :)

2019-03-22 11:19 UTC, Virasack commented on k8s/kibana/.deploy-kibana-k8s.yml
> +  - envsubst < k8s/kibana/service-kibana.yml > k8s/kibana/service-cdtn-kibana.yml
Comme j'ai pas les conf de l'actuel kibana et ce qu'il fait exactement.

2019-03-22 14:05 UTC, lionelB commented on k8s/kibana/.deploy-kibana-k8s.yml
> +  - envsubst < k8s/kibana/service-kibana.yml > k8s/kibana/service-cdtn-kibana.yml
oki on le rajoutera plus tard pour al partie prod

2019-03-27 13:54 UTC, douglasduteil commented
Let's add Deployment statuses and merge :)

2019-03-28 10:12 UTC, merged