feat(feedback): ajout du composant "Avez-vous trouvé une réponse à votre question"
SocialGouv/code-du-travail-numerique pull request #6121
Opened 2024-09-12 12:44 UTC by maxgfr

fix #6116
fix #6114

2024-09-12 12:45 UTC, maxgfr commented on packages/code-du-travail-frontend/src/modules/layout/index.tsx
> +          <Feedback />
à supprimer, car là c'est juste pour le test

2024-09-16 09:19 UTC, carolineBda requested changes

2024-09-16 09:19 UTC, carolineBda commented on packages/code-du-travail-frontend/src/modules/layout/feedback/FeedbackAnswered.tsx
> +const container = css({
pourquoi t'as besoin de ça ??

2024-09-16 09:19 UTC, carolineBda commented on packages/code-du-travail-frontend/src/modules/layout/feedback/FeedbackContent.tsx
> +                name: "checkboxes-1",
on mettrai pas des noms plus explicite ?

2024-09-16 09:19 UTC, carolineBda commented on packages/code-du-travail-frontend/src/modules/layout/feedback/tracking.ts
> +export const useFeedbackEvents = () => {
je trouve que le `useFeedbackEvents` n'est pas nécessairement utile

2024-09-16 09:19 UTC, carolineBda commented on packages/code-du-travail-frontend/src/modules/layout/feedback/tracking.ts
> +export enum MatomoFeedbackEventTertiary {
ne devrait pas être `export` parce que c'est utilisé directement dans les méthodes dessous, non ?

2024-09-16 09:19 UTC, carolineBda commented on packages/code-du-travail-frontend/src/modules/layout/feedback/tracking.ts
> +  const emitFeedback = (isPositive: boolean, baseUrl: string) => {
pour moi on devrait avoir 2 méthodes `export` :

```
   const emitNegativeFeedback = (baseUrl: string) => {
    emitNegativeFeedback(MatomoFeedbackEventTertiary.NEGATIVE, baseUrl)
  };

   const emitPositiveFeedback = (baseUrl: string) => {
    emitNegativeFeedback(MatomoFeedbackEventTertiary.POSITIVE, baseUrl)
  };
```

2024-09-16 09:19 UTC, carolineBda commented on packages/code-du-travail-frontend/src/modules/utils/index.ts
on a plus besoin de cette fonction parce que le [use-pathname]( https://nextjs.org/docs/app/api-reference/functions/use-pathname#returns) retourne juste le path sans les query params

2024-09-16 14:30 UTC, maxgfr commented on packages/code-du-travail-frontend/src/modules/layout/feedback/tracking.ts
> +    matopush([
wrapper dans un push ou on passe un objet

2024-09-17 08:22 UTC, Viczei commented on packages/code-du-travail-frontend/src/modules/layout/feedback/FeedbackContent.tsx
> +        textArea={true}
```suggestion
        textArea
```

2024-09-17 08:25 UTC, Viczei approved these changes

2024-09-17 15:14 UTC, carolineBda commented on packages/code-du-travail-frontend/src/modules/layout/feedback/tracking.ts
> +export const useFeedbackEvents = () => {
on a décidé de garder comme ça

2024-09-17 15:14 UTC, carolineBda commented on packages/code-du-travail-frontend/src/modules/layout/feedback/tracking.ts
> +    if (baseUrl) {
c'est possible qu'il ne soit pas définit ?

2024-09-17 15:15 UTC, maxgfr commented on packages/code-du-travail-frontend/src/modules/layout/feedback/tracking.ts
> +    if (baseUrl) {
Non, car il envoie un null via le pathName

2024-09-17 15:17 UTC, carolineBda commented on packages/code-du-travail-frontend/src/modules/utils/events.ts
> +  } else if (props.value) {
on ne passera jamais dans ce if parce qu’il y aura toujours un `props.name` définit donc on passera toujours dans if au dessus non ?
je sais pas comment le test au dessus arrive à passer

2024-09-17 15:25 UTC, maxgfr commented on packages/code-du-travail-frontend/src/modules/utils/events.ts
> +  } else if (props.value) {
Ah ouais, j'ai totalement chier dans la colle. J'ai un soucis pour tester en local, à la volée... :(

2024-09-18 15:10 UTC, merged

2024-09-19 07:14 UTC, carolineBda commented on packages/code-du-travail-frontend/src/modules/layout/infos/tracking.ts
> +    matopush([
t'as pas utilisé ta méthode `sendEvent` ?