chore: move contrinuting file
SocialGouv/code-du-travail-numerique pull request #615
Opened 2019-03-21 15:23 UTC by douglasduteil

<img src=https://media.giphy.com/media/3rgXBN6i9LIUg6lSLe/giphy.gif width=693>

2019-03-22 13:51 UTC, lionelB commented
@douglasduteil @revolunet personnellement le contributing n'est pas du tout à jour donc soit on le supprime et en fait un nouveau, soit on le modifie.

2019-03-25 18:03 UTC, revolunet commented
yep, outdated

2019-03-25 18:03 UTC, revolunet requested changes
outdated

2019-03-25 18:55 UTC, douglasduteil commented
Let's kill it with 🔥 then 😁

2019-03-25 18:55 UTC, douglasduteil commented
Let's kill it with 🔥 then 😁

2019-03-25 18:55 UTC, closed without merging