feat: rgga pas de alt sur image home
SocialGouv/code-du-travail-numerique pull request #6382
Opened 2024-12-20 14:09 UTC by Viczei

2025-01-08 08:59 UTC, maxgfr commented on packages/code-du-travail-frontend/src/modules/home/Search.tsx
> +              alt=""
on peut pas juste supprimer la propriété ?

2025-01-08 09:24 UTC, m-maillot commented on packages/code-du-travail-frontend/src/modules/home/Search.tsx
> +              alt=""
Si tu ne mets pas la propriété, elle ne va pas être mise dans le html. Il faut bien avoir un `alt=""` dans le code HTML. Cela me semble bon

2025-01-09 15:16 UTC, m-maillot requested changes
Il ya aussi le picto sur les thèmes à faire : https://github.com/SocialGouv/code-du-travail-numerique/issues/6291#issuecomment-2478753239

2025-01-21 10:09 UTC, carolineBda approved these changes

2025-01-21 10:12 UTC, merged