fixes in Company and ConventionForm to improve UX
SocialGouv/code-du-travail-numerique pull request #730
Opened 2019-04-15 08:57 UTC by adipasquale

cf issue #720

2019-04-15 09:14 UTC, revolunet approved these changes

2019-04-17 09:54 UTC, douglasduteil requested changes
@adipasquale Commit message format :police_car:

2019-05-09 13:42 UTC, revolunet approved these changes

2019-05-09 14:39 UTC, lionelB commented
@adipasquale the subject of the commit should be fix(frontend): since there is no sub-packages `ccn`

2019-05-13 10:00 UTC, douglasduteil approved these changes

2019-05-17 09:58 UTC, merged