feat(frontend): add meta to fiche service public and ministere travail
SocialGouv/code-du-travail-numerique pull request #773
Opened 2019-04-25 13:55 UTC by lionelB

add meta description to fiche-service-public and fiche ministere-travail

2019-04-25 14:01 UTC, UnbearableBear approved these changes
👍

2019-04-25 14:08 UTC, douglasduteil requested changes
- meta tag are out of topic here
- This is more a `feat(dataset)` then `feat(frontend)`

2019-04-25 14:08 UTC, douglasduteil commented on packages/code-du-travail-frontend/pages/fiche-ministere-travail.js
> +          <meta name="description" content={data._source.description} />
Duplicate with #771

2019-04-25 14:08 UTC, douglasduteil commented on packages/code-du-travail-frontend/pages/fiche-service-public.js
> +          <meta name="description" content={data._source.description} />
Duplicate with #771

2019-04-25 15:37 UTC, lionelB commented on packages/code-du-travail-frontend/pages/fiche-ministere-travail.js
> +          <meta name="description" content={data._source.description} />
not the same page

2019-04-25 15:37 UTC, lionelB commented on packages/code-du-travail-frontend/pages/fiche-service-public.js
> +          <meta name="description" content={data._source.description} />
not the same page

2019-04-26 10:19 UTC, douglasduteil approved these changes
Alright

2019-04-29 09:46 UTC, merged