ci: fix elasticsearch deployment
SocialGouv/code-du-travail-numerique pull request #939
Opened 2019-06-14 12:22 UTC by Virasack

2019-06-14 12:33 UTC, lionelB requested changes
@Virasack il y aussi un fichier docker avec une version d'elastic qui trainer (cf la PR https://github.com/SocialGouv/code-du-travail-numerique/pull/932/files)

2019-06-17 15:46 UTC, lionelB commented
@Virasack up!

2019-06-18 16:36 UTC, lionelB commented
@Virasack c'est mergé, tu peux mettre à jour stp ?

2019-06-20 09:31 UTC, revolunet commented
j'ai ajouté update de ES en 6.8.0 comme dans le docker-compose

2019-06-20 12:02 UTC, lionelB approved these changes
let's merge it :)

2019-06-20 13:25 UTC, merged