Lionelb bump elastic 7.2
SocialGouv/code-du-travail-numerique pull request #992
Opened 2019-07-02 15:13 UTC by lionelB

bump elastic to version 7.2

2019-07-02 16:24 UTC, douglasduteil requested changes

2019-07-02 16:24 UTC, douglasduteil commented on k8s/code-du-travail-data/deployment-code-du-travail-data.yml
> +      apt-get install curl -V;
revert it on alpine

2019-07-04 07:02 UTC, revolunet approved these changes

2019-07-04 07:41 UTC, douglasduteil approved these changes
LGTM

2019-07-04 08:23 UTC, merged